SET NOCOUNT ON;
DECLARE @Now nvarchar(50)=CONVERT(nvarchar(50),SYSUTCDATETIME(),126), @S nvarchar(20)=N'ORG_STRUCTURE';
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreen WHERE CompanyCode='TD' AND ScreenCode=@S) INSERT dbo.TDSTScreen(CompanyCode,ScreenCode,MenuCode,MDCode,ScreenName,ScreenType,RouteName,RoutePath,Module,LastUpdate) VALUES('TD',@S,'01005',NULL,N'Organization Structure','CRUD',N'organizationStructure',N'/support/organization-structure',N'AD',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenAPI WHERE CompanyCode='TD' AND ScreenCode=@S AND APIName='OrganizationStructure.List') INSERT dbo.TDSTScreenAPI VALUES('TD',@S,'OrganizationStructure.List','GET','/api/support/organization-structure','VIEW','Load organization units by login company scope',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenAPI WHERE CompanyCode='TD' AND ScreenCode=@S AND APIName='OrganizationStructure.Create') INSERT dbo.TDSTScreenAPI VALUES('TD',@S,'OrganizationStructure.Create','POST','/api/support/organization-structure','CREATE','Create division or department',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenAPI WHERE CompanyCode='TD' AND ScreenCode=@S AND APIName='OrganizationStructure.Update') INSERT dbo.TDSTScreenAPI VALUES('TD',@S,'OrganizationStructure.Update','PUT','/api/support/organization-structure/{id}','EDIT','Update organization unit',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenAPI WHERE CompanyCode='TD' AND ScreenCode=@S AND APIName='OrganizationStructure.Delete') INSERT dbo.TDSTScreenAPI VALUES('TD',@S,'OrganizationStructure.Delete','DELETE','/api/support/organization-structure/{id}','DELETE','Delete unit when no children or references',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenField WHERE CompanyCode='TD' AND ScreenCode=@S AND FieldName='UnitType') INSERT dbo.TDSTScreenField VALUES('TD',@S,'UnitType','Unit Type','nvarchar(10)','Y','N','Y','dbo.TDADOrganizationUnit','UnitType','DIV or DEP',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenField WHERE CompanyCode='TD' AND ScreenCode=@S AND FieldName='ParentOrgUnitID') INSERT dbo.TDSTScreenField VALUES('TD',@S,'ParentOrgUnitID','Parent Unit','bigint','N','N','Y','dbo.TDADOrganizationUnit','ParentOrgUnitID','Department parent division',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenField WHERE CompanyCode='TD' AND ScreenCode=@S AND FieldName='UnitCode') INSERT dbo.TDSTScreenField VALUES('TD',@S,'UnitCode','Unit Code','nvarchar(50)','Y','N','Y','dbo.TDADOrganizationUnit','UnitCode','Unique code within company and parent',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenField WHERE CompanyCode='TD' AND ScreenCode=@S AND FieldName='NameTH') INSERT dbo.TDSTScreenField VALUES('TD',@S,'NameTH','Name','nvarchar(200)','Y','N','Y','dbo.TDADOrganizationUnit','NameTH','Normalized duplicate validation',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenField WHERE CompanyCode='TD' AND ScreenCode=@S AND FieldName='IsActive') INSERT dbo.TDSTScreenField VALUES('TD',@S,'IsActive','Status','bit','Y','Y','Y','dbo.TDADOrganizationUnit','IsActive','Active status',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenPermission WHERE CompanyCode='TD' AND ScreenCode=@S AND PermissionCode='VIEW') INSERT dbo.TDSTScreenPermission VALUES('TD',@S,'VIEW','View','Load scoped organization data',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenPermission WHERE CompanyCode='TD' AND ScreenCode=@S AND PermissionCode='CREATE') INSERT dbo.TDSTScreenPermission VALUES('TD',@S,'CREATE','Create','Create unit',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenPermission WHERE CompanyCode='TD' AND ScreenCode=@S AND PermissionCode='EDIT') INSERT dbo.TDSTScreenPermission VALUES('TD',@S,'EDIT','Edit','Edit unit',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenPermission WHERE CompanyCode='TD' AND ScreenCode=@S AND PermissionCode='DELETE') INSERT dbo.TDSTScreenPermission VALUES('TD',@S,'DELETE','Delete','Delete unit',@Now);
IF NOT EXISTS (SELECT 1 FROM dbo.TDSTScreenPermission WHERE CompanyCode='TD' AND ScreenCode=@S AND PermissionCode='CHANGE_STATUS') INSERT dbo.TDSTScreenPermission VALUES('TD',@S,'CHANGE_STATUS','Change Status','Activate or deactivate unit',@Now);
GO
