using System.Data;
using LaooApi.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace LaooApi.Controllers;

[ApiController, Authorize, Route("api/service/pm")]
public sealed class ServicePmController(IConfiguration configuration) : ControllerBase
{
    long CompanyId => RegistryControllerSupport.ClaimLong(User,"company_id");
    long UserId => RegistryControllerSupport.ClaimLong(User,"user_id");
    async Task<SqlConnection> Open(CancellationToken t) => await RegistryControllerSupport.Open(configuration,t);
    async Task<bool> Allow(SqlConnection c,string menu,string action,CancellationToken t) => await CompanyProjectPermission.IsAllowedAsync(c,User,menu,action,t);
    static void Add(SqlCommand q,string n,SqlDbType t,object? v) => q.Parameters.Add(n,t).Value=v??DBNull.Value;
    async Task<bool> Enabled(SqlConnection c,CancellationToken t) { await using var q=new SqlCommand("SELECT CASE WHEN EXISTS(SELECT 1 FROM dbo.TDADCompanyProject CP JOIN dbo.TDADProject P ON P.ProjectID=CP.ProjectID AND P.ProjectCode=N'LAOO_SERVICE' AND P.IsActive=1 WHERE CP.CompanyID=@c AND CP.IsActive=1) THEN 1 ELSE 0 END",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);return Convert.ToBoolean(await q.ExecuteScalarAsync(t)); }
    async Task<IActionResult?> Guard(SqlConnection c,string menu,string action,CancellationToken t) => !await Enabled(c,t)||!await Allow(c,menu,action,t)?Forbid():null;
    static async Task<List<Dictionary<string,object?>>> Rows(SqlCommand q,CancellationToken t) { var x=new List<Dictionary<string,object?>>();await using var r=await q.ExecuteReaderAsync(t);while(await r.ReadAsync(t)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[char.ToLowerInvariant(r.GetName(i)[0])+r.GetName(i)[1..]]=r.IsDBNull(i)?null:r.GetValue(i);x.Add(d);}return x; }

    [HttpGet("plans")]
    public async Task<IActionResult> Plans([FromQuery]string? search,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","VIEW",t)is { } bad)return bad;await using var q=new SqlCommand("SELECT P.PmPlanID,P.PlanName,P.ItemTypeCode,P.IntervalUnit,P.IntervalValue,P.StartDate,P.IsActive,COUNT(A.PmPlanAssignmentID) AssetCount FROM dbo.TDADServicePmPlan P LEFT JOIN dbo.TDADServicePmPlanAssignment A ON A.PmPlanID=P.PmPlanID AND A.CompanyID=P.CompanyID AND A.IsActive=1 WHERE P.CompanyID=@c AND (@s=N'' OR P.PlanName LIKE N'%'+@s+N'%' OR P.ItemTypeCode LIKE N'%'+@s+N'%') GROUP BY P.PmPlanID,P.PlanName,P.ItemTypeCode,P.IntervalUnit,P.IntervalValue,P.StartDate,P.IsActive ORDER BY P.IsActive DESC,P.PlanName",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@s",SqlDbType.NVarChar,search?.Trim()??"");return Ok(new{items=await Rows(q,t)});}
    [HttpGet("item-types")]
    public async Task<IActionResult> Types(CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","VIEW",t)is { } bad)return bad;await using var q=new SqlCommand("SELECT DISTINCT I.ItemTypeCode FROM dbo.TDIVItem I JOIN dbo.TDIVItemUsage U ON U.CompanyID=I.CompanyID AND U.ItemID=I.ItemID AND U.UsageCode=N'EQUIPMENT' WHERE I.CompanyID=@c AND I.IsActive=1 AND NULLIF(I.ItemTypeCode,N'') IS NOT NULL ORDER BY I.ItemTypeCode",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);var rows=await Rows(q,t);return Ok(new{items=rows.Select(x=>new{itemTypeCode=x["itemTypeCode"]})});}
    [HttpGet("plans/{id:long}/assets")]
    public async Task<IActionResult> PlanAssets(long id,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","VIEW",t)is { } bad)return bad;await using var q=new SqlCommand("SELECT A.PmPlanAssignmentID,A.ItemInstanceID,X.SerialNo,I.ItemCode,I.ItemName,A.StartDate,A.NextDueDate,A.IsActive,CONCAT_WS(N' / ',B.BuildingNameTH,F.FloorNameTH,R.RoomCode) LocationSnapshot FROM dbo.TDADServicePmPlanAssignment A JOIN dbo.TDIVItemInstance X ON X.ItemInstanceID=A.ItemInstanceID AND X.CompanyID=A.CompanyID JOIN dbo.TDIVItem I ON I.ItemID=X.ItemID AND I.CompanyID=X.CompanyID LEFT JOIN dbo.TDADBuilding B ON B.BuildingID=X.BuildingID AND B.CompanyID=X.CompanyID LEFT JOIN dbo.TDADFloor F ON F.FloorID=X.FloorID AND F.BuildingID=X.BuildingID LEFT JOIN dbo.TDADRoom R ON R.RoomID=X.RoomID AND R.CompanyID=X.CompanyID WHERE A.CompanyID=@c AND A.PmPlanID=@id ORDER BY X.SerialNo",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);return Ok(new{items=await Rows(q,t)});}
    [HttpGet("plans/{id:long}/checklists")]
    public async Task<IActionResult> PlanChecklists(long id,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","VIEW",t)is{} bad)return bad;await using var q=new SqlCommand("SELECT C.PmChecklistID,C.ChecklistName FROM dbo.TDADServicePmPlanChecklist X JOIN dbo.TDADServicePmChecklist C ON C.PmChecklistID=X.PmChecklistID AND C.CompanyID=X.CompanyID WHERE X.CompanyID=@c AND X.PmPlanID=@id AND C.IsActive=1 ORDER BY C.ChecklistName",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);return Ok(new{items=await Rows(q,t)});}
    [HttpPut("plans/{id:long}/checklists")]
    public async Task<IActionResult> SetPlanChecklists(long id,[FromBody] IdList x,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","EDIT",t)is{} bad)return bad;await using var tx=await c.BeginTransactionAsync(t);await using(var d=new SqlCommand("DELETE FROM dbo.TDADServicePmPlanChecklist WHERE CompanyID=@c AND PmPlanID=@id",c,(SqlTransaction)tx)){Add(d,"@c",SqlDbType.BigInt,CompanyId);Add(d,"@id",SqlDbType.BigInt,id);await d.ExecuteNonQueryAsync(t);}foreach(var checklist in x.Ids.Distinct()){await using var q=new SqlCommand("INSERT dbo.TDADServicePmPlanChecklist(CompanyID,PmPlanID,PmChecklistID) SELECT @c,@id,C.PmChecklistID FROM dbo.TDADServicePmChecklist C WHERE C.CompanyID=@c AND C.PmChecklistID=@check AND C.IsActive=1 AND EXISTS(SELECT 1 FROM dbo.TDADServicePmPlan P WHERE P.CompanyID=@c AND P.PmPlanID=@id)",c,(SqlTransaction)tx);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);Add(q,"@check",SqlDbType.BigInt,checklist);await q.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return Ok(new{saved=true});}
    [HttpGet("assets")]
    public async Task<IActionResult> Assets([FromQuery]string itemTypeCode,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16001","VIEW",t)is { } bad)return bad;await using var q=new SqlCommand("SELECT X.ItemInstanceID,X.SerialNo,I.ItemCode,I.ItemName,CONCAT_WS(N' / ',B.BuildingNameTH,F.FloorNameTH,R.RoomCode) LocationSnapshot FROM dbo.TDIVItemInstance X JOIN dbo.TDIVItem I ON I.ItemID=X.ItemID AND I.CompanyID=X.CompanyID AND I.IsActive=1 AND I.ItemTypeCode=@type JOIN dbo.TDIVItemUsage U ON U.ItemID=I.ItemID AND U.CompanyID=I.CompanyID AND U.UsageCode=N'EQUIPMENT' LEFT JOIN dbo.TDADBuilding B ON B.BuildingID=X.BuildingID AND B.CompanyID=X.CompanyID LEFT JOIN dbo.TDADFloor F ON F.FloorID=X.FloorID AND F.BuildingID=X.BuildingID LEFT JOIN dbo.TDADRoom R ON R.RoomID=X.RoomID AND R.CompanyID=X.CompanyID WHERE X.CompanyID=@c AND X.StatusCode=N'INSTALLED' ORDER BY I.ItemName,X.SerialNo",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@type",SqlDbType.NVarChar,itemTypeCode);return Ok(new{items=await Rows(q,t)});}
    [HttpPost("plans")]
    public async Task<IActionResult> CreatePlan([FromBody] PmPlanInput x,CancellationToken t)=>await SavePlan(null,x,t);
    [HttpPut("plans/{id:long}")]
    public async Task<IActionResult> UpdatePlan(long id,[FromBody] PmPlanInput x,CancellationToken t)=>await SavePlan(id,x,t);
    async Task<IActionResult> SavePlan(long? id,PmPlanInput x,CancellationToken t){if(string.IsNullOrWhiteSpace(x.PlanName)||string.IsNullOrWhiteSpace(x.ItemTypeCode)||x.IntervalValue<1||!(x.IntervalUnit=="DAY"||x.IntervalUnit=="MONTH"))return BadRequest(new{message="ข้อมูลแผน PM ไม่ครบถ้วน"});await using var c=await Open(t);if(await Guard(c,"16001",id is null?"CREATE":"EDIT",t)is{} bad)return bad;await using var tx=await c.BeginTransactionAsync(t);try{long plan=id??0;if(id is null){await using var q=new SqlCommand("INSERT dbo.TDADServicePmPlan(CompanyID,PlanName,ItemTypeCode,IntervalUnit,IntervalValue,StartDate,IsActive,CreateBy) OUTPUT INSERTED.PmPlanID VALUES(@c,@n,@type,@u,@v,@d,@a,@by)",c,(SqlTransaction)tx);P(q,x);plan=Convert.ToInt64(await q.ExecuteScalarAsync(t));}else{await using var q=new SqlCommand("UPDATE dbo.TDADServicePmPlan SET PlanName=@n,ItemTypeCode=@type,IntervalUnit=@u,IntervalValue=@v,StartDate=@d,IsActive=@a,UpdateBy=@by,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND PmPlanID=@id",c,(SqlTransaction)tx);P(q,x);Add(q,"@id",SqlDbType.BigInt,id);if(await q.ExecuteNonQueryAsync(t)==0){await tx.RollbackAsync(t);return NotFound();}}
foreach(var asset in x.ItemInstanceIds.Distinct()){await using var q=new SqlCommand("IF EXISTS(SELECT 1 FROM dbo.TDIVItemInstance X JOIN dbo.TDIVItem I ON I.ItemID=X.ItemID AND I.CompanyID=X.CompanyID JOIN dbo.TDIVItemUsage U ON U.ItemID=I.ItemID AND U.CompanyID=I.CompanyID AND U.UsageCode=N'EQUIPMENT' WHERE X.CompanyID=@c AND X.ItemInstanceID=@asset AND X.StatusCode=N'INSTALLED' AND I.IsActive=1 AND I.ItemTypeCode=@type) MERGE dbo.TDADServicePmPlanAssignment AS T USING(SELECT @c CompanyID,@plan PmPlanID,@asset ItemInstanceID) S ON T.CompanyID=S.CompanyID AND T.PmPlanID=S.PmPlanID AND T.ItemInstanceID=S.ItemInstanceID WHEN MATCHED THEN UPDATE SET IsActive=1,StartDate=@d,NextDueDate=COALESCE(T.NextDueDate,@d),UpdateDate=SYSUTCDATETIME(),UpdateBy=@by WHEN NOT MATCHED THEN INSERT(CompanyID,PmPlanID,ItemInstanceID,StartDate,NextDueDate,CreateBy) VALUES(@c,@plan,@asset,@d,@d,@by);",c,(SqlTransaction)tx);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@plan",SqlDbType.BigInt,plan);Add(q,"@asset",SqlDbType.BigInt,asset);Add(q,"@type",SqlDbType.NVarChar,x.ItemTypeCode);Add(q,"@d",SqlDbType.Date,x.StartDate.Date);Add(q,"@by",SqlDbType.BigInt,UserId);await q.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return Ok(new{pmPlanId=plan});}catch{await tx.RollbackAsync(t);throw;}}
    void P(SqlCommand q,PmPlanInput x){Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@n",SqlDbType.NVarChar,x.PlanName.Trim());Add(q,"@type",SqlDbType.NVarChar,x.ItemTypeCode.Trim());Add(q,"@u",SqlDbType.NVarChar,x.IntervalUnit);Add(q,"@v",SqlDbType.Int,x.IntervalValue);Add(q,"@d",SqlDbType.Date,x.StartDate.Date);Add(q,"@a",SqlDbType.Bit,x.IsActive);Add(q,"@by",SqlDbType.BigInt,UserId);}

    [HttpGet("checklists")]
    public async Task<IActionResult> Checklists(CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16002","VIEW",t)is{} bad)return bad;await using var q=new SqlCommand("SELECT C.PmChecklistID,C.ChecklistName,C.IsActive,COUNT(I.PmChecklistItemID) ItemCount FROM dbo.TDADServicePmChecklist C LEFT JOIN dbo.TDADServicePmChecklistItem I ON I.PmChecklistID=C.PmChecklistID AND I.CompanyID=C.CompanyID AND I.IsActive=1 WHERE C.CompanyID=@c GROUP BY C.PmChecklistID,C.ChecklistName,C.IsActive ORDER BY C.ChecklistName",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);return Ok(new{items=await Rows(q,t)});}
    [HttpPost("checklists")]
    public async Task<IActionResult> CreateChecklist([FromBody] ChecklistInput x,CancellationToken t){if(string.IsNullOrWhiteSpace(x.ChecklistName)||x.Items.Count==0)return BadRequest(new{message="กรุณาระบุชื่อและรายการตรวจ"});await using var c=await Open(t);if(await Guard(c,"16002","CREATE",t)is{} bad)return bad;await using var tx=await c.BeginTransactionAsync(t);await using var h=new SqlCommand("INSERT dbo.TDADServicePmChecklist(CompanyID,ChecklistName,IsActive,CreateBy) OUTPUT INSERTED.PmChecklistID VALUES(@c,@n,@a,@by)",c,(SqlTransaction)tx);Add(h,"@c",SqlDbType.BigInt,CompanyId);Add(h,"@n",SqlDbType.NVarChar,x.ChecklistName.Trim());Add(h,"@a",SqlDbType.Bit,x.IsActive);Add(h,"@by",SqlDbType.BigInt,UserId);var id=Convert.ToInt64(await h.ExecuteScalarAsync(t));var n=1;foreach(var item in x.Items.Where(z=>!string.IsNullOrWhiteSpace(z.Text))){await using var q=new SqlCommand("INSERT dbo.TDADServicePmChecklistItem(CompanyID,PmChecklistID,SequenceNo,CheckItem,IsRequired,IsActive) VALUES(@c,@id,@n,@x,@r,1)",c,(SqlTransaction)tx);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);Add(q,"@n",SqlDbType.Int,n++);Add(q,"@x",SqlDbType.NVarChar,item.Text.Trim());Add(q,"@r",SqlDbType.Bit,item.Required);await q.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return Ok(new{pmChecklistId=id});}

    [HttpGet("work-orders")]
    public async Task<IActionResult> WorkOrders([FromQuery]string? status,[FromQuery]DateTime? from,[FromQuery]DateTime? to,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16003","VIEW",t)is{} bad)return bad;await using var q=new SqlCommand("SELECT W.PmWorkOrderID,W.DueDate,W.StatusCode,W.PlanNameSnapshot,W.ItemSnapshot,W.LocationSnapshot,W.StartedDate,W.CompletedDate,W.ResultDetail,W.SkipReason FROM dbo.TDADServicePmWorkOrder W WHERE W.CompanyID=@c AND (@s=N'' OR W.StatusCode=@s) AND W.DueDate>=@f AND W.DueDate<=@t ORDER BY W.DueDate,W.PmWorkOrderID",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@s",SqlDbType.NVarChar,status?.Trim()??"");Add(q,"@f",SqlDbType.Date,(from??DateTime.Today.AddDays(-30)).Date);Add(q,"@t",SqlDbType.Date,(to??DateTime.Today.AddMonths(3)).Date);return Ok(new{items=await Rows(q,t)});}
    [HttpGet("work-orders/{id:long}")]
    public async Task<IActionResult> WorkOrder(long id,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16003","VIEW",t)is{} bad)return bad;await using var h=new SqlCommand("SELECT PmWorkOrderID,DueDate,StatusCode,PlanNameSnapshot,ItemSnapshot,LocationSnapshot,StartedDate,CompletedDate,ResultDetail,SkipReason FROM dbo.TDADServicePmWorkOrder WHERE CompanyID=@c AND PmWorkOrderID=@id",c);Add(h,"@c",SqlDbType.BigInt,CompanyId);Add(h,"@id",SqlDbType.BigInt,id);var head=await Rows(h,t);if(head.Count==0)return NotFound();await using var q=new SqlCommand("SELECT PmWorkOrderCheckID,SequenceNo,CheckItemSnapshot,IsRequired,IsChecked,ResultNote FROM dbo.TDADServicePmWorkOrderCheck WHERE CompanyID=@c AND PmWorkOrderID=@id ORDER BY SequenceNo,PmWorkOrderCheckID",c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);return Ok(new{workOrder=head[0],checks=await Rows(q,t)});}
    [HttpPut("work-orders/{id:long}/checks")]
    public async Task<IActionResult> SaveChecks(long id,[FromBody] PmCheckResultInput x,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16003","EDIT",t)is{} bad)return bad;await using var tx=await c.BeginTransactionAsync(t);foreach(var line in x.Items){await using var q=new SqlCommand("UPDATE C SET IsChecked=@checked,ResultNote=@note FROM dbo.TDADServicePmWorkOrderCheck C JOIN dbo.TDADServicePmWorkOrder W ON W.PmWorkOrderID=C.PmWorkOrderID AND W.CompanyID=C.CompanyID WHERE C.CompanyID=@c AND C.PmWorkOrderID=@id AND C.PmWorkOrderCheckID=@check AND W.StatusCode=N'IN_PROGRESS'",c,(SqlTransaction)tx);Add(q,"@checked",SqlDbType.Bit,line.IsChecked);Add(q,"@note",SqlDbType.NVarChar,line.ResultNote?.Trim());Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);Add(q,"@check",SqlDbType.BigInt,line.PmWorkOrderCheckId);await q.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return Ok(new{saved=true});}
    [HttpPost("work-orders/generate")]
    public async Task<IActionResult> Generate(CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16003","CREATE",t)is{} bad)return bad;const string sql="INSERT dbo.TDADServicePmWorkOrder(CompanyID,PmPlanAssignmentID,ItemInstanceID,DueDate,PlanNameSnapshot,ItemSnapshot,LocationSnapshot,CreateBy) SELECT A.CompanyID,A.PmPlanAssignmentID,A.ItemInstanceID,A.NextDueDate,P.PlanName,CONCAT(I.ItemCode,N' / ',I.ItemName,N' / ',X.SerialNo),CONCAT_WS(N' / ',B.BuildingNameTH,F.FloorNameTH,R.RoomCode),@by FROM dbo.TDADServicePmPlanAssignment A JOIN dbo.TDADServicePmPlan P ON P.PmPlanID=A.PmPlanID AND P.CompanyID=A.CompanyID AND P.IsActive=1 JOIN dbo.TDIVItemInstance X ON X.ItemInstanceID=A.ItemInstanceID AND X.CompanyID=A.CompanyID AND X.StatusCode=N'INSTALLED' JOIN dbo.TDIVItem I ON I.ItemID=X.ItemID AND I.CompanyID=X.CompanyID AND I.IsActive=1 JOIN dbo.TDIVItemUsage U ON U.ItemID=I.ItemID AND U.CompanyID=I.CompanyID AND U.UsageCode=N'EQUIPMENT' LEFT JOIN dbo.TDADBuilding B ON B.BuildingID=X.BuildingID AND B.CompanyID=X.CompanyID LEFT JOIN dbo.TDADFloor F ON F.FloorID=X.FloorID AND F.BuildingID=X.BuildingID LEFT JOIN dbo.TDADRoom R ON R.RoomID=X.RoomID AND R.CompanyID=X.CompanyID WHERE A.CompanyID=@c AND A.IsActive=1 AND A.NextDueDate<=CAST(SYSUTCDATETIME() AS date) AND NOT EXISTS(SELECT 1 FROM dbo.TDADServicePmWorkOrder W WHERE W.CompanyID=A.CompanyID AND W.PmPlanAssignmentID=A.PmPlanAssignmentID AND W.DueDate=A.NextDueDate)";await using var q=new SqlCommand(sql,c);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@by",SqlDbType.BigInt,UserId);var count=await q.ExecuteNonQueryAsync(t);const string checks="INSERT dbo.TDADServicePmWorkOrderCheck(CompanyID,PmWorkOrderID,PmChecklistItemID,SequenceNo,CheckItemSnapshot,IsRequired) SELECT W.CompanyID,W.PmWorkOrderID,I.PmChecklistItemID,I.SequenceNo,I.CheckItem,I.IsRequired FROM dbo.TDADServicePmWorkOrder W JOIN dbo.TDADServicePmPlanAssignment A ON A.PmPlanAssignmentID=W.PmPlanAssignmentID JOIN dbo.TDADServicePmPlanChecklist PC ON PC.CompanyID=W.CompanyID AND PC.PmPlanID=A.PmPlanID JOIN dbo.TDADServicePmChecklistItem I ON I.CompanyID=W.CompanyID AND I.PmChecklistID=PC.PmChecklistID AND I.IsActive=1 WHERE W.CompanyID=@c AND NOT EXISTS(SELECT 1 FROM dbo.TDADServicePmWorkOrderCheck C WHERE C.PmWorkOrderID=W.PmWorkOrderID)";await using var copy=new SqlCommand(checks,c);Add(copy,"@c",SqlDbType.BigInt,CompanyId);await copy.ExecuteNonQueryAsync(t);return Ok(new{generated=count});}
    [HttpPost("work-orders/{id:long}/start")]
    public async Task<IActionResult> Start(long id,CancellationToken t)=>await Status(id,"PENDING","IN_PROGRESS",null,t);
    [HttpPost("work-orders/{id:long}/complete")]
    public async Task<IActionResult> Complete(long id,[FromBody] CompletePmInput x,CancellationToken t)=>string.IsNullOrWhiteSpace(x.ResultDetail)?BadRequest(new{message="กรุณาระบุผลการตรวจ"}):await Status(id,"IN_PROGRESS","COMPLETED",x.ResultDetail.Trim(),t);
    [HttpPost("work-orders/{id:long}/skip")]
    public async Task<IActionResult> Skip(long id,[FromBody] CompletePmInput x,CancellationToken t)=>string.IsNullOrWhiteSpace(x.ResultDetail)?BadRequest(new{message="กรุณาระบุเหตุผลการข้าม"}):await Status(id,"PENDING","SKIPPED",x.ResultDetail.Trim(),t);
    async Task<IActionResult> Status(long id,string expected,string next,string? text,CancellationToken t){await using var c=await Open(t);if(await Guard(c,"16003","EDIT",t)is{} bad)return bad;await using var tx=await c.BeginTransactionAsync(t);await using var q=new SqlCommand("UPDATE dbo.TDADServicePmWorkOrder SET StatusCode=@next,StartedDate=CASE WHEN @next=N'IN_PROGRESS' THEN SYSUTCDATETIME() ELSE StartedDate END,StartedBy=CASE WHEN @next=N'IN_PROGRESS' THEN @by ELSE StartedBy END,CompletedDate=CASE WHEN @next IN(N'COMPLETED',N'SKIPPED') THEN SYSUTCDATETIME() ELSE CompletedDate END,CompletedBy=CASE WHEN @next IN(N'COMPLETED',N'SKIPPED') THEN @by ELSE CompletedBy END,ResultDetail=CASE WHEN @next=N'COMPLETED' THEN @text ELSE ResultDetail END,SkipReason=CASE WHEN @next=N'SKIPPED' THEN @text ELSE SkipReason END,UpdateBy=@by,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND PmWorkOrderID=@id AND StatusCode=@expected",c,(SqlTransaction)tx);Add(q,"@next",SqlDbType.NVarChar,next);Add(q,"@by",SqlDbType.BigInt,UserId);Add(q,"@text",SqlDbType.NVarChar,text);Add(q,"@c",SqlDbType.BigInt,CompanyId);Add(q,"@id",SqlDbType.BigInt,id);Add(q,"@expected",SqlDbType.NVarChar,expected);if(await q.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return Conflict(new{message="สถานะงาน PM ถูกเปลี่ยนแล้ว กรุณาโหลดข้อมูลใหม่"});}if(next is "COMPLETED" or "SKIPPED"){await using var u=new SqlCommand("UPDATE A SET NextDueDate=CASE P.IntervalUnit WHEN N'DAY' THEN DATEADD(day,P.IntervalValue,CAST(SYSUTCDATETIME() AS date)) ELSE DATEADD(month,P.IntervalValue,CAST(SYSUTCDATETIME() AS date)) END,UpdateDate=SYSUTCDATETIME(),UpdateBy=@by FROM dbo.TDADServicePmPlanAssignment A JOIN dbo.TDADServicePmWorkOrder W ON W.PmPlanAssignmentID=A.PmPlanAssignmentID JOIN dbo.TDADServicePmPlan P ON P.PmPlanID=A.PmPlanID WHERE A.CompanyID=@c AND W.CompanyID=@c AND W.PmWorkOrderID=@id",c,(SqlTransaction)tx);Add(u,"@by",SqlDbType.BigInt,UserId);Add(u,"@c",SqlDbType.BigInt,CompanyId);Add(u,"@id",SqlDbType.BigInt,id);await u.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return Ok(new{saved=true,statusCode=next});}
}
public sealed record PmPlanInput(string PlanName,string ItemTypeCode,string IntervalUnit,int IntervalValue,DateTime StartDate,bool IsActive,List<long> ItemInstanceIds);
public sealed record ChecklistItemInput(string Text,bool Required);
public sealed record ChecklistInput(string ChecklistName,bool IsActive,List<ChecklistItemInput> Items);
public sealed record CompletePmInput(string ResultDetail);
public sealed record IdList(List<long> Ids);
public sealed record PmCheckResultItem(long PmWorkOrderCheckId,bool IsChecked,string? ResultNote);
public sealed record PmCheckResultInput(List<PmCheckResultItem> Items);
