name: laoo_project
description: LAOO Project Management feature package for the Center host.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.4.0
  laoo_shared_core:
    path: ../../packages/laoo_shared_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
