using System.Data;
using System.Security.Claims;
using Laoo.Shared.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
namespace LaooTimeModule.Controllers;

[ApiController,Authorize,Route("api/time/rotation-patterns")]
public sealed class RotationPatternsController(IConfiguration configuration):ControllerBase
{
 private const string MenuCode="27003";
 public sealed record DayRequest(int DayNo,bool IsDayOff,long? ShiftTemplateId);
 public sealed record SaveRequest(string PatternCode,string PatternName,string? DescriptionText,bool IsActive,DateOnly EffectiveFrom,int CycleDays,List<DayRequest> Days,string? RowVersion);
 [HttpGet("actions")]public async Task<IActionResult>Actions(CancellationToken t){if(!Scope(out _,out _))return Forbid();await using var c=await Open(t);return Ok(new{menuCode=MenuCode,caption=await Caption(c,t),screenType=1,view=await Can(c,"VIEW",t),create=await Can(c,"CREATE",t),edit=await Can(c,"EDIT",t),delete=await Can(c,"DELETE",t)});}
 [HttpGet("shift-options")]public async Task<IActionResult>Shifts(CancellationToken t){if(!Scope(out var co,out _))return Forbid();await using var c=await Open(t);if(!await Can(c,"VIEW",t))return Forbid();await using var q=new SqlCommand("SELECT ShiftTemplateID,ShiftCode,ShiftName FROM dbo.TDTMShiftTemplate WHERE CompanyID=@C AND IsActive=1 ORDER BY ShiftCode",c);Add(q,"@C",SqlDbType.BigInt,co);await using var r=await q.ExecuteReaderAsync(t);var x=new List<object>();while(await r.ReadAsync(t))x.Add(new{id=r.GetInt64(0),code=r.GetString(1),name=r.GetString(2)});return Ok(x);}
 [HttpGet]public async Task<IActionResult>List([FromQuery]string?search,[FromQuery]bool?isActive,[FromQuery]int page=1,[FromQuery]int pageSize=30,CancellationToken t=default){if(!Scope(out var co,out _))return Forbid();if(page<1||pageSize is<1 or>100)return BadRequest(new{message="หน้าหรือจำนวนรายการต่อหน้าไม่ถูกต้อง"});await using var c=await Open(t);if(!await Can(c,"VIEW",t))return Forbid();search=Clean(search);const string w="FROM dbo.TDTMRotationPattern P OUTER APPLY(SELECT TOP(1) V.RotationPatternVersionID,V.EffectiveFrom,V.CycleDays FROM dbo.TDTMRotationPatternVersion V WHERE V.CompanyID=P.CompanyID AND V.RotationPatternID=P.RotationPatternID AND V.IsActive=1 AND V.EffectiveTo IS NULL ORDER BY V.EffectiveFrom DESC)V WHERE P.CompanyID=@C AND (@A IS NULL OR P.IsActive=@A) AND (@S IS NULL OR P.PatternCode LIKE N'%'+@S+N'%' OR P.PatternName LIKE N'%'+@S+N'%')";await using var count=new SqlCommand($"SELECT COUNT_BIG(1) {w}",c);Bind(count,co,search,isActive);var total=Convert.ToInt64(await count.ExecuteScalarAsync(t));await using var q=new SqlCommand($"SELECT P.RotationPatternID,P.PatternCode,P.PatternName,P.DescriptionText,P.IsActive,V.EffectiveFrom,V.CycleDays,CONVERT(varchar(32),P.RowVersion,2) {w} ORDER BY P.PatternCode OFFSET @O ROWS FETCH NEXT @N ROWS ONLY",c);Bind(q,co,search,isActive);Add(q,"@O",SqlDbType.Int,(page-1)*pageSize);Add(q,"@N",SqlDbType.Int,pageSize);await using var r=await q.ExecuteReaderAsync(t);var items=new List<object>();while(await r.ReadAsync(t))items.Add(new{rotationPatternId=r.GetInt64(0),patternCode=r.GetString(1),patternName=r.GetString(2),descriptionText=r.IsDBNull(3)?null:r.GetString(3),isActive=r.GetBoolean(4),effectiveFrom=r.IsDBNull(5)?null:(DateOnly?)DateOnly.FromDateTime(r.GetDateTime(5)),cycleDays=r.IsDBNull(6)?0:r.GetInt32(6),rowVersion=r.GetString(7)});return Ok(new{total,page,pageSize,items});}
 [HttpGet("{id:long}")]public async Task<IActionResult>Get(long id,CancellationToken t){if(!Scope(out var co,out _))return Forbid();await using var c=await Open(t);if(!await Can(c,"VIEW",t))return Forbid();await using var q=new SqlCommand("SELECT P.PatternCode,P.PatternName,P.DescriptionText,P.IsActive,V.RotationPatternVersionID,V.EffectiveFrom,V.CycleDays,CONVERT(varchar(32),P.RowVersion,2) FROM dbo.TDTMRotationPattern P JOIN dbo.TDTMRotationPatternVersion V ON V.CompanyID=P.CompanyID AND V.RotationPatternID=P.RotationPatternID WHERE P.CompanyID=@C AND P.RotationPatternID=@ID AND V.IsActive=1 AND V.EffectiveTo IS NULL",c);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@ID",SqlDbType.BigInt,id);await using var r=await q.ExecuteReaderAsync(t);if(!await r.ReadAsync(t))return NotFound();var code=r.GetString(0);var name=r.GetString(1);var desc=r.IsDBNull(2)?null:r.GetString(2);var active=r.GetBoolean(3);var vid=r.GetInt64(4);var date=DateOnly.FromDateTime(r.GetDateTime(5));var cycle=r.GetInt32(6);var rv=r.GetString(7);await r.CloseAsync();await using var d=new SqlCommand("SELECT D.DayNo,D.IsDayOff,D.ShiftTemplateID,S.ShiftCode,S.ShiftName FROM dbo.TDTMRotationDay D LEFT JOIN dbo.TDTMShiftTemplate S ON S.CompanyID=D.CompanyID AND S.ShiftTemplateID=D.ShiftTemplateID WHERE D.CompanyID=@C AND D.RotationPatternVersionID=@V ORDER BY D.DayNo",c);Add(d,"@C",SqlDbType.BigInt,co);Add(d,"@V",SqlDbType.BigInt,vid);await using var dr=await d.ExecuteReaderAsync(t);var days=new List<object>();while(await dr.ReadAsync(t))days.Add(new{dayNo=dr.GetInt32(0),isDayOff=dr.GetBoolean(1),shiftTemplateId=dr.IsDBNull(2)?null:(long?)dr.GetInt64(2),shiftCode=dr.IsDBNull(3)?null:dr.GetString(3),shiftName=dr.IsDBNull(4)?null:dr.GetString(4)});return Ok(new{rotationPatternId=id,patternCode=code,patternName=name,descriptionText=desc,isActive=active,effectiveFrom=date,cycleDays=cycle,days,rowVersion=rv});}
 [HttpPost]public async Task<IActionResult>Create(SaveRequest x,CancellationToken t)=>await Save(null,x,t);
 [HttpPut("{id:long}")]public async Task<IActionResult>Update(long id,SaveRequest x,CancellationToken t)=>await Save(id,x,t);
 private async Task<IActionResult>Save(long?id,SaveRequest x,CancellationToken t){if(!Scope(out var co,out var user))return Forbid();var error=Validate(x);if(error!=null)return BadRequest(new{message=error});await using var c=await Open(t);if(!await Can(c,id==null?"CREATE":"EDIT",t))return Forbid();await using var tx=(SqlTransaction)await c.BeginTransactionAsync(IsolationLevel.Serializable,t);try{long patternId;if(id==null){await using var q=new SqlCommand("INSERT dbo.TDTMRotationPattern(CompanyID,PatternCode,PatternName,DescriptionText,IsActive,CreateBy) OUTPUT INSERTED.RotationPatternID VALUES(@C,@Code,@Name,@D,@A,@U)",c,tx);Header(q,co,user,x);patternId=Convert.ToInt64(await q.ExecuteScalarAsync(t));}else{if(string.IsNullOrWhiteSpace(x.RowVersion))return BadRequest(new{message="ไม่พบ Version ของข้อมูล"});patternId=id.Value;await using var q=new SqlCommand("UPDATE dbo.TDTMRotationPattern SET PatternCode=@Code,PatternName=@Name,DescriptionText=@D,IsActive=@A,UpdateDate=SYSDATETIME(),UpdateBy=@U WHERE CompanyID=@C AND RotationPatternID=@ID AND RowVersion=CONVERT(binary(8),@RV,2)",c,tx);Header(q,co,user,x);Add(q,"@ID",SqlDbType.BigInt,patternId);Add(q,"@RV",SqlDbType.VarChar,x.RowVersion,32);if(await q.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return Conflict(new{message="ข้อมูลถูกแก้ไขแล้ว กรุณาโหลดใหม่"});}}
 long versionId;await using(var find=new SqlCommand("SELECT TOP(1) RotationPatternVersionID,EffectiveFrom FROM dbo.TDTMRotationPatternVersion WITH(UPDLOCK,HOLDLOCK) WHERE CompanyID=@C AND RotationPatternID=@ID AND IsActive=1 AND EffectiveTo IS NULL",c,tx)){Add(find,"@C",SqlDbType.BigInt,co);Add(find,"@ID",SqlDbType.BigInt,patternId);await using var r=await find.ExecuteReaderAsync(t);if(await r.ReadAsync(t)){versionId=r.GetInt64(0);var start=DateOnly.FromDateTime(r.GetDateTime(1));await r.CloseAsync();if(start>x.EffectiveFrom)throw new InvalidOperationException("วันที่เริ่มใช้ต้องไม่ก่อน Version ที่บันทึกไว้");if(start==x.EffectiveFrom){await using var q=new SqlCommand("DELETE dbo.TDTMRotationDay WHERE CompanyID=@C AND RotationPatternVersionID=@V;UPDATE dbo.TDTMRotationPatternVersion SET CycleDays=@Days WHERE CompanyID=@C AND RotationPatternVersionID=@V",c,tx);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@V",SqlDbType.BigInt,versionId);Add(q,"@Days",SqlDbType.Int,x.CycleDays);await q.ExecuteNonQueryAsync(t);}else{await using var close=new SqlCommand("UPDATE dbo.TDTMRotationPatternVersion SET EffectiveTo=DATEADD(day,-1,@Date) WHERE CompanyID=@C AND RotationPatternVersionID=@V",c,tx);Add(close,"@Date",SqlDbType.Date,x.EffectiveFrom.ToDateTime(TimeOnly.MinValue));Add(close,"@C",SqlDbType.BigInt,co);Add(close,"@V",SqlDbType.BigInt,versionId);await close.ExecuteNonQueryAsync(t);versionId=await NewVersion(c,tx,co,patternId,user,x,t);}}else{await r.CloseAsync();versionId=await NewVersion(c,tx,co,patternId,user,x,t);}}
 foreach(var day in x.Days){if(day.ShiftTemplateId!=null&&!await OwnShift(c,tx,co,day.ShiftTemplateId.Value,t))throw new InvalidOperationException("พบกะที่ไม่ได้อยู่ในบริษัทหรือปิดใช้งานแล้ว");await using var q=new SqlCommand("INSERT dbo.TDTMRotationDay(CompanyID,RotationPatternVersionID,DayNo,IsDayOff,ShiftTemplateID,CreateBy)VALUES(@C,@V,@Day,@Off,@Shift,@U)",c,tx);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@V",SqlDbType.BigInt,versionId);Add(q,"@Day",SqlDbType.Int,day.DayNo);Add(q,"@Off",SqlDbType.Bit,day.IsDayOff);Add(q,"@Shift",SqlDbType.BigInt,day.ShiftTemplateId);Add(q,"@U",SqlDbType.BigInt,user);await q.ExecuteNonQueryAsync(t);}await tx.CommitAsync(t);return id==null?Created(string.Empty,new{rotationPatternId=patternId}):NoContent();}catch(InvalidOperationException e){await tx.RollbackAsync(t);return Conflict(new{message=e.Message});}catch(SqlException e)when(e.Number is 2601 or 2627){await tx.RollbackAsync(t);return Conflict(new{message="รหัสรูปแบบหรือวันที่เริ่มใช้ซ้ำกับข้อมูลเดิม"});}}
 [HttpDelete("{id:long}")]public async Task<IActionResult>Delete(long id,[FromQuery]string rowVersion,CancellationToken t){if(!Scope(out var co,out var user))return Forbid();await using var c=await Open(t);if(!await Can(c,"DELETE",t))return Forbid();await using var q=new SqlCommand("IF EXISTS(SELECT 1 FROM dbo.TDTMGroupShiftRotation WHERE CompanyID=@C AND RotationPatternID=@ID) THROW 52332,N'รูปแบบนี้ถูกใช้กับกลุ่มแล้ว ไม่สามารถลบได้',1;UPDATE dbo.TDTMRotationPattern SET IsActive=0,UpdateDate=SYSDATETIME(),UpdateBy=@U WHERE CompanyID=@C AND RotationPatternID=@ID AND RowVersion=CONVERT(binary(8),@RV,2)",c);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@ID",SqlDbType.BigInt,id);Add(q,"@U",SqlDbType.BigInt,user);Add(q,"@RV",SqlDbType.VarChar,rowVersion,32);try{return await q.ExecuteNonQueryAsync(t)==1?NoContent():Conflict(new{message="ข้อมูลถูกแก้ไขแล้ว กรุณาโหลดใหม่"});}catch(SqlException e)when(e.Number==52332){return Conflict(new{message=e.Message});}}
 private static string?Validate(SaveRequest x){if(Clean(x.PatternCode)is null||x.PatternCode.Trim().Length>30)return"กรุณาระบุรหัสรูปแบบไม่เกิน 30 ตัวอักษร";if(Clean(x.PatternName)is null||x.PatternName.Trim().Length>150)return"กรุณาระบุชื่อรูปแบบไม่เกิน 150 ตัวอักษร";if(x.EffectiveFrom<DateOnly.FromDateTime(DateTime.Today))return"วันที่เริ่มใช้ต้องไม่ย้อนหลัง";if(x.CycleDays is<1 or>366||x.Days.Count!=x.CycleDays||!Enumerable.Range(1,x.CycleDays).SequenceEqual(x.Days.Select(d=>d.DayNo).Order()))return"ต้องกำหนดวันในวงรอบให้ครบและไม่ซ้ำ";if(x.Days.Any(d=>(d.IsDayOff&&d.ShiftTemplateId!=null)||(!d.IsDayOff&&d.ShiftTemplateId==null)))return"แต่ละวันต้องเลือกวันหยุดหรือกะทำงานอย่างใดอย่างหนึ่ง";return null;}
 private static async Task<long>NewVersion(SqlConnection c,SqlTransaction tx,long co,long id,long user,SaveRequest x,CancellationToken t){await using var q=new SqlCommand("INSERT dbo.TDTMRotationPatternVersion(CompanyID,RotationPatternID,EffectiveFrom,CycleDays,IsActive,CreateBy)OUTPUT INSERTED.RotationPatternVersionID VALUES(@C,@ID,@Date,@Days,1,@U)",c,tx);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@ID",SqlDbType.BigInt,id);Add(q,"@Date",SqlDbType.Date,x.EffectiveFrom.ToDateTime(TimeOnly.MinValue));Add(q,"@Days",SqlDbType.Int,x.CycleDays);Add(q,"@U",SqlDbType.BigInt,user);return Convert.ToInt64(await q.ExecuteScalarAsync(t));}
 private static async Task<bool>OwnShift(SqlConnection c,SqlTransaction tx,long co,long id,CancellationToken t){await using var q=new SqlCommand("SELECT COUNT(1) FROM dbo.TDTMShiftTemplate WHERE CompanyID=@C AND ShiftTemplateID=@ID AND IsActive=1",c,tx);Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@ID",SqlDbType.BigInt,id);return Convert.ToInt32(await q.ExecuteScalarAsync(t))==1;}
 private static void Header(SqlCommand q,long co,long u,SaveRequest x){Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@Code",SqlDbType.NVarChar,x.PatternCode.Trim().ToUpperInvariant(),30);Add(q,"@Name",SqlDbType.NVarChar,x.PatternName.Trim(),150);Add(q,"@D",SqlDbType.NVarChar,Clean(x.DescriptionText),500);Add(q,"@A",SqlDbType.Bit,x.IsActive);Add(q,"@U",SqlDbType.BigInt,u);}private static void Bind(SqlCommand q,long co,string?s,bool?a){Add(q,"@C",SqlDbType.BigInt,co);Add(q,"@S",SqlDbType.NVarChar,s,150);Add(q,"@A",SqlDbType.Bit,a);}private async Task<bool>Can(SqlConnection c,string a,CancellationToken t)=>await CompanyMenuAccess.IsAllowedAsync(c,User,MenuCode,a,t);private async Task<SqlConnection>Open(CancellationToken t){var c=new SqlConnection(configuration.GetConnectionString("LaooDatabase"));await c.OpenAsync(t);return c;}private bool Scope(out long c,out long u){c=0;u=0;return string.Equals(User.FindFirstValue("user_type"),"COMPANY_USER",StringComparison.OrdinalIgnoreCase)&&long.TryParse(User.FindFirstValue("company_id"),out c)&&long.TryParse(User.FindFirstValue("user_id"),out u)&&c>0&&u>0;}private static async Task<string>Caption(SqlConnection c,CancellationToken t){await using var q=new SqlCommand("SELECT TOP(1)MenuName FROM dbo.TDADMainMenu WHERE MenuCode=@M",c);Add(q,"@M",SqlDbType.Char,MenuCode,5);return Convert.ToString(await q.ExecuteScalarAsync(t))??"รูปแบบหมุนกะ";}private static string?Clean(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();private static void Add(SqlCommand q,string n,SqlDbType t,object?v,int s=0){var p=s==0?q.Parameters.Add(n,t):q.Parameters.Add(n,t,s);p.Value=v??DBNull.Value;}
}
