import 'package:laoo_shared_core/laoo_shared_core.dart';

abstract final class VisitorProject {
  static const code = 'LAOO_VISITOR';
}

abstract final class VisitorRoutes {
  static const all = <FeatureRouteContract>[
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '31001',
      screenType: 3,
      routeName: 'gateDashboard',
      routePath: '/visitor/gate-dashboard',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '31002',
      screenType: 1,
      routeName: 'visitorCheckIn',
      routePath: '/visitor/check-in',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '31003',
      screenType: 3,
      routeName: 'visitorInside',
      routePath: '/visitor/inside',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '31004',
      screenType: 2,
      routeName: 'gateCheckOut',
      routePath: '/visitor/check-out',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '31005',
      screenType: 3,
      routeName: 'visitorHistory',
      routePath: '/visitor/history',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '32001',
      screenType: 1,
      routeName: 'preRegister',
      routePath: '/visitor/pre-register',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '32002',
      screenType: 3,
      routeName: 'approvalStatus',
      routePath: '/visitor/approval-status',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '32003',
      screenType: 2,
      routeName: 'hostConfirm',
      routePath: '/visitor/host-confirm',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '33001',
      screenType: 1,
      routeName: 'siteZoneGate',
      routePath: '/visitor/site-zone-gate',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '33002',
      screenType: 1,
      routeName: 'residentialMaster',
      routePath: '/visitor/residential',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '33003',
      screenType: 1,
      routeName: 'corporateMaster',
      routePath: '/visitor/corporate',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '33004',
      screenType: 1,
      routeName: 'commonMaster',
      routePath: '/visitor/common-master',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '34001',
      screenType: 3,
      routeName: 'adminDashboard',
      routePath: '/visitor/admin-dashboard',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '34002',
      screenType: 3,
      routeName: 'visitorReports',
      routePath: '/visitor/reports',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '34003',
      screenType: 3,
      routeName: 'visitorExceptions',
      routePath: '/visitor/exceptions',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '34004',
      screenType: 3,
      routeName: 'visitTimeline',
      routePath: '/visitor/timeline',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '35001',
      screenType: 3,
      routeName: 'notifications',
      routePath: '/visitor/notifications',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '35002',
      screenType: 3,
      routeName: 'notificationHistory',
      routePath: '/visitor/notification-history',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '35003',
      screenType: 2,
      routeName: 'notificationChannels',
      routePath: '/visitor/notification-channels',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '36001',
      screenType: 3,
      routeName: 'visitorAudit',
      routePath: '/visitor/audit',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '36002',
      screenType: 1,
      routeName: 'visitorWatchlist',
      routePath: '/visitor/watchlist',
      isImplemented: false,
    ),
    FeatureRouteContract(
      projectCode: VisitorProject.code,
      menuCode: '36003',
      screenType: 2,
      routeName: 'retentionPolicy',
      routePath: '/visitor/retention-policy',
      isImplemented: false,
    ),
  ];

  static Iterable<FeatureRouteContract> get implemented =>
      all.where((route) => route.isImplemented);
}
