using LaooTrainingModule.Assessments;
using System.Text.Json;

var checks=0;
void Check(bool condition,string name) {
    if(!condition) throw new Exception("FAILED: "+name);
    checks++; Console.WriteLine("PASS: "+name);
}
ExamQuestion Question() => new(Guid.NewGuid(),"คำถาม",null,Enumerable.Range(0,4)
    .Select(i=>new ExamOption(Guid.NewGuid(),"ตัวเลือก "+(i+1),null,i==0)).ToList());
var definition=new ExamDefinition(3,60,true,Enumerable.Range(0,8).Select(_=>Question()).ToList());
Check(ExamRules.Validate(definition) is null,"valid four-choice definition");
Check(ExamRules.Validate(definition with { QuestionCount=9 }) is not null,"sample cannot exceed bank");
Check(ExamRules.Validate(definition with { QuestionCount=0 }) is not null,"empty sample rejected");
Check(ExamRules.Validate(definition with { PassingPercent=101 }) is not null,"threshold cannot exceed 100");
Check(ExamRules.Validate(definition with { PassingPercent=-1 }) is not null,"negative threshold rejected");
var invalid=Question();
invalid.Options.RemoveAt(3);
Check(ExamRules.Validate(definition with { Questions=[invalid],QuestionCount=1 }) is not null,"requires exactly four options");
invalid=Question();
invalid.Options[1]=invalid.Options[1] with { IsCorrect=true };
Check(ExamRules.Validate(definition with { Questions=[invalid],QuestionCount=1 }) is not null,"multiple correct choices rejected");
invalid=Question();
invalid.Options[0]=invalid.Options[0] with { IsCorrect=false };
Check(ExamRules.Validate(definition with { Questions=[invalid],QuestionCount=1 }) is not null,"missing correct choice rejected");
invalid=Question() with { Text=null,ImageId=null };
Check(ExamRules.Validate(definition with { Questions=[invalid],QuestionCount=1 }) is not null,"empty prompt rejected");
var image=Question() with { Text=null,ImageId=Guid.NewGuid() };
image.Options[0]=image.Options[0] with { Text=null,ImageId=Guid.NewGuid() };
Check(ExamRules.Validate(definition with { Questions=[image],QuestionCount=1 }) is null,"image-only prompt and option accepted");
Check(ExamRules.Validate(definition with { Questions=[image,image],QuestionCount=1 }) is not null,"duplicate question ID rejected");
var sample=ExamRules.Sample(definition);
Check(sample.Questions.Count==3 && sample.Questions.Select(q=>q.Id).Distinct().Count()==3,"random sample has correct size without duplicates");
Check(sample.Questions.All(q=>q.Options.Count(o=>o.IsCorrect)==1),"shuffle preserves correct answer identity");
Check(sample.Questions.All(q=>definition.Questions.Any(original=>original.Id==q.Id)),"sample uses only configured questions");
var encoded=JsonSerializer.Serialize(sample,ExamRules.Json);
var restored=JsonSerializer.Deserialize<ExamSnapshot>(encoded,ExamRules.Json)!;
Check(JsonSerializer.Serialize(restored,ExamRules.Json)==encoded,"persisted snapshot retains question and option ordering");
var answers=sample.Questions.Select(q=>new ExamAnswer(q.Id,q.Options.Single(o=>o.IsCorrect).Id)).ToList();
Check(ExamRules.Score(sample,answers).Score==3 && ExamRules.Score(sample,answers).Passed,"full score passes");
var wrong=sample.Questions.Select(q=>new ExamAnswer(q.Id,q.Options.First(o=>!o.IsCorrect).Id)).ToList();
Check(ExamRules.Score(sample,wrong).Score==0 && !ExamRules.Score(sample,wrong).Passed,"zero correct fails");
var mixed=answers.ToList(); mixed[0]=wrong[0];
Check(ExamRules.Score(sample with { PassingPercent=66.67m },mixed).Passed==false,"pass threshold uses unrounded percentage");
Check(ExamRules.ValidateAnswers(sample,[answers[0]],false) is null,"draft may be incomplete");
Check(ExamRules.ValidateAnswers(sample,[answers[0]],true) is not null,"submit requires all answers");
Check(ExamRules.ValidateAnswers(sample,[answers[0],answers[0]],false) is not null,"duplicate answers rejected");
Check(ExamRules.ValidateAnswers(sample,[new(Guid.NewGuid(),Guid.NewGuid())],false) is not null,"foreign question rejected");
Check(ExamRules.ValidateAnswers(sample,[new(answers[0].QuestionId,answers[1].OptionId)],false) is not null,"option from other question rejected");
var start=new DateTime(2026,9,19,9,0,0); var end=start.AddHours(3);
Check(ExamRules.IsOpen("PRE",start.AddTicks(-1),start,end),"PRE just before start open");
Check(!ExamRules.IsOpen("PRE",start,start,end),"PRE exactly at start closed");
Check(!ExamRules.IsOpen("POST",end.AddTicks(-1),start,end),"POST before last slot end closed");
Check(ExamRules.IsOpen("POST",end,start,end),"POST exactly at last slot end open");
Check(!ExamRules.IsOpen("POST",end.AddDays(7),start,end),"POST exactly at cutoff closed");
Check(!ExamRules.IsOpen("OTHER",end,start,end),"unknown section closed");
var png=new byte[12]; new byte[]{137,80,78,71,13,10,26,10}.CopyTo(png,0);
Check(ExamRules.ImageType(png)=="image/png","PNG signature detected");
var maxPng=new byte[ExamRules.MaxImageBytes]; png.CopyTo(maxPng,0);
Check(ExamRules.ImageType(maxPng)=="image/png","exact 1 MB accepted");
Check(ExamRules.ImageType(new byte[ExamRules.MaxImageBytes+1]) is null,"over 1 MB rejected");
Check(ExamRules.ImageType("<svg>bad</svg>"u8.ToArray()) is null,"SVG rejected");
Check(ExamRules.ImageType(new byte[12]) is null,"unknown signature rejected");
Console.WriteLine($"Completed {checks} checks.");
