SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE PM
SET PM.IsActive = 1
FROM dbo.TDADProjectMenu PM
JOIN dbo.TDADProject P ON P.ProjectID = PM.ProjectID
WHERE P.ProjectCode = 'LAOO_TIME'
  AND PM.MenuCode IN ('28013','25003','25004');

COMMIT TRANSACTION;
