export 'features/service/service_route_contract.dart';
export 'features/service/service_go_routes.dart';
export 'features/support/presentation/widgets/support_workspace_shell.dart'
    show configureServiceWorkspaceShell;
export 'features/company/customer/pages/customer_page.dart';
export 'features/company/delivery_note/pages/delivery_note_page.dart';
export 'features/company/pre_order/pages/pre_order_page.dart';
export 'features/company/quotation/pages/quotation_page.dart';
export 'features/company/tax_invoice/pages/tax_invoice_page.dart';
export 'features/company/temporary_receipt/pages/temporary_receipt_page.dart';
