SET XACT_ABORT ON;
BEGIN TRY
BEGIN TRANSACTION;
DECLARE @ProjectID bigint=(SELECT ProjectID FROM dbo.TDADProject WHERE ProjectCode=N'LAOO_PROJECT' AND IsActive=1);
DECLARE @CoreProjectID bigint=(SELECT ProjectID FROM dbo.TDADProject WHERE ProjectCode=N'LAOO' AND IsActive=1);
IF @ProjectID IS NULL OR @CoreProjectID IS NULL THROW 56601,N'Active LAOO and LAOO_PROJECT projects are required.',1;
IF OBJECT_ID(N'dbo.TDPMProjectSystemSetting',N'U') IS NULL CREATE TABLE dbo.TDPMProjectSystemSetting(CompanyID bigint NOT NULL PRIMARY KEY,ProjectID bigint NOT NULL,IsEnabled bit NOT NULL CONSTRAINT DF_TDPMSetting_Enabled DEFAULT(1),ProjectNoFormat nvarchar(80) NOT NULL CONSTRAINT DF_TDPMSetting_NoFormat DEFAULT(N'PJ-{yyyy}-{running}'),DueWarningDays int NOT NULL CONSTRAINT DF_TDPMSetting_Warning DEFAULT(7),AllowOverBudget bit NOT NULL CONSTRAINT DF_TDPMSetting_Over DEFAULT(0),RequireBudgetBeforeStart bit NOT NULL CONSTRAINT DF_TDPMSetting_Budget DEFAULT(1),RequireTasksCompleteBeforeClose bit NOT NULL CONSTRAINT DF_TDPMSetting_Task DEFAULT(1),CreateBy bigint NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMSetting_CreateDate DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT CK_TDPMSetting_Warning CHECK(DueWarningDays BETWEEN 0 AND 365));
IF OBJECT_ID(N'dbo.TDPMBudgetCategory',N'U') IS NULL CREATE TABLE dbo.TDPMBudgetCategory(BudgetCategoryID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,CategoryCode nvarchar(40) NOT NULL,CategoryName nvarchar(300) NOT NULL,SortOrder int NOT NULL CONSTRAINT DF_TDPMCategory_Sort DEFAULT(0),Remark nvarchar(1000) NULL,IsActive bit NOT NULL CONSTRAINT DF_TDPMCategory_Active DEFAULT(1),CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMCategory_CreateDate DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT UQ_TDPMCategory UNIQUE(CompanyID,CategoryCode));
IF OBJECT_ID(N'dbo.TDPMProject',N'U') IS NULL CREATE TABLE dbo.TDPMProject(BusinessProjectID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,ProjectNo nvarchar(80) NOT NULL,ProjectName nvarchar(500) NOT NULL,ManagerEmployeeID bigint NOT NULL,DepartmentOrgUnitID bigint NULL,StartDate date NOT NULL,EndDate date NOT NULL,BudgetAmount decimal(18,2) NOT NULL CONSTRAINT DF_TDPMProject_Budget DEFAULT(0),StatusCode nvarchar(30) NOT NULL CONSTRAINT DF_TDPMProject_Status DEFAULT(N'DRAFT'),ProgressPercent decimal(5,2) NOT NULL CONSTRAINT DF_TDPMProject_Progress DEFAULT(0),DescriptionText nvarchar(4000) NULL,Remark nvarchar(2000) NULL,ClosedBy bigint NULL,ClosedDate datetime2 NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMProject_CreateDate DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT UQ_TDPMProject_No UNIQUE(CompanyID,ProjectNo),CONSTRAINT CK_TDPMProject_Dates CHECK(EndDate>=StartDate),CONSTRAINT CK_TDPMProject_Budget CHECK(BudgetAmount>=0),CONSTRAINT CK_TDPMProject_Progress CHECK(ProgressPercent BETWEEN 0 AND 100),CONSTRAINT CK_TDPMProject_Status CHECK(StatusCode IN(N'DRAFT',N'ACTIVE',N'COMPLETED',N'CANCELLED')));
IF OBJECT_ID(N'dbo.TDPMProjectMember',N'U') IS NULL CREATE TABLE dbo.TDPMProjectMember(ProjectMemberID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,BusinessProjectID bigint NOT NULL,EmployeeID bigint NOT NULL,RoleName nvarchar(200) NOT NULL,JoinDate date NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMMember_CreateDate DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDPMMember_Project FOREIGN KEY(BusinessProjectID) REFERENCES dbo.TDPMProject(BusinessProjectID) ON DELETE CASCADE,CONSTRAINT UQ_TDPMMember UNIQUE(CompanyID,BusinessProjectID,EmployeeID));
IF OBJECT_ID(N'dbo.TDPMProjectTask',N'U') IS NULL CREATE TABLE dbo.TDPMProjectTask(ProjectTaskID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,BusinessProjectID bigint NOT NULL,TaskSeq int NOT NULL,TaskName nvarchar(500) NOT NULL,AssigneeEmployeeID bigint NOT NULL,StartDate date NOT NULL,DueDate date NOT NULL,PlannedHours decimal(10,2) NOT NULL CONSTRAINT DF_TDPMTask_Planned DEFAULT(0),ActualHours decimal(10,2) NOT NULL CONSTRAINT DF_TDPMTask_Actual DEFAULT(0),WeightPercent decimal(5,2) NOT NULL CONSTRAINT DF_TDPMTask_Weight DEFAULT(0),ProgressPercent decimal(5,2) NOT NULL CONSTRAINT DF_TDPMTask_Progress DEFAULT(0),StatusCode nvarchar(30) NOT NULL CONSTRAINT DF_TDPMTask_Status DEFAULT(N'NOT_STARTED'),UpdateNote nvarchar(2000) NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMTask_CreateDate DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT FK_TDPMTask_Project FOREIGN KEY(BusinessProjectID) REFERENCES dbo.TDPMProject(BusinessProjectID) ON DELETE CASCADE,CONSTRAINT UQ_TDPMTask_Seq UNIQUE(CompanyID,BusinessProjectID,TaskSeq),CONSTRAINT CK_TDPMTask_Dates CHECK(DueDate>=StartDate),CONSTRAINT CK_TDPMTask_Hours CHECK(PlannedHours>=0 AND ActualHours>=0),CONSTRAINT CK_TDPMTask_Percent CHECK(WeightPercent BETWEEN 0 AND 100 AND ProgressPercent BETWEEN 0 AND 100),CONSTRAINT CK_TDPMTask_Status CHECK(StatusCode IN(N'NOT_STARTED',N'IN_PROGRESS',N'BLOCKED',N'COMPLETED',N'CANCELLED')));
IF OBJECT_ID(N'dbo.TDPMProjectTaskHistory',N'U') IS NULL CREATE TABLE dbo.TDPMProjectTaskHistory(ProjectTaskHistoryID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,ProjectTaskID bigint NOT NULL,OldStatusCode nvarchar(30) NULL,NewStatusCode nvarchar(30) NOT NULL,OldProgressPercent decimal(5,2) NULL,NewProgressPercent decimal(5,2) NOT NULL,ActualHours decimal(10,2) NOT NULL,NoteText nvarchar(2000) NULL,ChangedBy bigint NOT NULL,ChangedDate datetime2 NOT NULL CONSTRAINT DF_TDPMTaskHistory_Date DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDPMTaskHistory_Task FOREIGN KEY(ProjectTaskID) REFERENCES dbo.TDPMProjectTask(ProjectTaskID));
IF OBJECT_ID(N'dbo.TDPMProjectBudget',N'U') IS NULL CREATE TABLE dbo.TDPMProjectBudget(ProjectBudgetID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,CompanyID bigint NOT NULL,BusinessProjectID bigint NOT NULL,BudgetSeq int NOT NULL,BudgetCategoryID bigint NOT NULL,DescriptionText nvarchar(500) NULL,PlannedAmount decimal(18,2) NOT NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDPMBudget_CreateDate DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDPMBudget_Project FOREIGN KEY(BusinessProjectID) REFERENCES dbo.TDPMProject(BusinessProjectID) ON DELETE CASCADE,CONSTRAINT FK_TDPMBudget_Category FOREIGN KEY(BudgetCategoryID) REFERENCES dbo.TDPMBudgetCategory(BudgetCategoryID),CONSTRAINT UQ_TDPMBudget_Seq UNIQUE(CompanyID,BusinessProjectID,BudgetSeq),CONSTRAINT CK_TDPMBudget_Amount CHECK(PlannedAmount>=0));
IF COL_LENGTH(N'dbo.TDEXExpense',N'BusinessProjectID') IS NULL ALTER TABLE dbo.TDEXExpense ADD BusinessProjectID bigint NULL;
IF COL_LENGTH(N'dbo.TDEXExpenseDocument',N'BusinessProjectID') IS NULL ALTER TABLE dbo.TDEXExpenseDocument ADD BusinessProjectID bigint NULL;
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_TDEXExpense_BusinessProject') ALTER TABLE dbo.TDEXExpense ADD CONSTRAINT FK_TDEXExpense_BusinessProject FOREIGN KEY(BusinessProjectID) REFERENCES dbo.TDPMProject(BusinessProjectID);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_TDEXExpenseDocument_BusinessProject') ALTER TABLE dbo.TDEXExpenseDocument ADD CONSTRAINT FK_TDEXExpenseDocument_BusinessProject FOREIGN KEY(BusinessProjectID) REFERENCES dbo.TDPMProject(BusinessProjectID);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDPMProject') AND name=N'IX_TDPMProject_CompanyStatusDates') CREATE INDEX IX_TDPMProject_CompanyStatusDates ON dbo.TDPMProject(CompanyID,StatusCode,StartDate,EndDate);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDPMProjectTask') AND name=N'IX_TDPMTask_AssigneeStatus') CREATE INDEX IX_TDPMTask_AssigneeStatus ON dbo.TDPMProjectTask(CompanyID,AssigneeEmployeeID,StatusCode,DueDate);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDEXExpense') AND name=N'IX_TDEXExpense_BusinessProject') CREATE INDEX IX_TDEXExpense_BusinessProject ON dbo.TDEXExpense(CompanyID,BusinessProjectID,StatusCode);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDEXExpenseDocument') AND name=N'IX_TDEXExpenseDocument_BusinessProject') CREATE INDEX IX_TDEXExpenseDocument_BusinessProject ON dbo.TDEXExpenseDocument(CompanyID,BusinessProjectID,StatusCode);
UPDATE dbo.TDADProjectMenu SET IsActive=1,UpdateDate=SYSUTCDATETIME() WHERE ProjectID=@ProjectID AND MenuCode BETWEEN N'42001' AND N'42005';
UPDATE dbo.TDADProjectMenuGroup SET IsActive=1,UpdateDate=SYSUTCDATETIME() WHERE ProjectID=@ProjectID AND MenuGroupCode=N'42';
;WITH CompanyAdminRoles AS(SELECT DISTINCT RG.RoleGroupID FROM dbo.TDADRoleGroup RG WHERE RG.ProjectID=@CoreProjectID AND RG.ScopeType=N'C' AND RG.CompanyID IS NOT NULL AND RG.IsActive=1 AND (RG.RoleCode=N'ADMIN' OR RG.RoleNameTH LIKE N'%Admin%' OR RG.RoleNameTH LIKE N'%ผู้ดูแล%'))
INSERT dbo.TDADRoleGroupPermission(RoleGroupID,ProjectID,MenuCode,ActionCode,IsAllowed,CreatedBy) SELECT R.RoleGroupID,@ProjectID,P.ScreenCode,P.ActionCode,1,0 FROM CompanyAdminRoles R CROSS JOIN dbo.TDADPermission P WHERE P.ProjectID=@ProjectID AND P.ScreenCode BETWEEN N'42001' AND N'42005' AND P.IsActive=1 AND NOT EXISTS(SELECT 1 FROM dbo.TDADRoleGroupPermission X WHERE X.RoleGroupID=R.RoleGroupID AND X.ProjectID=@ProjectID AND X.MenuCode=P.ScreenCode AND X.ActionCode=P.ActionCode);
UPDATE dbo.TDADRoleGroupPermission SET IsAllowed=1,UpdatedUtc=SYSUTCDATETIME(),UpdatedBy=0 WHERE ProjectID=@ProjectID AND MenuCode BETWEEN N'42001' AND N'42005';
COMMIT;
END TRY
BEGIN CATCH
 IF @@TRANCOUNT>0 ROLLBACK;
 THROW;
END CATCH;
