SET XACT_ABORT ON;
BEGIN TRY
 BEGIN TRANSACTION;
 IF OBJECT_ID(N'dbo.TDKNSystemSetting',N'U') IS NULL CREATE TABLE dbo.TDKNSystemSetting(
  CompanyID bigint NOT NULL PRIMARY KEY,MaxVideoMB int NOT NULL CONSTRAINT DF_TDKNSetting_Video DEFAULT(100),MaxAttachmentMB int NOT NULL CONSTRAINT DF_TDKNSetting_File DEFAULT(20),DefaultReviewMonths int NOT NULL CONSTRAINT DF_TDKNSetting_Review DEFAULT(12),
  AllowedVideoExtensions nvarchar(200) NOT NULL CONSTRAINT DF_TDKNSetting_VideoExt DEFAULT(N'mp4'),AllowedAttachmentExtensions nvarchar(500) NOT NULL CONSTRAINT DF_TDKNSetting_FileExt DEFAULT(N'pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png'),
  CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNSetting_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,
  CONSTRAINT CK_TDKNSetting CHECK(MaxVideoMB BETWEEN 1 AND 2048 AND MaxAttachmentMB BETWEEN 1 AND 200 AND DefaultReviewMonths BETWEEN 1 AND 60));
 IF OBJECT_ID(N'dbo.TDKNCategory',N'U') IS NULL CREATE TABLE dbo.TDKNCategory(
  CategoryID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ParentCategoryID bigint NULL,CategoryCode nvarchar(40) NOT NULL,CategoryName nvarchar(200) NOT NULL,OwnerUserID bigint NULL,SortOrder int NOT NULL CONSTRAINT DF_TDKNCategory_Sort DEFAULT(0),IsActive bit NOT NULL CONSTRAINT DF_TDKNCategory_Active DEFAULT(1),
  CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNCategory_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,
  CONSTRAINT FK_TDKNCategory_Parent FOREIGN KEY(ParentCategoryID) REFERENCES dbo.TDKNCategory(CategoryID),CONSTRAINT UQ_TDKNCategory UNIQUE(CompanyID,CategoryCode));
 IF OBJECT_ID(N'dbo.TDKNCategoryExpert',N'U') IS NULL CREATE TABLE dbo.TDKNCategoryExpert(
  CompanyID bigint NOT NULL,CategoryID bigint NOT NULL,UserID bigint NOT NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNExpert_Create DEFAULT(SYSUTCDATETIME()),
  CONSTRAINT PK_TDKNCategoryExpert PRIMARY KEY(CompanyID,CategoryID,UserID),CONSTRAINT FK_TDKNExpert_Category FOREIGN KEY(CategoryID) REFERENCES dbo.TDKNCategory(CategoryID) ON DELETE CASCADE);
 IF OBJECT_ID(N'dbo.TDKNArticle',N'U') IS NULL CREATE TABLE dbo.TDKNArticle(
  ArticleID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ArticleCode nvarchar(80) NOT NULL,CategoryID bigint NOT NULL,Title nvarchar(500) NOT NULL,SummaryText nvarchar(2000) NULL,ContentType nvarchar(30) NOT NULL,SourceSystem nvarchar(30) NULL,SourceType nvarchar(50) NULL,SourceID nvarchar(100) NULL,SourceRevision nvarchar(50) NULL,SourceUrl nvarchar(2000) NULL,
  OwnerUserID bigint NOT NULL,StatusCode nvarchar(30) NOT NULL,AudienceMode nvarchar(20) NOT NULL CONSTRAINT DF_TDKNArticle_Audience DEFAULT(N'ALL'),CurrentRevisionID bigint NULL,PublishedAt datetime2 NULL,NextReviewDate date NULL,IsActive bit NOT NULL CONSTRAINT DF_TDKNArticle_Active DEFAULT(1),
  CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNArticle_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,
  CONSTRAINT FK_TDKNArticle_Category FOREIGN KEY(CategoryID) REFERENCES dbo.TDKNCategory(CategoryID),CONSTRAINT UQ_TDKNArticle_Code UNIQUE(CompanyID,ArticleCode),
  CONSTRAINT CK_TDKNArticle_Content CHECK(ContentType IN(N'ARTICLE',N'VIDEO_FILE',N'VIDEO_URL',N'DOCUMENT_CONTROL',N'TRAINING',N'INTRANET',N'EXTERNAL_URL')),
  CONSTRAINT CK_TDKNArticle_Status CHECK(StatusCode IN(N'DRAFT',N'IN_REVIEW',N'RETURNED',N'PUBLISHED',N'REVIEW_DUE',N'ARCHIVED')),CONSTRAINT CK_TDKNArticle_Audience CHECK(AudienceMode IN(N'ALL',N'RESTRICTED')));
 IF OBJECT_ID(N'dbo.TDKNArticleRevision',N'U') IS NULL CREATE TABLE dbo.TDKNArticleRevision(
  RevisionID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,RevisionNo int NOT NULL,BodyText nvarchar(max) NULL,StatusCode nvarchar(30) NOT NULL,ReviewerUserID bigint NULL,SubmittedAt datetime2 NULL,ReviewedBy bigint NULL,ReviewedAt datetime2 NULL,ReturnReason nvarchar(2000) NULL,
  CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNRevision_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,
  CONSTRAINT FK_TDKNRevision_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID),CONSTRAINT UQ_TDKNRevision UNIQUE(CompanyID,ArticleID,RevisionNo),CONSTRAINT CK_TDKNRevision_Status CHECK(StatusCode IN(N'DRAFT',N'IN_REVIEW',N'RETURNED',N'PUBLISHED',N'ARCHIVED')));
 IF OBJECT_ID(N'dbo.TDKNArticleAudience',N'U') IS NULL CREATE TABLE dbo.TDKNArticleAudience(
  AudienceID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,SubjectType nvarchar(20) NOT NULL,SubjectID bigint NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNAudience_Create DEFAULT(SYSUTCDATETIME()),
  CONSTRAINT FK_TDKNAudience_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID) ON DELETE CASCADE,CONSTRAINT CK_TDKNAudience_Type CHECK(SubjectType IN(N'DEPARTMENT',N'USER')));
 IF OBJECT_ID(N'dbo.TDKNTag',N'U') IS NULL CREATE TABLE dbo.TDKNTag(TagID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,TagName nvarchar(100) NOT NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNTag_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT UQ_TDKNTag UNIQUE(CompanyID,TagName));
 IF OBJECT_ID(N'dbo.TDKNArticleTag',N'U') IS NULL CREATE TABLE dbo.TDKNArticleTag(CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,TagID bigint NOT NULL,CONSTRAINT PK_TDKNArticleTag PRIMARY KEY(CompanyID,ArticleID,TagID),CONSTRAINT FK_TDKNArticleTag_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID) ON DELETE CASCADE,CONSTRAINT FK_TDKNArticleTag_Tag FOREIGN KEY(TagID) REFERENCES dbo.TDKNTag(TagID));
 IF OBJECT_ID(N'dbo.TDKNFile',N'U') IS NULL CREATE TABLE dbo.TDKNFile(
  FileID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,RevisionID bigint NULL,FileKind nvarchar(20) NOT NULL,OriginalFileName nvarchar(260) NOT NULL,StoredFileName nvarchar(260) NOT NULL,RelativePath nvarchar(1000) NOT NULL,ContentType nvarchar(150) NOT NULL,FileSizeBytes bigint NOT NULL,Sha256 nvarchar(64) NOT NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNFile_Create DEFAULT(SYSUTCDATETIME()),
  CONSTRAINT FK_TDKNFile_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID),CONSTRAINT FK_TDKNFile_Revision FOREIGN KEY(RevisionID) REFERENCES dbo.TDKNArticleRevision(RevisionID),CONSTRAINT CK_TDKNFile_Kind CHECK(FileKind IN(N'COVER',N'VIDEO',N'ATTACHMENT')),CONSTRAINT CK_TDKNFile_Size CHECK(FileSizeBytes>0));
 IF OBJECT_ID(N'dbo.TDKNFeedback',N'U') IS NULL CREATE TABLE dbo.TDKNFeedback(FeedbackID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,RevisionID bigint NULL,UserID bigint NOT NULL,IsHelpful bit NOT NULL,CommentText nvarchar(2000) NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNFeedback_Create DEFAULT(SYSUTCDATETIME()),UpdateDate datetime2 NULL,CONSTRAINT FK_TDKNFeedback_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID),CONSTRAINT UQ_TDKNFeedback UNIQUE(CompanyID,ArticleID,UserID));
 IF OBJECT_ID(N'dbo.TDKNFollow',N'U') IS NULL CREATE TABLE dbo.TDKNFollow(CompanyID bigint NOT NULL,ArticleID bigint NOT NULL,UserID bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNFollow_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT PK_TDKNFollow PRIMARY KEY(CompanyID,ArticleID,UserID),CONSTRAINT FK_TDKNFollow_Article FOREIGN KEY(ArticleID) REFERENCES dbo.TDKNArticle(ArticleID) ON DELETE CASCADE);
 IF OBJECT_ID(N'dbo.TDKNQuestion',N'U') IS NULL CREATE TABLE dbo.TDKNQuestion(QuestionID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,CategoryID bigint NOT NULL,QuestionTitle nvarchar(500) NOT NULL,QuestionText nvarchar(max) NOT NULL,AskedBy bigint NOT NULL,StatusCode nvarchar(20) NOT NULL,AudienceMode nvarchar(20) NOT NULL CONSTRAINT DF_TDKNQuestion_Audience DEFAULT(N'ALL'),ConvertedArticleID bigint NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNQuestion_Create DEFAULT(SYSUTCDATETIME()),UpdateDate datetime2 NULL,CONSTRAINT FK_TDKNQuestion_Category FOREIGN KEY(CategoryID) REFERENCES dbo.TDKNCategory(CategoryID),CONSTRAINT CK_TDKNQuestion_Status CHECK(StatusCode IN(N'OPEN',N'ANSWERED',N'RESOLVED')),CONSTRAINT CK_TDKNQuestion_Audience CHECK(AudienceMode IN(N'ALL',N'RESTRICTED')));
 IF OBJECT_ID(N'dbo.TDKNAnswer',N'U') IS NULL CREATE TABLE dbo.TDKNAnswer(AnswerID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,QuestionID bigint NOT NULL,AnswerText nvarchar(max) NOT NULL,AnsweredBy bigint NOT NULL,IsAccepted bit NOT NULL CONSTRAINT DF_TDKNAnswer_Accepted DEFAULT(0),CreateDate datetime2 NOT NULL CONSTRAINT DF_TDKNAnswer_Create DEFAULT(SYSUTCDATETIME()),UpdateDate datetime2 NULL,CONSTRAINT FK_TDKNAnswer_Question FOREIGN KEY(QuestionID) REFERENCES dbo.TDKNQuestion(QuestionID) ON DELETE CASCADE);
 IF OBJECT_ID(N'dbo.TDKNAudit',N'U') IS NULL CREATE TABLE dbo.TDKNAudit(AuditID bigint IDENTITY(1,1) PRIMARY KEY,CompanyID bigint NOT NULL,EntityType nvarchar(30) NOT NULL,EntityID bigint NULL,ActionCode nvarchar(50) NOT NULL,DetailText nvarchar(2000) NULL,UserID bigint NOT NULL,IpAddress nvarchar(80) NULL,ActionDate datetime2 NOT NULL CONSTRAINT DF_TDKNAudit_Date DEFAULT(SYSUTCDATETIME()));
 IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDKNArticle') AND name=N'IX_TDKNArticle_Search') CREATE INDEX IX_TDKNArticle_Search ON dbo.TDKNArticle(CompanyID,StatusCode,CategoryID,CreateDate DESC);
 IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDKNQuestion') AND name=N'IX_TDKNQuestion_Status') CREATE INDEX IX_TDKNQuestion_Status ON dbo.TDKNQuestion(CompanyID,StatusCode,CreateDate DESC);
 COMMIT;
END TRY
BEGIN CATCH
 IF @@TRANCOUNT>0 ROLLBACK;
 THROW;
END CATCH;
GO
