using System.Data;
using System.Security.Claims;
using Laoo.Shared.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace LaooProjectModule.Controllers;

[ApiController,Authorize,Route("api/company/project-management")]
public sealed class ProjectManagementController(IConfiguration cfg):ControllerBase
{
 static readonly string[] Menus=["42001","42002","42003","42004","42005"];
 [HttpGet("actions/{menu}")] public async Task<IActionResult> Actions(string menu,CancellationToken t){if(!Menus.Contains(menu)||!Scope(out _,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,menu,"VIEW",t))return Forbid();return Ok(new{create=await Can(db,menu,"CREATE",t),edit=await Can(db,menu,"EDIT",t),delete=await Can(db,menu,"DELETE",t),close=await Can(db,menu,"CLOSE",t)});}
 [HttpGet("settings")] public async Task<IActionResult> Settings(CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42001","VIEW",t))return Forbid();await Ensure(db,c,t);return Ok((await Q(db,"SELECT IsEnabled,ProjectNoFormat,DueWarningDays,AllowOverBudget,RequireBudgetBeforeStart,RequireTasksCompleteBeforeClose FROM dbo.TDPMProjectSystemSetting WHERE CompanyID=@c",t,("@c",c))).First());}
 [HttpPut("settings")] public async Task<IActionResult> Settings(SettingInput x,CancellationToken t){if(x.DueWarningDays is <0 or >365||string.IsNullOrWhiteSpace(x.ProjectNoFormat))return Bad("ข้อมูลตั้งค่าไม่ถูกต้อง","รูปแบบเลขที่ต้องไม่ว่างและวันเตือนต้องอยู่ระหว่าง 0-365");if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42001","EDIT",t))return Forbid();await Ensure(db,c,t);await X(db,"UPDATE dbo.TDPMProjectSystemSetting SET IsEnabled=@e,ProjectNoFormat=@f,DueWarningDays=@d,AllowOverBudget=@o,RequireBudgetBeforeStart=@b,RequireTasksCompleteBeforeClose=@r,UpdateBy=@u,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c",t,("@e",x.IsEnabled),("@f",x.ProjectNoFormat.Trim()),("@d",x.DueWarningDays),("@o",x.AllowOverBudget),("@b",x.RequireBudgetBeforeStart),("@r",x.RequireTasksCompleteBeforeClose),("@u",u),("@c",c));return NoContent();}
 [HttpGet("budget-categories")] public async Task<IActionResult> Categories(CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42002","VIEW",t))return Forbid();return Ok(await Q(db,"SELECT BudgetCategoryID id,CategoryCode code,CategoryName name,SortOrder,Remark,IsActive active FROM dbo.TDPMBudgetCategory WHERE CompanyID=@c ORDER BY SortOrder,CategoryName",t,("@c",c)));}
 [HttpPost("budget-categories")] public Task<IActionResult> Category(CategoryInput x,CancellationToken t)=>SaveCategory(null,x,"CREATE",t);
 [HttpPut("budget-categories/{id:long}")] public Task<IActionResult> Category(long id,CategoryInput x,CancellationToken t)=>SaveCategory(id,x,"EDIT",t);
 async Task<IActionResult> SaveCategory(long? id,CategoryInput x,string action,CancellationToken t){var code=Clean(x.Code)?.ToUpperInvariant();var name=Clean(x.Name);if(code is null||name is null||code.Length>40)return Bad("ข้อมูลหมวดงบประมาณไม่ครบ","ระบุรหัสไม่เกิน 40 ตัวและชื่อหมวด");if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42002",action,t))return Forbid();try{var n=id is null?await X(db,"INSERT dbo.TDPMBudgetCategory(CompanyID,CategoryCode,CategoryName,SortOrder,Remark,IsActive,CreateBy) VALUES(@c,@code,@name,@sort,@remark,@active,@u)",t,("@c",c),("@code",code),("@name",name),("@sort",x.SortOrder),("@remark",Clean(x.Remark)),("@active",x.IsActive),("@u",u)):await X(db,"UPDATE dbo.TDPMBudgetCategory SET CategoryCode=@code,CategoryName=@name,SortOrder=@sort,Remark=@remark,IsActive=@active,UpdateBy=@u,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND BudgetCategoryID=@id",t,("@c",c),("@id",id),("@code",code),("@name",name),("@sort",x.SortOrder),("@remark",Clean(x.Remark)),("@active",x.IsActive),("@u",u));return n==1?Ok(new{id,code}):NotFound();}catch(SqlException e)when(e.Number is 2601 or 2627){return Conflict(new{message="รหัสหมวดงบประมาณซ้ำ",description="ใช้รหัสอื่นภายในบริษัทเดียวกัน"});}}
 [HttpDelete("budget-categories/{id:long}")] public async Task<IActionResult> DeleteCategory(long id,CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42002","DELETE",t))return Forbid();if(await S<int>(db,"SELECT COUNT(*) FROM dbo.TDPMProjectBudget WHERE CompanyID=@c AND BudgetCategoryID=@id",t,("@c",c),("@id",id))>0)return Conflict(new{message="ลบหมวดงบประมาณไม่ได้",description="หมวดนี้ถูกใช้ในโครงการแล้ว"});return await X(db,"DELETE dbo.TDPMBudgetCategory WHERE CompanyID=@c AND BudgetCategoryID=@id",t,("@c",c),("@id",id))==1?NoContent():NotFound();}
 [HttpGet("options")] public async Task<IActionResult> Options(CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003","VIEW",t)&&!await Can(db,"42004","VIEW",t)&&!await Can(db,"42005","VIEW",t))return Forbid();var employees=await Q(db,"SELECT EmployeeID id,EmployeeCode code,FullName name FROM dbo.TDADEmployee WHERE CompanyID=@c AND IsActive=1 ORDER BY FullName",t,("@c",c));var departments=await Q(db,"SELECT OrgUnitID id,UnitCode code,NameTH name FROM dbo.TDADOrganizationUnit WHERE CompanyID=@c AND UnitType=N'DEPARTMENT' AND IsActive=1 ORDER BY NameTH",t,("@c",c));var categories=await Q(db,"SELECT BudgetCategoryID id,CategoryCode code,CategoryName name FROM dbo.TDPMBudgetCategory WHERE CompanyID=@c AND IsActive=1 ORDER BY SortOrder,CategoryName",t,("@c",c));var projects=await Q(db,"SELECT BusinessProjectID id,ProjectNo code,ProjectName name FROM dbo.TDPMProject WHERE CompanyID=@c AND StatusCode<>N'CANCELLED' ORDER BY ProjectName",t,("@c",c));return Ok(new{employees,departments,categories,projects});}
 [HttpGet("projects")] public async Task<IActionResult> Projects(string? search,string? status,long? managerId,int page=1,int pageSize=10,CancellationToken t=default){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003","VIEW",t))return Forbid();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);const string f=@" FROM dbo.TDPMProject p JOIN dbo.TDADEmployee e ON e.CompanyID=p.CompanyID AND e.EmployeeID=p.ManagerEmployeeID LEFT JOIN dbo.TDADOrganizationUnit o ON o.CompanyID=p.CompanyID AND o.OrgUnitID=p.DepartmentOrgUnitID OUTER APPLY(SELECT SUM(v.Amount) actual FROM(SELECT TotalAmount Amount FROM dbo.TDEXExpense WHERE CompanyID=p.CompanyID AND BusinessProjectID=p.BusinessProjectID AND StatusCode=N'RECORDED' UNION ALL SELECT TotalAmount FROM dbo.TDEXExpenseDocument WHERE CompanyID=p.CompanyID AND BusinessProjectID=p.BusinessProjectID AND StatusCode IN(N'APPROVED',N'PAID',N'SETTLED'))v)a WHERE p.CompanyID=@c AND (@q IS NULL OR p.ProjectNo LIKE N'%'+@q+N'%' OR p.ProjectName LIKE N'%'+@q+N'%') AND (@s IS NULL OR p.StatusCode=@s) AND (@m IS NULL OR p.ManagerEmployeeID=@m)";var a=new(string,object?)[]{("@c",c),("@q",Clean(search)),("@s",Clean(status)),("@m",managerId)};var total=await S<int>(db,"SELECT COUNT(*)"+f,t,a);var items=await Q(db,"SELECT p.BusinessProjectID id,p.ProjectNo code,p.ProjectName name,e.FullName manager,o.NameTH department,p.StartDate,p.EndDate,p.BudgetAmount budget,ISNULL(a.actual,0) actual,p.ProgressPercent progress,p.StatusCode status"+f+" ORDER BY p.StartDate DESC,p.BusinessProjectID DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",t,[..a,("@skip",(page-1)*pageSize),("@take",pageSize)]);return Ok(new{items,total,page,pageSize});}
 [HttpGet("projects/{id:long}")] public async Task<IActionResult> Project(long id,CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003","VIEW",t))return Forbid();var h=await Q(db,"SELECT BusinessProjectID id,ProjectNo code,ProjectName name,ManagerEmployeeID managerId,DepartmentOrgUnitID departmentId,StartDate,EndDate,BudgetAmount budget,StatusCode status,ProgressPercent progress,DescriptionText description,Remark FROM dbo.TDPMProject WHERE CompanyID=@c AND BusinessProjectID=@id",t,("@c",c),("@id",id));if(h.Count==0)return NotFound();var members=await Q(db,"SELECT m.EmployeeID employeeId,e.FullName employee,m.RoleName role,m.JoinDate FROM dbo.TDPMProjectMember m JOIN dbo.TDADEmployee e ON e.CompanyID=m.CompanyID AND e.EmployeeID=m.EmployeeID WHERE m.CompanyID=@c AND m.BusinessProjectID=@id ORDER BY e.FullName",t,("@c",c),("@id",id));var tasks=await Q(db,"SELECT t.ProjectTaskID AS [id],t.TaskSeq AS [lineNo],t.TaskName AS [name],t.AssigneeEmployeeID AS [assigneeId],e.FullName AS [assignee],t.StartDate,t.DueDate,t.PlannedHours,t.ActualHours,t.WeightPercent AS [weight],t.ProgressPercent AS [progress],t.StatusCode AS [status],t.UpdateNote AS [note] FROM dbo.TDPMProjectTask t JOIN dbo.TDADEmployee e ON e.CompanyID=t.CompanyID AND e.EmployeeID=t.AssigneeEmployeeID WHERE t.CompanyID=@c AND t.BusinessProjectID=@id ORDER BY t.TaskSeq",t,("@c",c),("@id",id));var budgets=await Q(db,"SELECT b.BudgetCategoryID categoryId,c.CategoryName category,b.DescriptionText description,b.PlannedAmount amount FROM dbo.TDPMProjectBudget b JOIN dbo.TDPMBudgetCategory c ON c.CompanyID=b.CompanyID AND c.BudgetCategoryID=b.BudgetCategoryID WHERE b.CompanyID=@c AND b.BusinessProjectID=@id ORDER BY b.BudgetSeq",t,("@c",c),("@id",id));return Ok(new{header=h[0],members,tasks,budgets});}
 [HttpPost("projects")] public Task<IActionResult> Project(ProjectInput x,CancellationToken t)=>SaveProject(null,x,"CREATE",t);
 [HttpPut("projects/{id:long}")] public Task<IActionResult> Project(long id,ProjectInput x,CancellationToken t)=>SaveProject(id,x,"EDIT",t);
 async Task<IActionResult> SaveProject(long? id,ProjectInput x,string action,CancellationToken t){var name=Clean(x.Name);if(name is null||x.ManagerId<=0||x.EndDate.Date<x.StartDate.Date||x.Budget<0)return Bad("ข้อมูลโครงการไม่ถูกต้อง","ระบุชื่อ ผู้จัดการ ช่วงวันที่ และงบประมาณให้ถูกต้อง");if(x.Tasks.Any(v=>string.IsNullOrWhiteSpace(v.Name)||v.AssigneeId<=0||v.DueDate<v.StartDate||v.PlannedHours<0||v.Weight is <0 or >100)||x.Budgets.Any(v=>v.CategoryId<=0||v.Amount<0))return Bad("รายละเอียดโครงการไม่ถูกต้อง","ตรวจงานและแผนงบประมาณ");if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003",action,t))return Forbid();await Ensure(db,c,t);var set=(await Q(db,"SELECT AllowOverBudget,RequireBudgetBeforeStart FROM dbo.TDPMProjectSystemSetting WHERE CompanyID=@c",t,("@c",c))).First();var plan=x.Budgets.Sum(v=>v.Amount);if(x.Status=="ACTIVE"&&Convert.ToBoolean(set["requireBudgetBeforeStart"])&&plan<=0)return Conflict(new{message="เริ่มโครงการไม่ได้",description="ต้องระบุแผนงบประมาณ"});if(!Convert.ToBoolean(set["allowOverBudget"])&&plan>x.Budget)return Conflict(new{message="แผนงบประมาณเกินวงเงิน",description="ลดแผนงบประมาณหรือแก้การตั้งค่า"});await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);try{long pid;if(id is null){await using var q=new SqlCommand("INSERT dbo.TDPMProject(CompanyID,ProjectNo,ProjectName,ManagerEmployeeID,DepartmentOrgUnitID,StartDate,EndDate,BudgetAmount,StatusCode,DescriptionText,Remark,CreateBy) OUTPUT INSERTED.BusinessProjectID VALUES(@c,CONVERT(nvarchar(36),NEWID()),@name,@manager,@department,@start,@end,@budget,@status,@description,@remark,@u)",db,tx);Header(q,c,null,x,name,u);pid=Convert.ToInt64(await q.ExecuteScalarAsync(t));var no=string.IsNullOrWhiteSpace(x.Code)?$"PJ-{DateTime.UtcNow:yyyy}-{pid:00000}":x.Code.Trim().ToUpperInvariant();await X(db,tx,"UPDATE dbo.TDPMProject SET ProjectNo=@no WHERE CompanyID=@c AND BusinessProjectID=@id",t,("@no",no),("@c",c),("@id",pid));}else{await using var q=new SqlCommand("UPDATE dbo.TDPMProject SET ProjectName=@name,ManagerEmployeeID=@manager,DepartmentOrgUnitID=@department,StartDate=@start,EndDate=@end,BudgetAmount=@budget,StatusCode=@status,DescriptionText=@description,Remark=@remark,UpdateBy=@u,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND BusinessProjectID=@id AND StatusCode=N'DRAFT'",db,tx);Header(q,c,id,x,name,u);if(await q.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return Conflict(new{message="แก้ไขโครงการไม่ได้",description="แก้โครงสร้างได้เฉพาะสถานะร่าง"});}pid=id.Value;foreach(var table in new[]{"TDPMProjectMember","TDPMProjectTask","TDPMProjectBudget"})await X(db,tx,$"DELETE dbo.{table} WHERE CompanyID=@c AND BusinessProjectID=@id",t,("@c",c),("@id",pid));}
 foreach(var v in x.Members)await X(db,tx,"INSERT dbo.TDPMProjectMember(CompanyID,BusinessProjectID,EmployeeID,RoleName,JoinDate,CreateBy) SELECT @c,@p,EmployeeID,@role,@join,@u FROM dbo.TDADEmployee WHERE CompanyID=@c AND EmployeeID=@e AND IsActive=1",t,("@c",c),("@p",pid),("@e",v.EmployeeId),("@role",Clean(v.Role)??"สมาชิก"),("@join",v.JoinDate?.Date),("@u",u));
 for(var i=0;i<x.Tasks.Count;i++){var v=x.Tasks[i];await X(db,tx,"INSERT dbo.TDPMProjectTask(CompanyID,BusinessProjectID,TaskSeq,TaskName,AssigneeEmployeeID,StartDate,DueDate,PlannedHours,WeightPercent,CreateBy) SELECT @c,@p,@seq,@name,EmployeeID,@start,@due,@hours,@weight,@u FROM dbo.TDADEmployee WHERE CompanyID=@c AND EmployeeID=@e AND IsActive=1",t,("@c",c),("@p",pid),("@seq",i+1),("@name",v.Name.Trim()),("@e",v.AssigneeId),("@start",v.StartDate.Date),("@due",v.DueDate.Date),("@hours",v.PlannedHours),("@weight",v.Weight),("@u",u));}
 for(var i=0;i<x.Budgets.Count;i++){var v=x.Budgets[i];await X(db,tx,"INSERT dbo.TDPMProjectBudget(CompanyID,BusinessProjectID,BudgetSeq,BudgetCategoryID,DescriptionText,PlannedAmount,CreateBy) SELECT @c,@p,@seq,BudgetCategoryID,@description,@amount,@u FROM dbo.TDPMBudgetCategory WHERE CompanyID=@c AND BudgetCategoryID=@category AND IsActive=1",t,("@c",c),("@p",pid),("@seq",i+1),("@category",v.CategoryId),("@description",Clean(v.Description)),("@amount",v.Amount),("@u",u));}await tx.CommitAsync(t);return Ok(new{id=pid});}catch(SqlException e)when(e.Number is 2601 or 2627){await tx.RollbackAsync(t);return Conflict(new{message="ข้อมูลโครงการซ้ำ",description="ตรวจเลขที่ สมาชิก หรือรายละเอียดซ้ำ"});}catch{await tx.RollbackAsync(t);throw;}}
 [HttpDelete("projects/{id:long}")] public async Task<IActionResult> DeleteProject(long id,CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003","DELETE",t))return Forbid();var refs=await S<int>(db,"SELECT (SELECT COUNT(*) FROM dbo.TDPMProjectTaskHistory h JOIN dbo.TDPMProjectTask x ON x.ProjectTaskID=h.ProjectTaskID WHERE x.CompanyID=@c AND x.BusinessProjectID=@id)+(SELECT COUNT(*) FROM dbo.TDEXExpense WHERE CompanyID=@c AND BusinessProjectID=@id)+(SELECT COUNT(*) FROM dbo.TDEXExpenseDocument WHERE CompanyID=@c AND BusinessProjectID=@id)",t,("@c",c),("@id",id));if(refs>0)return Conflict(new{message="ลบโครงการไม่ได้",description="มีประวัติหรือค่าใช้จ่ายอ้างอิงแล้ว"});return await X(db,"DELETE dbo.TDPMProject WHERE CompanyID=@c AND BusinessProjectID=@id AND StatusCode=N'DRAFT'",t,("@c",c),("@id",id))==1?NoContent():Conflict(new{message="ลบโครงการไม่ได้",description="ลบได้เฉพาะสถานะร่าง"});}
 [HttpPost("projects/{id:long}/close")] public async Task<IActionResult> Close(long id,CancellationToken t){if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42003","CLOSE",t))return Forbid();await Ensure(db,c,t);if(await S<bool>(db,"SELECT RequireTasksCompleteBeforeClose FROM dbo.TDPMProjectSystemSetting WHERE CompanyID=@c",t,("@c",c))&&await S<int>(db,"SELECT COUNT(*) FROM dbo.TDPMProjectTask WHERE CompanyID=@c AND BusinessProjectID=@id AND StatusCode NOT IN(N'COMPLETED',N'CANCELLED')",t,("@c",c),("@id",id))>0)return Conflict(new{message="ปิดโครงการไม่ได้",description="ยังมีงานที่ไม่เสร็จ"});return await X(db,"UPDATE dbo.TDPMProject SET StatusCode=N'COMPLETED',ProgressPercent=100,ClosedBy=@u,ClosedDate=SYSUTCDATETIME(),UpdateBy=@u,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND BusinessProjectID=@id AND StatusCode=N'ACTIVE'",t,("@c",c),("@id",id),("@u",u))==1?NoContent():Conflict(new{message="ปิดโครงการไม่ได้",description="ปิดได้เฉพาะโครงการที่กำลังดำเนินการ"});}
 [HttpGet("my-tasks")] public async Task<IActionResult> MyTasks(string? search,string? status,long? projectId,CancellationToken t){if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42004","VIEW",t))return Forbid();return Ok(await Q(db,@"SELECT x.ProjectTaskID id,p.ProjectNo projectCode,p.ProjectName projectName,x.TaskName name,x.StartDate,x.DueDate,x.PlannedHours,x.ActualHours,x.ProgressPercent progress,x.StatusCode status,x.UpdateNote note FROM dbo.TDPMProjectTask x JOIN dbo.TDPMProject p ON p.CompanyID=x.CompanyID AND p.BusinessProjectID=x.BusinessProjectID JOIN dbo.TDADUserEmployee ue ON ue.CompanyID=x.CompanyID AND ue.EmployeeID=x.AssigneeEmployeeID AND ue.UserID=@u AND ue.IsActive=1 WHERE x.CompanyID=@c AND (@q IS NULL OR x.TaskName LIKE N'%'+@q+N'%' OR p.ProjectName LIKE N'%'+@q+N'%') AND (@s IS NULL OR x.StatusCode=@s) AND (@p IS NULL OR p.BusinessProjectID=@p) ORDER BY x.DueDate",t,("@c",c),("@u",u),("@q",Clean(search)),("@s",Clean(status)),("@p",projectId)));}
 [HttpPut("my-tasks/{id:long}")] public async Task<IActionResult> Task(long id,TaskInput x,CancellationToken t){var s=Clean(x.Status)?.ToUpperInvariant();if(!new[]{"NOT_STARTED","IN_PROGRESS","BLOCKED","COMPLETED","CANCELLED"}.Contains(s)||x.Progress is <0 or >100||x.ActualHours<0||s=="COMPLETED"&&x.Progress!=100)return Bad("ข้อมูลความคืบหน้าไม่ถูกต้อง","งานเสร็จต้องเป็น 100% และชั่วโมงต้องไม่ติดลบ");if(!Scope(out var c,out var u))return Forbid();await using var db=await Open(t);if(!await Can(db,"42004","EDIT",t))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);var old=(await Q(db,tx,"SELECT x.StatusCode status,x.ProgressPercent progress FROM dbo.TDPMProjectTask x JOIN dbo.TDADUserEmployee ue ON ue.CompanyID=x.CompanyID AND ue.EmployeeID=x.AssigneeEmployeeID AND ue.UserID=@u AND ue.IsActive=1 WHERE x.CompanyID=@c AND x.ProjectTaskID=@id",t,("@c",c),("@u",u),("@id",id))).FirstOrDefault();if(old is null){await tx.RollbackAsync(t);return NotFound();}await X(db,tx,"UPDATE dbo.TDPMProjectTask SET StatusCode=@s,ProgressPercent=@p,ActualHours=@h,UpdateNote=@n,UpdateBy=@u,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@c AND ProjectTaskID=@id",t,("@s",s),("@p",x.Progress),("@h",x.ActualHours),("@n",Clean(x.Note)),("@u",u),("@c",c),("@id",id));await X(db,tx,"INSERT dbo.TDPMProjectTaskHistory(CompanyID,ProjectTaskID,OldStatusCode,NewStatusCode,OldProgressPercent,NewProgressPercent,ActualHours,NoteText,ChangedBy) VALUES(@c,@id,@os,@s,@op,@p,@h,@n,@u)",t,("@c",c),("@id",id),("@os",old["status"]),("@s",s),("@op",old["progress"]),("@p",x.Progress),("@h",x.ActualHours),("@n",Clean(x.Note)),("@u",u));await tx.CommitAsync(t);return NoContent();}
 [HttpGet("reports")] public async Task<IActionResult> Reports(int? year,int? month,string? status,long? departmentId,long? managerId,CancellationToken t){if(!Scope(out var c,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,"42005","VIEW",t))return Forbid();const string w=" FROM dbo.TDPMProject p WHERE p.CompanyID=@c AND (@y IS NULL OR YEAR(p.StartDate)=@y) AND (@mth IS NULL OR MONTH(p.StartDate)=@mth) AND (@s IS NULL OR p.StatusCode=@s) AND (@d IS NULL OR p.DepartmentOrgUnitID=@d) AND (@m IS NULL OR p.ManagerEmployeeID=@m)";var a=new(string,object?)[]{("@c",c),("@y",year),("@mth",month),("@s",Clean(status)),("@d",departmentId),("@m",managerId)};var summary=(await Q(db,"SELECT COUNT(*) total,SUM(CASE WHEN StatusCode=N'COMPLETED' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN StatusCode=N'ACTIVE' AND EndDate<CAST(SYSUTCDATETIME() AS date) THEN 1 ELSE 0 END) delayed,ISNULL(SUM(BudgetAmount),0) budget"+w,t,a)).First();var actual=await S<decimal>(db,@"SELECT ISNULL(SUM(v.amount),0) FROM(SELECT e.TotalAmount amount FROM dbo.TDEXExpense e JOIN dbo.TDPMProject p ON p.CompanyID=e.CompanyID AND p.BusinessProjectID=e.BusinessProjectID WHERE e.CompanyID=@c AND e.StatusCode=N'RECORDED' AND (@y IS NULL OR YEAR(p.StartDate)=@y) AND (@mth IS NULL OR MONTH(p.StartDate)=@mth) AND (@s IS NULL OR p.StatusCode=@s) AND (@d IS NULL OR p.DepartmentOrgUnitID=@d) AND (@m IS NULL OR p.ManagerEmployeeID=@m) UNION ALL SELECT e.TotalAmount FROM dbo.TDEXExpenseDocument e JOIN dbo.TDPMProject p ON p.CompanyID=e.CompanyID AND p.BusinessProjectID=e.BusinessProjectID WHERE e.CompanyID=@c AND e.StatusCode IN(N'APPROVED',N'PAID',N'SETTLED') AND (@y IS NULL OR YEAR(p.StartDate)=@y) AND (@mth IS NULL OR MONTH(p.StartDate)=@mth) AND (@s IS NULL OR p.StatusCode=@s) AND (@d IS NULL OR p.DepartmentOrgUnitID=@d) AND (@m IS NULL OR p.ManagerEmployeeID=@m))v",t,a);var byStatus=await Q(db,"SELECT StatusCode label,COUNT(*) value"+w+" GROUP BY StatusCode ORDER BY StatusCode",t,a);var delayed=await Q(db,"SELECT TOP(20) p.BusinessProjectID AS id,p.ProjectNo AS code,p.ProjectName AS name,p.EndDate,p.ProgressPercent AS progress"+w+" AND p.StatusCode=N'ACTIVE' AND p.EndDate<CAST(SYSUTCDATETIME() AS date) ORDER BY p.EndDate",t,a);summary["actual"]=actual;summary["balance"]=Convert.ToDecimal(summary["budget"])-actual;return Ok(new{summary,byStatus,delayed});}
 static void Header(SqlCommand q,long c,long? id,ProjectInput x,string name,long u){P(q,"@c",c);P(q,"@id",id);P(q,"@name",name);P(q,"@manager",x.ManagerId);P(q,"@department",x.DepartmentId);P(q,"@start",x.StartDate.Date);P(q,"@end",x.EndDate.Date);P(q,"@budget",x.Budget);P(q,"@status",Clean(x.Status)?.ToUpperInvariant()??"DRAFT");P(q,"@description",Clean(x.Description));P(q,"@remark",Clean(x.Remark));P(q,"@u",u);}
 async Task Ensure(SqlConnection db,long c,CancellationToken t)=>await X(db,"DECLARE @p bigint=(SELECT ProjectID FROM dbo.TDADProject WHERE ProjectCode=N'LAOO_PROJECT' AND IsActive=1);IF NOT EXISTS(SELECT 1 FROM dbo.TDPMProjectSystemSetting WHERE CompanyID=@c) INSERT dbo.TDPMProjectSystemSetting(CompanyID,ProjectID,CreateBy) VALUES(@c,@p,0)",t,("@c",c));
 Task<bool> Can(SqlConnection db,string m,string a,CancellationToken t)=>CompanyMenuAccess.IsAllowedAsync(db,User,m,a,t);
 bool Scope(out long c,out long u){c=0;u=0;return User.FindFirstValue("user_type")=="COMPANY_USER"&&string.Equals(User.FindFirstValue("project_code"),"LAOO_PROJECT",StringComparison.OrdinalIgnoreCase)&&long.TryParse(User.FindFirstValue("company_id"),out c)&&long.TryParse(User.FindFirstValue("user_id"),out u)&&c>0&&u>0;}
 async Task<SqlConnection> Open(CancellationToken t){var db=new SqlConnection(cfg.GetConnectionString("LaooDatabase"));await db.OpenAsync(t);return db;}
 static string? Clean(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();BadRequestObjectResult Bad(string m,string d)=>BadRequest(new{message=m,description=d});
 static void P(SqlCommand q,string n,object? v){var p=q.Parameters.AddWithValue(n,v??DBNull.Value);if(v is decimal){p.SqlDbType=SqlDbType.Decimal;p.Precision=18;p.Scale=2;}}
 static async Task<int> X(SqlConnection db,string sql,CancellationToken t,params(string,object?)[] a){await using var q=new SqlCommand(sql,db);foreach(var v in a)P(q,v.Item1,v.Item2);return await q.ExecuteNonQueryAsync(t);}static async Task<int> X(SqlConnection db,SqlTransaction tx,string sql,CancellationToken t,params(string,object?)[] a){await using var q=new SqlCommand(sql,db,tx);foreach(var v in a)P(q,v.Item1,v.Item2);return await q.ExecuteNonQueryAsync(t);}
 static async Task<T> S<T>(SqlConnection db,string sql,CancellationToken t,params(string,object?)[] a){await using var q=new SqlCommand(sql,db);foreach(var v in a)P(q,v.Item1,v.Item2);var z=await q.ExecuteScalarAsync(t);return z is null||z==DBNull.Value?default!:(T)Convert.ChangeType(z,typeof(T));}
 static async Task<List<Dictionary<string,object?>>> Q(SqlConnection db,string sql,CancellationToken t,params(string,object?)[] a){await using var q=new SqlCommand(sql,db);foreach(var v in a)P(q,v.Item1,v.Item2);return await Read(q,t);}static async Task<List<Dictionary<string,object?>>> Q(SqlConnection db,SqlTransaction tx,string sql,CancellationToken t,params(string,object?)[] a){await using var q=new SqlCommand(sql,db,tx);foreach(var v in a)P(q,v.Item1,v.Item2);return await Read(q,t);}static async Task<List<Dictionary<string,object?>>> Read(SqlCommand q,CancellationToken t){await using var r=await q.ExecuteReaderAsync(t);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(t)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++){var n=r.GetName(i);d[char.ToLowerInvariant(n[0])+n[1..]]=r.IsDBNull(i)?null:r.GetValue(i);}rows.Add(d);}return rows;}
}
public sealed record SettingInput(bool IsEnabled,string ProjectNoFormat,int DueWarningDays,bool AllowOverBudget,bool RequireBudgetBeforeStart,bool RequireTasksCompleteBeforeClose);
public sealed record CategoryInput(string Code,string Name,int SortOrder,string? Remark,bool IsActive=true);
public sealed record MemberInput(long EmployeeId,string Role,DateTime? JoinDate);
public sealed record ProjectTaskLine(string Name,long AssigneeId,DateTime StartDate,DateTime DueDate,decimal PlannedHours,decimal Weight);
public sealed record BudgetLine(long CategoryId,string? Description,decimal Amount);
public sealed record ProjectInput(string? Code,string Name,long ManagerId,long? DepartmentId,DateTime StartDate,DateTime EndDate,decimal Budget,string Status,string? Description,string? Remark,List<MemberInput> Members,List<ProjectTaskLine> Tasks,List<BudgetLine> Budgets);
public sealed record TaskInput(string Status,decimal Progress,decimal ActualHours,string? Note);