import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'laoo_typography.dart';

class WorkspaceThemePreset {
  const WorkspaceThemePreset({
    required this.code,
    required this.name,
    required this.group,
    required this.primary,
    required this.background,
    required this.surface,
    required this.sidebarBackground,
    required this.sidebarText,
    required this.textPrimary,
    required this.textSecondary,
    required this.border,
    this.isDark = false,
  });

  final String code;
  final String name;
  final String group;
  final Color primary;
  final Color background;
  final Color surface;
  final Color sidebarBackground;
  final Color sidebarText;
  final Color textPrimary;
  final Color textSecondary;
  final Color border;
  final bool isDark;

  ThemeData toThemeData() {
    final brightness = isDark ? Brightness.dark : Brightness.light;
    final scheme = ColorScheme.fromSeed(
      seedColor: primary,
      brightness: brightness,
      surface: surface,
    );
    final baseTheme = ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorScheme: scheme,
      scaffoldBackgroundColor: background,
      dividerColor: border,
    );

    final themedText = baseTheme.textTheme.apply(
      fontFamily: LaooTypography.fontFamily,
      fontFamilyFallback: LaooTypography.fontFallback,
    );

    return baseTheme.copyWith(
      textTheme: themedText.copyWith(
        bodyLarge: themedText.bodyLarge?.copyWith(
          fontSize: LaooTypography.body,
          height: LaooTypography.bodyLineHeight,
          color: textPrimary,
        ),
        bodyMedium: themedText.bodyMedium?.copyWith(
          fontSize: LaooTypography.body,
          height: LaooTypography.bodyLineHeight,
          color: textPrimary,
        ),
        bodySmall: themedText.bodySmall?.copyWith(
          fontSize: LaooTypography.bodySmall,
          height: LaooTypography.bodyLineHeight,
          color: textSecondary,
        ),
        labelLarge: themedText.labelLarge?.copyWith(
          fontSize: LaooTypography.button,
          height: LaooTypography.bodyLineHeight,
        ),
        labelMedium: themedText.labelMedium?.copyWith(
          fontSize: LaooTypography.inputLabel,
          height: LaooTypography.bodyLineHeight,
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        isDense: true,
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 14,
          vertical: 12,
        ),
        labelStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.inputHint,
          height: LaooTypography.bodyLineHeight,
          color: textSecondary,
        ),
        floatingLabelStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.inputLabel,
          height: LaooTypography.bodyLineHeight,
          color: primary,
        ),
        hintStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.inputHint,
          height: LaooTypography.inputLineHeight,
          color: textSecondary,
        ),
        helperStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.validation,
          height: LaooTypography.bodyLineHeight,
          color: textSecondary,
        ),
        errorStyle: const TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontSize: LaooTypography.validation,
          height: LaooTypography.bodyLineHeight,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: primary, width: 1.5),
        ),
      ),
      dialogTheme: DialogThemeData(
        titleTextStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.sectionTitle,
          height: LaooTypography.titleLineHeight,
          fontWeight: FontWeight.w700,
          color: textPrimary,
        ),
        contentTextStyle: TextStyle(
          fontFamily: LaooTypography.fontFamily,
          fontFamilyFallback: LaooTypography.fontFallback,
          fontSize: LaooTypography.inputText,
          height: LaooTypography.bodyLineHeight,
          color: textPrimary,
        ),
        actionsPadding: const EdgeInsets.fromLTRB(18, 4, 18, 10),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          textStyle: const TextStyle(
            fontFamily: LaooTypography.fontFamily,
            fontSize: LaooTypography.button,
            height: LaooTypography.bodyLineHeight,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          alignment: Alignment.center,
          minimumSize: const Size(0, LaooTypography.buttonHeight),
          maximumSize: const Size(double.infinity, LaooTypography.buttonHeight),
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
          textStyle: const TextStyle(
            fontFamily: LaooTypography.fontFamily,
            fontSize: LaooTypography.button,
            height: LaooTypography.bodyLineHeight,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          alignment: Alignment.center,
          minimumSize: const Size(0, LaooTypography.buttonHeight),
          maximumSize: const Size(double.infinity, LaooTypography.buttonHeight),
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
          textStyle: const TextStyle(
            fontFamily: LaooTypography.fontFamily,
            fontSize: LaooTypography.button,
            height: LaooTypography.bodyLineHeight,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          alignment: Alignment.center,
          minimumSize: const Size(0, LaooTypography.buttonHeight),
          maximumSize: const Size(double.infinity, LaooTypography.buttonHeight),
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 0),
          textStyle: const TextStyle(
            fontFamily: LaooTypography.fontFamily,
            fontSize: LaooTypography.button,
            height: LaooTypography.bodyLineHeight,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    );
  }
}

Color _c(int value) => Color(value);

final List<WorkspaceThemePreset> workspaceThemePresets = [
  // STYLE11 is intentionally Green Soft (old Style 2) and is the Laoo default.
  WorkspaceThemePreset(
    code: 'STYLE31',
    name: 'Emerald Green',
    group: 'White Menu',
    primary: _c(0xFF14805E),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF14805E),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE4E8E6),
  ),
  WorkspaceThemePreset(
    code: 'STYLE32',
    name: 'Teal Blue',
    group: 'White Menu',
    primary: _c(0xFF1597A5),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF117985),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE1EAEB),
  ),
  WorkspaceThemePreset(
    code: 'STYLE33',
    name: 'Royal Blue',
    group: 'White Menu',
    primary: _c(0xFF1565C0),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF1554A0),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE0E7F0),
  ),
  WorkspaceThemePreset(
    code: 'STYLE34',
    name: 'Purple Violet',
    group: 'White Menu',
    primary: _c(0xFF673AB7),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF5E35A1),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE8E2F0),
  ),
  WorkspaceThemePreset(
    code: 'STYLE35',
    name: 'Magenta Pink',
    group: 'White Menu',
    primary: _c(0xFFEC407A),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFFD72E68),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E1E6),
  ),
  WorkspaceThemePreset(
    code: 'STYLE36',
    name: 'Rose Pink',
    group: 'White Menu',
    primary: _c(0xFFF43F6B),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFFD92D58),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E2E6),
  ),
  WorkspaceThemePreset(
    code: 'STYLE37',
    name: 'Sunset Orange',
    group: 'White Menu',
    primary: _c(0xFFFF5A1F),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFFE34B14),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF2E3DC),
  ),
  WorkspaceThemePreset(
    code: 'STYLE38',
    name: 'Golden Yellow',
    group: 'White Menu',
    primary: _c(0xFFF5A300),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFFB87900),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E8D5),
  ),
  WorkspaceThemePreset(
    code: 'STYLE39',
    name: 'Warm Brown',
    group: 'White Menu',
    primary: _c(0xFF795548),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF6D4C41),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFEAE3E0),
  ),
  WorkspaceThemePreset(
    code: 'STYLE40',
    name: 'Charcoal Gray',
    group: 'White Menu',
    primary: _c(0xFF5F6368),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFFFFF),
    sidebarText: _c(0xFF4F5357),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE3E4E5),
  ),
  WorkspaceThemePreset(
    code: 'STYLE11',
    name: 'Green Soft',
    group: 'Light',
    primary: _c(0xFF2E7D32),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFF1FAF4),
    sidebarText: _c(0xFF256B2B),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDDE7DF),
  ),
  WorkspaceThemePreset(
    code: 'STYLE12',
    name: 'Green Fresh',
    group: 'Light',
    primary: _c(0xFF198754),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF198754),
    sidebarText: _c(0xFFFFFFFF),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDCE8E1),
  ),
  WorkspaceThemePreset(
    code: 'STYLE13',
    name: 'Blue Ocean',
    group: 'Light',
    primary: _c(0xFF1976D2),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF1976D2),
    sidebarText: _c(0xFFFFFFFF),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDCE6F2),
  ),
  WorkspaceThemePreset(
    code: 'STYLE14',
    name: 'Blue Sky',
    group: 'Light',
    primary: _c(0xFF42A5F5),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFE1F5FE),
    sidebarText: _c(0xFF1565C0),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDDEAF4),
  ),
  WorkspaceThemePreset(
    code: 'STYLE15',
    name: 'Purple Elegant',
    group: 'Light',
    primary: _c(0xFF7B1FA2),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF7B1FA2),
    sidebarText: _c(0xFFFFFFFF),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE8DCEF),
  ),
  WorkspaceThemePreset(
    code: 'STYLE16',
    name: 'Pink Soft',
    group: 'Light',
    primary: _c(0xFFE91E63),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFE4EC),
    sidebarText: _c(0xFFC2185B),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF2DDE5),
  ),
  WorkspaceThemePreset(
    code: 'STYLE17',
    name: 'Yellow Bright',
    group: 'Light',
    primary: _c(0xFFF9A825),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFF3CD),
    sidebarText: _c(0xFF8A6200),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E5C8),
  ),
  WorkspaceThemePreset(
    code: 'STYLE18',
    name: 'Orange Warm',
    group: 'Light',
    primary: _c(0xFFF57C00),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFFFE3D0),
    sidebarText: _c(0xFFC75B00),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF2DFD1),
  ),
  WorkspaceThemePreset(
    code: 'STYLE19',
    name: 'Gray Light',
    group: 'Light',
    primary: _c(0xFF607D8B),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFFF5F5F5),
    sidebarText: _c(0xFF455A64),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE2E5E8),
  ),
  WorkspaceThemePreset(
    code: 'STYLE20',
    name: 'Dark Gray Accent',
    group: 'Light',
    primary: _c(0xFF424342),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF424342),
    sidebarText: _c(0xFFFFFFFF),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE0E0E0),
  ),
  WorkspaceThemePreset(
    code: 'STYLE21',
    name: 'Soft Charcoal Green',
    group: 'Soft Dark',
    primary: _c(0xFF2DD881),
    background: _c(0xFF0F1B21),
    surface: _c(0xFF16252C),
    sidebarBackground: _c(0xFF14242B),
    sidebarText: _c(0xFFE7F3ED),
    textPrimary: _c(0xFFE8EEF1),
    textSecondary: _c(0xFFAFBEC5),
    border: _c(0xFF2A3C44),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE22',
    name: 'Slate Blue Soft',
    group: 'Soft Dark',
    primary: _c(0xFF38C7D9),
    background: _c(0xFF101D26),
    surface: _c(0xFF172833),
    sidebarBackground: _c(0xFF142630),
    sidebarText: _c(0xFFE5F2F5),
    textPrimary: _c(0xFFE8EEF1),
    textSecondary: _c(0xFFAFC0C8),
    border: _c(0xFF2A3E49),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE23',
    name: 'Night Blue Calm',
    group: 'Soft Dark',
    primary: _c(0xFF55A7FF),
    background: _c(0xFF111D2B),
    surface: _c(0xFF19283A),
    sidebarBackground: _c(0xFF162536),
    sidebarText: _c(0xFFE8F0FA),
    textPrimary: _c(0xFFE8EEF5),
    textSecondary: _c(0xFFB1BDCC),
    border: _c(0xFF2C3D51),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE24',
    name: 'Indigo Soft',
    group: 'Soft Dark',
    primary: _c(0xFFB388FF),
    background: _c(0xFF171B2A),
    surface: _c(0xFF202538),
    sidebarBackground: _c(0xFF1D2234),
    sidebarText: _c(0xFFF0E9FF),
    textPrimary: _c(0xFFEDECF3),
    textSecondary: _c(0xFFBDB9CB),
    border: _c(0xFF353A50),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE25',
    name: 'Plum Soft',
    group: 'Soft Dark',
    primary: _c(0xFFFF7A9D),
    background: _c(0xFF211820),
    surface: _c(0xFF2C202A),
    sidebarBackground: _c(0xFF281D26),
    sidebarText: _c(0xFFFFEAF0),
    textPrimary: _c(0xFFF2E9EE),
    textSecondary: _c(0xFFC9B8C1),
    border: _c(0xFF44323D),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE26',
    name: 'Warm Gray Orange',
    group: 'Soft Dark',
    primary: _c(0xFFFF8A3D),
    background: _c(0xFF211B18),
    surface: _c(0xFF2C2521),
    sidebarBackground: _c(0xFF28211D),
    sidebarText: _c(0xFFFFEEE3),
    textPrimary: _c(0xFFF1ECE8),
    textSecondary: _c(0xFFC7BBB4),
    border: _c(0xFF44372F),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE27',
    name: 'Coffee Brown Soft',
    group: 'Soft Dark',
    primary: _c(0xFFFFC247),
    background: _c(0xFF211D18),
    surface: _c(0xFF2C2821),
    sidebarBackground: _c(0xFF28241D),
    sidebarText: _c(0xFFFFF2D7),
    textPrimary: _c(0xFFF0ECE5),
    textSecondary: _c(0xFFC5BEB0),
    border: _c(0xFF433C30),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE28',
    name: 'Deep Teal Soft',
    group: 'Soft Dark',
    primary: _c(0xFF35D0C0),
    background: _c(0xFF101F20),
    surface: _c(0xFF172B2C),
    sidebarBackground: _c(0xFF142728),
    sidebarText: _c(0xFFE3F5F2),
    textPrimary: _c(0xFFE8F0EF),
    textSecondary: _c(0xFFAFC4C1),
    border: _c(0xFF294142),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE29',
    name: 'Graphite Gray',
    group: 'Soft Dark',
    primary: _c(0xFFA8BEDA),
    background: _c(0xFF171C22),
    surface: _c(0xFF20262D),
    sidebarBackground: _c(0xFF1D232A),
    sidebarText: _c(0xFFE8EDF2),
    textPrimary: _c(0xFFE9EDF1),
    textSecondary: _c(0xFFB7C0C9),
    border: _c(0xFF353D46),
    isDark: true,
  ),
  WorkspaceThemePreset(
    code: 'STYLE30',
    name: 'Stone Gray Soft',
    group: 'Soft Dark',
    primary: _c(0xFFC2C8CC),
    background: _c(0xFF1A1E20),
    surface: _c(0xFF24292C),
    sidebarBackground: _c(0xFF202528),
    sidebarText: _c(0xFFEEF0F1),
    textPrimary: _c(0xFFECEEEF),
    textSecondary: _c(0xFFBEC3C6),
    border: _c(0xFF3A4145),
    isDark: true,
  ),

  WorkspaceThemePreset(
    code: 'STYLE01',
    name: 'Soft Charcoal Green Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFF2DD881),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF14242B),
    sidebarText: _c(0xFFE7F3ED),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDDE5E8),
  ),
  WorkspaceThemePreset(
    code: 'STYLE02',
    name: 'Slate Blue Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFF38C7D9),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF142630),
    sidebarText: _c(0xFFE5F2F5),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDCE6EA),
  ),
  WorkspaceThemePreset(
    code: 'STYLE03',
    name: 'Night Blue Calm Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFF55A7FF),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF162536),
    sidebarText: _c(0xFFE8F0FA),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDCE5EF),
  ),
  WorkspaceThemePreset(
    code: 'STYLE04',
    name: 'Indigo Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFB388FF),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF1D2234),
    sidebarText: _c(0xFFF0E9FF),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE6E0EF),
  ),
  WorkspaceThemePreset(
    code: 'STYLE05',
    name: 'Plum Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFFF7A9D),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF281D26),
    sidebarText: _c(0xFFFFEAF0),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E0E5),
  ),
  WorkspaceThemePreset(
    code: 'STYLE06',
    name: 'Warm Gray Orange Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFFF8A3D),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF28211D),
    sidebarText: _c(0xFFFFEEE3),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFF0E3DC),
  ),
  WorkspaceThemePreset(
    code: 'STYLE07',
    name: 'Coffee Brown Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFFFC247),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF28241D),
    sidebarText: _c(0xFFFFF2D7),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFEDE5D7),
  ),
  WorkspaceThemePreset(
    code: 'STYLE08',
    name: 'Deep Teal Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFF35D0C0),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF142728),
    sidebarText: _c(0xFFE3F5F2),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFDCE9E7),
  ),
  WorkspaceThemePreset(
    code: 'STYLE09',
    name: 'Graphite Gray Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFA8BEDA),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF1D232A),
    sidebarText: _c(0xFFE8EDF2),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE1E5EA),
  ),
  WorkspaceThemePreset(
    code: 'STYLE10',
    name: 'Stone Gray Soft Hybrid',
    group: 'Hybrid Dark Menu',
    primary: _c(0xFFC2C8CC),
    background: _c(0xFFFFFFFF),
    surface: _c(0xFFFFFFFF),
    sidebarBackground: _c(0xFF202528),
    sidebarText: _c(0xFFEEF0F1),
    textPrimary: _c(0xFF212529),
    textSecondary: _c(0xFF667085),
    border: _c(0xFFE3E5E6),
  ),
];

WorkspaceThemePreset workspaceThemeByCode(String code) =>
    workspaceThemePresets.firstWhere(
      (item) => item.code == code,
      orElse: () => workspaceThemePresets.firstWhere(
        (item) => item.code == 'STYLE01',
      ),
    );

class WorkspaceThemeController extends ValueNotifier<WorkspaceThemePreset> {
  WorkspaceThemeController() : super(workspaceThemeByCode('STYLE01'));

  static const _preferenceKey = 'workspace.theme.code';

  Future<void> initialize() async {
    final preferences = await SharedPreferences.getInstance();
    final savedCode = preferences.getString(_preferenceKey);

    if (savedCode != null) {
      value = workspaceThemeByCode(savedCode);
    }
  }

  Future<void> save(WorkspaceThemePreset preset) async {
    final preferences = await SharedPreferences.getInstance();
    final saved = await preferences.setString(_preferenceKey, preset.code);

    if (!saved) {
      throw StateError('Unable to save workspace theme preference.');
    }

    value = preset;
  }
}

final WorkspaceThemeController workspaceThemeController =
    WorkspaceThemeController();
