SET XACT_ABORT ON;
BEGIN TRY
 BEGIN TRANSACTION;
 IF OBJECT_ID(N'dbo.TDMESystemSetting',N'U') IS NULL CREATE TABLE dbo.TDMESystemSetting(CompanyID bigint NOT NULL PRIMARY KEY,MaxAttachmentMB int NOT NULL CONSTRAINT DF_TDMESetting_Size DEFAULT(20),AllowedExtensions nvarchar(500) NOT NULL CONSTRAINT DF_TDMESetting_Ext DEFAULT(N'pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png'),AutoDistribute bit NOT NULL CONSTRAINT DF_TDMESetting_Distribute DEFAULT(1),CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMESetting_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT CK_TDMESetting_Size CHECK(MaxAttachmentMB BETWEEN 1 AND 200));
 IF OBJECT_ID(N'dbo.TDMEApprovalRoute',N'U') IS NULL CREATE TABLE dbo.TDMEApprovalRoute(RouteID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,RouteCode nvarchar(40) NOT NULL,RouteName nvarchar(200) NOT NULL,IsActive bit NOT NULL CONSTRAINT DF_TDMERoute_Active DEFAULT(1),CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMERoute_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT UQ_TDMERoute UNIQUE(CompanyID,RouteCode));
 IF OBJECT_ID(N'dbo.TDMEApprovalRouteStep',N'U') IS NULL CREATE TABLE dbo.TDMEApprovalRouteStep(RouteStepID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,RouteID bigint NOT NULL,StepOrder int NOT NULL,AssigneeUserID bigint NOT NULL,StepName nvarchar(200) NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMERouteStep_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDMERouteStep_Route FOREIGN KEY(RouteID) REFERENCES dbo.TDMEApprovalRoute(RouteID) ON DELETE CASCADE,CONSTRAINT UQ_TDMERouteStep UNIQUE(CompanyID,RouteID,StepOrder));
 IF OBJECT_ID(N'dbo.TDMETemplate',N'U') IS NULL CREATE TABLE dbo.TDMETemplate(TemplateID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,TemplateCode nvarchar(40) NOT NULL,TemplateName nvarchar(200) NOT NULL,SubjectDefault nvarchar(500) NULL,BodyDeltaJson nvarchar(max) NULL,BodyPlainText nvarchar(max) NULL,IsActive bit NOT NULL CONSTRAINT DF_TDMETemplate_Active DEFAULT(1),CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMETemplate_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT UQ_TDMETemplate UNIQUE(CompanyID,TemplateCode));
 IF OBJECT_ID(N'dbo.TDMEType',N'U') IS NULL CREATE TABLE dbo.TDMEType(MemoTypeID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,TypeCode nvarchar(40) NOT NULL,TypeName nvarchar(200) NOT NULL,NumberPrefix nvarchar(30) NOT NULL,DefaultRouteID bigint NULL,DefaultTemplateID bigint NULL,DefaultConfidentiality nvarchar(20) NOT NULL CONSTRAINT DF_TDMEType_Secret DEFAULT(N'INTERNAL'),IsActive bit NOT NULL CONSTRAINT DF_TDMEType_Active DEFAULT(1),CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMEType_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT FK_TDMEType_Route FOREIGN KEY(DefaultRouteID) REFERENCES dbo.TDMEApprovalRoute(RouteID),CONSTRAINT FK_TDMEType_Template FOREIGN KEY(DefaultTemplateID) REFERENCES dbo.TDMETemplate(TemplateID),CONSTRAINT UQ_TDMEType UNIQUE(CompanyID,TypeCode),CONSTRAINT CK_TDMEType_Secret CHECK(DefaultConfidentiality IN(N'NORMAL',N'INTERNAL',N'SECRET')));
 IF OBJECT_ID(N'dbo.TDMEMemo',N'U') IS NULL CREATE TABLE dbo.TDMEMemo(MemoID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoTypeID bigint NOT NULL,TemporaryNo nvarchar(80) NOT NULL,MemoNo nvarchar(80) NULL,SubjectText nvarchar(500) NOT NULL,ToText nvarchar(1000) NOT NULL,MemoDate date NOT NULL,OwnerUserID bigint NOT NULL,OwnerDepartmentID bigint NULL,ConfidentialityCode nvarchar(20) NOT NULL,StatusCode nvarchar(30) NOT NULL,CurrentVersionID bigint NULL,ApprovedAt datetime2 NULL,DistributedAt datetime2 NULL,CancelReason nvarchar(2000) NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMEMemo_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT FK_TDMEMemo_Type FOREIGN KEY(MemoTypeID) REFERENCES dbo.TDMEType(MemoTypeID),CONSTRAINT UQ_TDMEMemo_Temp UNIQUE(CompanyID,TemporaryNo),CONSTRAINT CK_TDMEMemo_Secret CHECK(ConfidentialityCode IN(N'NORMAL',N'INTERNAL',N'SECRET')),CONSTRAINT CK_TDMEMemo_Status CHECK(StatusCode IN(N'DRAFT',N'IN_APPROVAL',N'RETURNED',N'APPROVED',N'DISTRIBUTED',N'WITHDRAWN',N'CANCELLED')));
 IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDMEMemo') AND name=N'UQ_TDMEMemo_No') CREATE UNIQUE INDEX UQ_TDMEMemo_No ON dbo.TDMEMemo(CompanyID,MemoNo) WHERE MemoNo IS NOT NULL;
 IF OBJECT_ID(N'dbo.TDMEMemoVersion',N'U') IS NULL CREATE TABLE dbo.TDMEMemoVersion(VersionID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoID bigint NOT NULL,VersionNo int NOT NULL,BodyDeltaJson nvarchar(max) NOT NULL,BodyPlainText nvarchar(max) NOT NULL,IsLocked bit NOT NULL CONSTRAINT DF_TDMEVersion_Locked DEFAULT(0),SubmittedAt datetime2 NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMEVersion_Create DEFAULT(SYSUTCDATETIME()),UpdateBy bigint NULL,UpdateDate datetime2 NULL,CONSTRAINT FK_TDMEVersion_Memo FOREIGN KEY(MemoID) REFERENCES dbo.TDMEMemo(MemoID),CONSTRAINT UQ_TDMEVersion UNIQUE(CompanyID,MemoID,VersionNo));
 IF OBJECT_ID(N'dbo.TDMEMemoRecipient',N'U') IS NULL CREATE TABLE dbo.TDMEMemoRecipient(RecipientID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoID bigint NOT NULL,VersionID bigint NOT NULL,RecipientRole nvarchar(10) NOT NULL,SubjectType nvarchar(20) NOT NULL,SubjectID bigint NOT NULL,ReadAt datetime2 NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMERecipient_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDMERecipient_Memo FOREIGN KEY(MemoID) REFERENCES dbo.TDMEMemo(MemoID),CONSTRAINT FK_TDMERecipient_Version FOREIGN KEY(VersionID) REFERENCES dbo.TDMEMemoVersion(VersionID),CONSTRAINT CK_TDMERecipient_Role CHECK(RecipientRole IN(N'TO',N'CC')),CONSTRAINT CK_TDMERecipient_Type CHECK(SubjectType IN(N'USER',N'DEPARTMENT',N'ROLE')));
 IF OBJECT_ID(N'dbo.TDMEMemoApproval',N'U') IS NULL CREATE TABLE dbo.TDMEMemoApproval(ApprovalID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoID bigint NOT NULL,VersionID bigint NOT NULL,StepOrder int NOT NULL,StepName nvarchar(200) NULL,AssigneeUserID bigint NOT NULL,StatusCode nvarchar(20) NOT NULL CONSTRAINT DF_TDMEApproval_Status DEFAULT(N'WAITING'),DecisionBy bigint NULL,DecisionAt datetime2 NULL,DecisionNote nvarchar(2000) NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMEApproval_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDMEApproval_Memo FOREIGN KEY(MemoID) REFERENCES dbo.TDMEMemo(MemoID),CONSTRAINT FK_TDMEApproval_Version FOREIGN KEY(VersionID) REFERENCES dbo.TDMEMemoVersion(VersionID),CONSTRAINT UQ_TDMEApproval UNIQUE(CompanyID,VersionID,StepOrder),CONSTRAINT CK_TDMEApproval_Status CHECK(StatusCode IN(N'WAITING',N'PENDING',N'APPROVED',N'RETURNED',N'CANCELLED')));
 IF OBJECT_ID(N'dbo.TDMEAttachment',N'U') IS NULL CREATE TABLE dbo.TDMEAttachment(AttachmentID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoID bigint NOT NULL,VersionID bigint NOT NULL,FileKind nvarchar(20) NOT NULL,OriginalFileName nvarchar(260) NOT NULL,StoredFileName nvarchar(260) NOT NULL,RelativePath nvarchar(1000) NOT NULL,ContentType nvarchar(150) NOT NULL,FileSizeBytes bigint NOT NULL,Sha256 nvarchar(64) NOT NULL,CreateBy bigint NOT NULL,CreateDate datetime2 NOT NULL CONSTRAINT DF_TDMEAttachment_Create DEFAULT(SYSUTCDATETIME()),CONSTRAINT FK_TDMEAttachment_Memo FOREIGN KEY(MemoID) REFERENCES dbo.TDMEMemo(MemoID),CONSTRAINT FK_TDMEAttachment_Version FOREIGN KEY(VersionID) REFERENCES dbo.TDMEMemoVersion(VersionID),CONSTRAINT CK_TDMEAttachment_Kind CHECK(FileKind IN(N'INLINE',N'ATTACHMENT')));
 IF OBJECT_ID(N'dbo.TDMENumberSequence',N'U') IS NULL CREATE TABLE dbo.TDMENumberSequence(CompanyID bigint NOT NULL,MemoTypeID bigint NOT NULL,SequenceYear int NOT NULL,LastNumber int NOT NULL,UpdateDate datetime2 NOT NULL CONSTRAINT DF_TDMESequence_Update DEFAULT(SYSUTCDATETIME()),CONSTRAINT PK_TDMENumberSequence PRIMARY KEY(CompanyID,MemoTypeID,SequenceYear));
 IF OBJECT_ID(N'dbo.TDMEAudit',N'U') IS NULL CREATE TABLE dbo.TDMEAudit(AuditID bigint IDENTITY PRIMARY KEY,CompanyID bigint NOT NULL,MemoID bigint NULL,VersionID bigint NULL,ActionCode nvarchar(50) NOT NULL,DetailText nvarchar(2000) NULL,UserID bigint NOT NULL,IpAddress nvarchar(80) NULL,ActionDate datetime2 NOT NULL CONSTRAINT DF_TDMEAudit_Date DEFAULT(SYSUTCDATETIME()));
 IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDMEMemo') AND name=N'IX_TDMEMemo_Status') CREATE INDEX IX_TDMEMemo_Status ON dbo.TDMEMemo(CompanyID,StatusCode,OwnerUserID,CreateDate DESC);
 IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TDMEMemoApproval') AND name=N'IX_TDMEApproval_User') CREATE INDEX IX_TDMEApproval_User ON dbo.TDMEMemoApproval(CompanyID,AssigneeUserID,StatusCode,StepOrder);
 COMMIT;
END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH;
GO
