namespace LaooApi.Models;

public sealed record CustomerListRow(
    long CustomerID,
    string CusCode,
    string? CusShortCode,
    string CusName,
    string? CusGroupCode,
    string? BusinessTypeCode,
    string? ProvCode,
    string? Phone,
    bool IsActive,
    bool HasBusinessCard,
    bool HasCustomerDocument);

public sealed record CustomerUpsertRequest(
    string CusCode,
    string? CusShortCode,
    string CusName,
    string? CusAddress,
    string? ProvCode,
    string? PostCode,
    DateTime? StartDate,
    string? CusGroupCode,
    string? BusinessTypeCode,
    string? PriceLevelCode,
    string? Website,
    string? TaxID,
    string? Phone,
    string? Email,
    string? ContName1,
    string? PositionName1,
    string? Phone1,
    string? Email1,
    string? ContName2,
    string? PositionName2,
    string? Phone2,
    string? Email2,
    string? PaymentType,
    int? CreditDays,
    decimal? CreditLimit,
    long? SalespersonEmployeeID,
    string? TaxType,
    bool IsActive);
