SET NOCOUNT ON;
SET XACT_ABORT ON;
ALTER TABLE dbo.TDPTPackage ADD PosItemID bigint NULL;
GO
CREATE UNIQUE INDEX UX_TDPTPackage_PosItem ON dbo.TDPTPackage(CompanyID,PosItemID) WHERE PosItemID IS NOT NULL;
GO
