import 'package:laoo_gate_pass/gate_pass_feature.dart'
    show GatePassMenuCodes, GatePassRouteNames, GatePassRoutePaths;
import 'package:laoo_five_s/five_s_feature.dart'
    show FiveSMenuCodes, FiveSRouteNames, FiveSRoutePaths;
import 'package:laoo_survey/survey_feature.dart'
    show SurveyMenuCodes, SurveyRouteNames, SurveyRoutePaths;
import 'package:laoo_expense/expense_feature.dart'
    show ExpenseMenuCodes, ExpenseRouteNames, ExpenseRoutePaths;
import 'package:laoo_project/project_feature.dart'
    show ProjectMenuCodes, ProjectRouteNames, ProjectRoutePaths;
import 'package:laoo_intranet/intranet_feature.dart'
    show IntranetMenuCodes, IntranetRouteNames, IntranetRoutePaths;
import 'package:laoo_meeting/meeting_feature.dart'
    show MeetingMenuCodes, MeetingRoutes;
import 'package:laoo_service/service_feature.dart' show ServiceRoutes;
import 'package:laoo_time/time_feature.dart' show TimeRoutes;
import 'package:laoo_training/training_feature.dart' show TrainingRoutes;
import 'package:laoo_visitor/visitor_feature.dart' show VisitorRoutes;

import 'route_names.dart';
import 'route_paths.dart';

enum AppMenuScope { support, partner, company, shared }

class AppMenuRouteSpec {
  const AppMenuRouteSpec({
    required this.menuCode,
    required this.databaseRouteName,
    required this.goRouteName,
    required this.path,
    required this.scope,
  });

  final String menuCode;
  final String databaseRouteName;
  final String goRouteName;
  final String path;
  final AppMenuScope scope;
}

abstract final class AppMenuRouteRegistry {
  static final Map<String, AppMenuRouteSpec> _byMenuCode = {
    '13002': AppMenuRouteSpec(
      menuCode: '13002',
      databaseRouteName: 'companyPersons',
      goRouteName: RouteNames.companyPersons,
      path: RoutePaths.companyPersons,
      scope: AppMenuScope.company,
    ),

    '08007': AppMenuRouteSpec(
      menuCode: '08007',
      databaseRouteName: 'companyVendors',
      goRouteName: RouteNames.companyVendors,
      path: RoutePaths.companyVendors,
      scope: AppMenuScope.company,
    ),
    '01001': AppMenuRouteSpec(
      menuCode: '01001',
      databaseRouteName: 'partner',
      goRouteName: RouteNames.partner,
      path: RoutePaths.partner,
      scope: AppMenuScope.support,
    ),
    '01004': AppMenuRouteSpec(
      menuCode: '01004',
      databaseRouteName: 'technicalInfo',
      goRouteName: RouteNames.technicalInfo,
      path: RoutePaths.technicalInfo,
      scope: AppMenuScope.support,
    ),
    '01005': AppMenuRouteSpec(
      menuCode: '01005',
      databaseRouteName: 'globalSettings',
      goRouteName: RouteNames.globalSettings,
      path: RoutePaths.globalSettings,
      scope: AppMenuScope.support,
    ),
    '01006': AppMenuRouteSpec(
      menuCode: '01006',
      databaseRouteName: 'globalPermissionSettings',
      goRouteName: RouteNames.globalPermissionSettings,
      path: RoutePaths.globalPermissionSettings,
      scope: AppMenuScope.support,
    ),
    '02001': AppMenuRouteSpec(
      menuCode: '02001',
      databaseRouteName: 'laooUser',
      goRouteName: RouteNames.laooUser,
      path: RoutePaths.laooUser,
      scope: AppMenuScope.support,
    ),
    '02002': AppMenuRouteSpec(
      menuCode: '02002',
      databaseRouteName: 'partnerUser',
      goRouteName: RouteNames.partnerUser,
      path: RoutePaths.partnerUser,
      scope: AppMenuScope.support,
    ),
    '02003': AppMenuRouteSpec(
      menuCode: '02003',
      databaseRouteName: 'companyUser',
      goRouteName: RouteNames.companyUser,
      path: RoutePaths.companyUser,
      scope: AppMenuScope.support,
    ),
    '03001': AppMenuRouteSpec(
      menuCode: '03001',
      databaseRouteName: 'module',
      goRouteName: RouteNames.module,
      path: RoutePaths.module,
      scope: AppMenuScope.support,
    ),
    '03002': AppMenuRouteSpec(
      menuCode: '03002',
      databaseRouteName: 'customerModule',
      goRouteName: RouteNames.customerModule,
      path: RoutePaths.customerModule,
      scope: AppMenuScope.support,
    ),
    '03003': AppMenuRouteSpec(
      menuCode: '03003',
      databaseRouteName: 'permission',
      goRouteName: RouteNames.permission,
      path: RoutePaths.permission,
      scope: AppMenuScope.support,
    ),
    '04001': AppMenuRouteSpec(
      menuCode: '04001',
      databaseRouteName: 'audit',
      goRouteName: RouteNames.audit,
      path: RoutePaths.audit,
      scope: AppMenuScope.support,
    ),
    '04002': AppMenuRouteSpec(
      menuCode: '04002',
      databaseRouteName: 'loginLog',
      goRouteName: RouteNames.loginLog,
      path: RoutePaths.loginLog,
      scope: AppMenuScope.support,
    ),
    '05001': AppMenuRouteSpec(
      menuCode: '05001',
      databaseRouteName: 'companySetup',
      goRouteName: RouteNames.companySetup,
      path: RoutePaths.companySetup,
      scope: AppMenuScope.shared,
    ),
    '05002': AppMenuRouteSpec(
      menuCode: '05002',
      databaseRouteName: 'masterData',
      goRouteName: RouteNames.masterData,
      path: RoutePaths.masterData,
      scope: AppMenuScope.shared,
    ),
    '05003': AppMenuRouteSpec(
      menuCode: '05003',
      databaseRouteName: 'companySetupAdditional',
      goRouteName: RouteNames.companySetupAdditional,
      path: RoutePaths.companySetupAdditional,
      scope: AppMenuScope.shared,
    ),
    '01003': AppMenuRouteSpec(
      menuCode: '01003',
      databaseRouteName: 'branch',
      goRouteName: RouteNames.supportBranches,
      path: RoutePaths.supportBranches,
      scope: AppMenuScope.support,
    ),
    '06001': AppMenuRouteSpec(
      menuCode: '06001',
      databaseRouteName: 'partnerCompanies',
      goRouteName: RouteNames.partnerCompanies,
      path: RoutePaths.partnerCompanies,
      scope: AppMenuScope.partner,
    ),
    '06002': AppMenuRouteSpec(
      menuCode: '06002',
      databaseRouteName: 'partnerBranches',
      goRouteName: RouteNames.partnerBranches,
      path: RoutePaths.partnerBranches,
      scope: AppMenuScope.partner,
    ),
    '13001': AppMenuRouteSpec(
      menuCode: '13001',
      databaseRouteName: 'companyBranches',
      goRouteName: RouteNames.companyBranches,
      path: RoutePaths.companyBranches,
      scope: AppMenuScope.company,
    ),
    '09003': AppMenuRouteSpec(
      menuCode: '09003',
      databaseRouteName: 'companyQuotations',
      goRouteName: RouteNames.companyQuotations,
      path: RoutePaths.companyQuotations,
      scope: AppMenuScope.company,
    ),
    '09004': AppMenuRouteSpec(
      menuCode: '09004',
      databaseRouteName: 'companyPreOrders',
      goRouteName: RouteNames.companyPreOrders,
      path: RoutePaths.companyPreOrders,
      scope: AppMenuScope.company,
    ),
    '09005': AppMenuRouteSpec(
      menuCode: '09005',
      databaseRouteName: 'companyTemporaryReceipts',
      goRouteName: RouteNames.companyTemporaryReceipts,
      path: RoutePaths.companyTemporaryReceipts,
      scope: AppMenuScope.company,
    ),
    '09006': AppMenuRouteSpec(
      menuCode: '09006',
      databaseRouteName: 'companyDeliveryNotes',
      goRouteName: RouteNames.companyDeliveryNotes,
      path: RoutePaths.companyDeliveryNotes,
      scope: AppMenuScope.company,
    ),
    '09007': AppMenuRouteSpec(
      menuCode: '09007',
      databaseRouteName: 'companyTaxInvoices',
      goRouteName: RouteNames.companyTaxInvoices,
      path: RoutePaths.companyTaxInvoices,
      scope: AppMenuScope.company,
    ),
    '07001': AppMenuRouteSpec(
      menuCode: '07001',
      databaseRouteName: 'partnerUsers',
      goRouteName: RouteNames.partnerUsers,
      path: RoutePaths.partnerUsers,
      scope: AppMenuScope.partner,
    ),
    '11005': AppMenuRouteSpec(
      menuCode: '11005',
      databaseRouteName: 'organizationStructure',
      goRouteName: RouteNames.organizationStructure,
      path: RoutePaths.organizationStructure,
      scope: AppMenuScope.partner,
    ),
    '12005': AppMenuRouteSpec(
      menuCode: '12005',
      databaseRouteName: 'organizationStructure',
      goRouteName: RouteNames.organizationStructure,
      path: RoutePaths.organizationStructure,
      scope: AppMenuScope.support,
    ),
    '08001': AppMenuRouteSpec(
      menuCode: '08001',
      databaseRouteName: 'companyProducts',
      goRouteName: RouteNames.companyProducts,
      path: RoutePaths.companyProducts,
      scope: AppMenuScope.company,
    ),
    '09001': AppMenuRouteSpec(
      menuCode: '09001',
      databaseRouteName: 'companyCustomers',
      goRouteName: RouteNames.companyCustomers,
      path: RoutePaths.companyCustomers,
      scope: AppMenuScope.company,
    ),
    '09002': AppMenuRouteSpec(
      menuCode: '09002',
      databaseRouteName: 'companyBranches',
      goRouteName: RouteNames.companyBranches,
      path: RoutePaths.companyBranches,
      scope: AppMenuScope.company,
    ),
    '14001': AppMenuRouteSpec(
      menuCode: '14001',
      databaseRouteName: 'assetLocations',
      goRouteName: RouteNames.assetLocations,
      path: RoutePaths.assetLocations,
      scope: AppMenuScope.company,
    ),
    '14002': AppMenuRouteSpec(
      menuCode: '14002',
      databaseRouteName: 'assetItems',
      goRouteName: RouteNames.assetItems,
      path: RoutePaths.assetItems,
      scope: AppMenuScope.company,
    ),
    '14003': AppMenuRouteSpec(
      menuCode: '14003',
      databaseRouteName: 'assetCustomers',
      goRouteName: RouteNames.assetCustomers,
      path: RoutePaths.assetCustomers,
      scope: AppMenuScope.company,
    ),
    '15001': AppMenuRouteSpec(
      menuCode: '15001',
      databaseRouteName: 'cmTickets',
      goRouteName: RouteNames.cmTickets,
      path: RoutePaths.cmTickets,
      scope: AppMenuScope.company,
    ),
    '15002': AppMenuRouteSpec(
      menuCode: '15002',
      databaseRouteName: 'cmQrPortal',
      goRouteName: RouteNames.cmQrPortal,
      path: RoutePaths.cmQrPortal,
      scope: AppMenuScope.company,
    ),
    '16001': AppMenuRouteSpec(
      menuCode: '16001',
      databaseRouteName: 'pmPlans',
      goRouteName: RouteNames.pmPlans,
      path: RoutePaths.pmPlans,
      scope: AppMenuScope.company,
    ),
    '16002': AppMenuRouteSpec(
      menuCode: '16002',
      databaseRouteName: 'pmChecklists',
      goRouteName: RouteNames.pmChecklists,
      path: RoutePaths.pmChecklists,
      scope: AppMenuScope.company,
    ),
    '16003': AppMenuRouteSpec(
      menuCode: '16003',
      databaseRouteName: 'pmCalendar',
      goRouteName: RouteNames.pmCalendar,
      path: RoutePaths.pmCalendar,
      scope: AppMenuScope.company,
    ),
    '17001': AppMenuRouteSpec(
      menuCode: '17001',
      databaseRouteName: 'jobDispatch',
      goRouteName: RouteNames.jobDispatch,
      path: RoutePaths.jobDispatch,
      scope: AppMenuScope.company,
    ),
    '17002': AppMenuRouteSpec(
      menuCode: '17002',
      databaseRouteName: 'jobWorkOrders',
      goRouteName: RouteNames.jobWorkOrders,
      path: RoutePaths.jobWorkOrders,
      scope: AppMenuScope.company,
    ),
    '17003': AppMenuRouteSpec(
      menuCode: '17003',
      databaseRouteName: 'jobCloseout',
      goRouteName: RouteNames.jobCloseout,
      path: RoutePaths.jobCloseout,
      scope: AppMenuScope.company,
    ),
    '08002': AppMenuRouteSpec(
      menuCode: '08002',
      databaseRouteName: 'inventoryItems',
      goRouteName: RouteNames.inventoryItems,
      path: RoutePaths.inventoryItems,
      scope: AppMenuScope.company,
    ),
    '08003': AppMenuRouteSpec(
      menuCode: '08003',
      databaseRouteName: 'inventoryUsage',
      goRouteName: RouteNames.inventoryUsage,
      path: RoutePaths.inventoryUsage,
      scope: AppMenuScope.company,
    ),
    '19001': AppMenuRouteSpec(
      menuCode: '19001',
      databaseRouteName: 'reportsDashboard',
      goRouteName: RouteNames.reportsDashboard,
      path: RoutePaths.reportsDashboard,
      scope: AppMenuScope.company,
    ),
    '19002': AppMenuRouteSpec(
      menuCode: '19002',
      databaseRouteName: 'reportsHistory',
      goRouteName: RouteNames.reportsHistory,
      path: RoutePaths.reportsHistory,
      scope: AppMenuScope.company,
    ),
    '19003': AppMenuRouteSpec(
      menuCode: '19003',
      databaseRouteName: 'reportsSatisfaction',
      goRouteName: RouteNames.reportsSatisfaction,
      path: RoutePaths.reportsSatisfaction,
      scope: AppMenuScope.company,
    ),
    '20001': AppMenuRouteSpec(
      menuCode: '20001',
      databaseRouteName: 'portalRequest',
      goRouteName: RouteNames.portalRequest,
      path: RoutePaths.portalRequest,
      scope: AppMenuScope.company,
    ),
    '20002': AppMenuRouteSpec(
      menuCode: '20002',
      databaseRouteName: 'portalTracking',
      goRouteName: RouteNames.portalTracking,
      path: RoutePaths.portalTracking,
      scope: AppMenuScope.company,
    ),
    '20003': AppMenuRouteSpec(
      menuCode: '20003',
      databaseRouteName: 'portalHistory',
      goRouteName: RouteNames.portalHistory,
      path: RoutePaths.portalHistory,
      scope: AppMenuScope.company,
    ),
    '20004': AppMenuRouteSpec(
      menuCode: '20004',
      databaseRouteName: 'portalPmSchedule',
      goRouteName: RouteNames.portalPmSchedule,
      path: RoutePaths.portalPmSchedule,
      scope: AppMenuScope.company,
    ),
    '20005': AppMenuRouteSpec(
      menuCode: '20005',
      databaseRouteName: 'portalEvaluation',
      goRouteName: RouteNames.portalEvaluation,
      path: RoutePaths.portalEvaluation,
      scope: AppMenuScope.company,
    ),
    '20006': AppMenuRouteSpec(
      menuCode: '20006',
      databaseRouteName: 'portalComplaint',
      goRouteName: RouteNames.portalComplaint,
      path: RoutePaths.portalComplaint,
      scope: AppMenuScope.company,
    ),
    '10001': AppMenuRouteSpec(
      menuCode: '10001',
      databaseRouteName: 'companyEmployees',
      goRouteName: RouteNames.companyEmployees,
      path: RoutePaths.companyEmployees,
      scope: AppMenuScope.company,
    ),
    '10002': AppMenuRouteSpec(
      menuCode: '10002',
      databaseRouteName: 'companyUsers',
      goRouteName: RouteNames.companyUsers,
      path: RoutePaths.companyUsers,
      scope: AppMenuScope.company,
    ),
    '10003': AppMenuRouteSpec(
      menuCode: '10003',
      databaseRouteName: 'companyRoleGroups',
      goRouteName: RouteNames.companyRoleGroups,
      path: RoutePaths.companyRoleGroups,
      scope: AppMenuScope.company,
    ),
    '10004': AppMenuRouteSpec(
      menuCode: '10004',
      databaseRouteName: 'companyMenuPermissions',
      goRouteName: RouteNames.companyMenuPermissions,
      path: RoutePaths.companyMenuPermissions,
      scope: AppMenuScope.company,
    ),
    '10006': AppMenuRouteSpec(
      menuCode: '10006',
      databaseRouteName: 'companySubPermissions',
      goRouteName: RouteNames.companySubPermissions,
      path: RoutePaths.companySubPermissions,
      scope: AppMenuScope.company,
    ),
    '10005': AppMenuRouteSpec(
      menuCode: '10005',
      databaseRouteName: 'organizationStructure',
      goRouteName: RouteNames.organizationStructure,
      path: RoutePaths.organizationStructure,
      scope: AppMenuScope.company,
    ),
    '11001': AppMenuRouteSpec(
      menuCode: '11001',
      databaseRouteName: 'partnerEmployees',
      goRouteName: RouteNames.partnerEmployees,
      path: RoutePaths.partnerEmployees,
      scope: AppMenuScope.partner,
    ),
    '11002': AppMenuRouteSpec(
      menuCode: '11002',
      databaseRouteName: 'partnerUsers',
      goRouteName: RouteNames.partnerUsers,
      path: RoutePaths.partnerUsers,
      scope: AppMenuScope.partner,
    ),
    '11003': AppMenuRouteSpec(
      menuCode: '11003',
      databaseRouteName: 'partnerRoleGroups',
      goRouteName: RouteNames.partnerRoleGroups,
      path: RoutePaths.partnerRoleGroups,
      scope: AppMenuScope.partner,
    ),
    '11004': AppMenuRouteSpec(
      menuCode: '11004',
      databaseRouteName: 'partnerMenuPermissions',
      goRouteName: RouteNames.partnerMenuPermissions,
      path: RoutePaths.partnerMenuPermissions,
      scope: AppMenuScope.partner,
    ),
    '12001': AppMenuRouteSpec(
      menuCode: '12001',
      databaseRouteName: 'customerEmployees',
      goRouteName: RouteNames.customerEmployees,
      path: RoutePaths.customerEmployees,
      scope: AppMenuScope.partner,
    ),
    MeetingMenuCodes.bookings: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.bookings,
      databaseRouteName: 'meetingRoomBookings',
      goRouteName: RouteNames.meetingRoomBookings,
      path: RoutePaths.meetingRoomBookings,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.calendar: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.calendar,
      databaseRouteName: 'meetingRoomCalendar',
      goRouteName: RouteNames.meetingRoomCalendar,
      path: RoutePaths.meetingRoomCalendar,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.invitations: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.invitations,
      databaseRouteName: 'meetingInvitationRsvp',
      goRouteName: RouteNames.meetingInvitationRsvp,
      path: RoutePaths.meetingInvitationRsvp,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.approvals: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.approvals,
      databaseRouteName: 'meetingRoomApprovals',
      goRouteName: RouteNames.meetingRoomApprovals,
      path: RoutePaths.meetingRoomApprovals,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.foodPlans: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.foodPlans,
      databaseRouteName: 'meetingFoodPlans',
      goRouteName: RouteNames.meetingFoodPlans,
      path: RoutePaths.meetingFoodPlans,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.roomCheckIn: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.roomCheckIn,
      databaseRouteName: 'roomCheckIn',
      goRouteName: RouteNames.roomCheckIn,
      path: RoutePaths.roomCheckIn,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.roomSupportTasks: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.roomSupportTasks,
      databaseRouteName: 'roomSupportTasks',
      goRouteName: RouteNames.roomSupportTasks,
      path: RoutePaths.roomSupportTasks,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.roomIssues: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.roomIssues,
      databaseRouteName: 'roomIssues',
      goRouteName: RouteNames.roomIssues,
      path: RoutePaths.roomIssues,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.buildings: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.buildings,
      databaseRouteName: 'meetingBuildings',
      goRouteName: RouteNames.meetingBuildings,
      path: RoutePaths.meetingBuildings,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.rooms: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.rooms,
      databaseRouteName: 'meetingRooms',
      goRouteName: RouteNames.meetingRooms,
      path: RoutePaths.meetingRooms,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.foods: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.foods,
      databaseRouteName: 'meetingFoods',
      goRouteName: RouteNames.meetingFoods,
      path: RoutePaths.meetingFoods,
      scope: AppMenuScope.company,
    ),
    '10007': AppMenuRouteSpec(
      menuCode: '10007',
      databaseRouteName: 'companySupervisors',
      goRouteName: RouteNames.companySupervisors,
      path: RoutePaths.companySupervisors,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.utilizationReport: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.utilizationReport,
      databaseRouteName: 'meetingRoomUtilizationReport',
      goRouteName: RouteNames.meetingRoomUtilizationReport,
      path: RoutePaths.meetingRoomUtilizationReport,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.noShowReport: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.noShowReport,
      databaseRouteName: 'meetingNoShowReport',
      goRouteName: RouteNames.meetingNoShowReport,
      path: RoutePaths.meetingNoShowReport,
      scope: AppMenuScope.company,
    ),
    MeetingMenuCodes.feedbackReport: AppMenuRouteSpec(
      menuCode: MeetingMenuCodes.feedbackReport,
      databaseRouteName: 'meetingFeedbackReport',
      goRouteName: RouteNames.meetingFeedbackReport,
      path: RoutePaths.meetingFeedbackReport,
      scope: AppMenuScope.company,
    ),
    '12002': AppMenuRouteSpec(
      menuCode: '12002',
      databaseRouteName: 'laooUsers',
      goRouteName: RouteNames.laooUsers,
      path: RoutePaths.laooUsers,
      scope: AppMenuScope.support,
    ),
    '25002': AppMenuRouteSpec(
      menuCode: '25002',
      databaseRouteName: 'timeAttendanceResults',
      goRouteName: RouteNames.timeAttendanceResults,
      path: RoutePaths.timeAttendanceResults,
      scope: AppMenuScope.company,
    ),
    '37001': AppMenuRouteSpec(
      menuCode: '37001',
      databaseRouteName: 'trainingTypes',
      goRouteName: RouteNames.trainingTypes,
      path: RoutePaths.trainingTypes,
      scope: AppMenuScope.company,
    ),
    '37002': AppMenuRouteSpec(
      menuCode: '37002',
      databaseRouteName: 'trainingInstructors',
      goRouteName: RouteNames.trainingInstructors,
      path: RoutePaths.trainingInstructors,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.settings: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.settings,
      databaseRouteName: GatePassRouteNames.settings,
      goRouteName: GatePassRouteNames.settings,
      path: GatePassRoutePaths.settings,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.purposes: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.purposes,
      databaseRouteName: GatePassRouteNames.purposes,
      goRouteName: GatePassRouteNames.purposes,
      path: GatePassRoutePaths.purposes,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.requests: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.requests,
      databaseRouteName: GatePassRouteNames.requests,
      goRouteName: GatePassRouteNames.requests,
      path: GatePassRoutePaths.requests,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.approvalInbox: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.approvalInbox,
      databaseRouteName: GatePassRouteNames.approvalInbox,
      goRouteName: GatePassRouteNames.approvalInbox,
      path: GatePassRoutePaths.approvalInbox,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.exitCheck: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.exitCheck,
      databaseRouteName: GatePassRouteNames.exitCheck,
      goRouteName: GatePassRouteNames.exitCheck,
      path: GatePassRoutePaths.exitCheck,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.returnTracking: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.returnTracking,
      databaseRouteName: GatePassRouteNames.returnTracking,
      goRouteName: GatePassRouteNames.returnTracking,
      path: GatePassRoutePaths.returnTracking,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.myGatePasses: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.myGatePasses,
      databaseRouteName: GatePassRouteNames.myGatePasses,
      goRouteName: GatePassRouteNames.myGatePasses,
      path: GatePassRoutePaths.myGatePasses,
      scope: AppMenuScope.company,
    ),
    GatePassMenuCodes.reports: AppMenuRouteSpec(
      menuCode: GatePassMenuCodes.reports,
      databaseRouteName: GatePassRouteNames.reports,
      goRouteName: GatePassRouteNames.reports,
      path: GatePassRoutePaths.reports,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspectionAreas: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspectionAreas,
      databaseRouteName: FiveSRouteNames.inspectionAreas,
      goRouteName: FiveSRouteNames.inspectionAreas,
      path: FiveSRoutePaths.inspectionAreas,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.templates: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.templates,
      databaseRouteName: FiveSRouteNames.templates,
      goRouteName: FiveSRouteNames.templates,
      path: FiveSRoutePaths.templates,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspectionTeams: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspectionTeams,
      databaseRouteName: FiveSRouteNames.inspectionTeams,
      goRouteName: FiveSRouteNames.inspectionTeams,
      path: FiveSRoutePaths.inspectionTeams,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspectionPlans: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspectionPlans,
      databaseRouteName: FiveSRouteNames.inspectionPlans,
      goRouteName: FiveSRouteNames.inspectionPlans,
      path: FiveSRoutePaths.inspectionPlans,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspections: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspections,
      databaseRouteName: FiveSRouteNames.inspections,
      goRouteName: FiveSRouteNames.inspections,
      path: FiveSRoutePaths.inspections,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspectionConfirmations: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspectionConfirmations,
      databaseRouteName: FiveSRouteNames.inspectionConfirmations,
      goRouteName: FiveSRouteNames.inspectionConfirmations,
      path: FiveSRoutePaths.inspectionConfirmations,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.findings: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.findings,
      databaseRouteName: FiveSRouteNames.findings,
      goRouteName: FiveSRouteNames.findings,
      path: FiveSRoutePaths.findings,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.inspectionHistory: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.inspectionHistory,
      databaseRouteName: FiveSRouteNames.inspectionHistory,
      goRouteName: FiveSRouteNames.inspectionHistory,
      path: FiveSRoutePaths.inspectionHistory,
      scope: AppMenuScope.company,
    ),
    FiveSMenuCodes.reports: AppMenuRouteSpec(
      menuCode: FiveSMenuCodes.reports,
      databaseRouteName: FiveSRouteNames.reports,
      goRouteName: FiveSRouteNames.reports,
      path: FiveSRoutePaths.reports,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.settings: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.settings,
      databaseRouteName: SurveyRouteNames.settings,
      goRouteName: SurveyRouteNames.settings,
      path: SurveyRoutePaths.settings,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.questionnaires: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.questionnaires,
      databaseRouteName: SurveyRouteNames.questionnaires,
      goRouteName: SurveyRouteNames.questionnaires,
      path: SurveyRoutePaths.questionnaires,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.approvalInbox: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.approvalInbox,
      databaseRouteName: SurveyRouteNames.approvalInbox,
      goRouteName: SurveyRouteNames.approvalInbox,
      path: SurveyRoutePaths.approvalInbox,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.delivery: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.delivery,
      databaseRouteName: SurveyRouteNames.delivery,
      goRouteName: SurveyRouteNames.delivery,
      path: SurveyRoutePaths.delivery,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.results: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.results,
      databaseRouteName: SurveyRouteNames.results,
      goRouteName: SurveyRouteNames.results,
      path: SurveyRoutePaths.results,
      scope: AppMenuScope.company,
    ),
    SurveyMenuCodes.reports: AppMenuRouteSpec(
      menuCode: SurveyMenuCodes.reports,
      databaseRouteName: SurveyRouteNames.reports,
      goRouteName: SurveyRouteNames.reports,
      path: SurveyRoutePaths.reports,
      scope: AppMenuScope.company,
    ),
    IntranetMenuCodes.settings: AppMenuRouteSpec(
      menuCode: IntranetMenuCodes.settings,
      databaseRouteName: IntranetRouteNames.settings,
      goRouteName: IntranetRouteNames.settings,
      path: IntranetRoutePaths.settings,
      scope: AppMenuScope.company,
    ),
    IntranetMenuCodes.content: AppMenuRouteSpec(
      menuCode: IntranetMenuCodes.content,
      databaseRouteName: IntranetRouteNames.content,
      goRouteName: IntranetRouteNames.content,
      path: IntranetRoutePaths.content,
      scope: AppMenuScope.company,
    ),
    IntranetMenuCodes.approvalInbox: AppMenuRouteSpec(
      menuCode: IntranetMenuCodes.approvalInbox,
      databaseRouteName: IntranetRouteNames.approvalInbox,
      goRouteName: IntranetRouteNames.approvalInbox,
      path: IntranetRoutePaths.approvalInbox,
      scope: AppMenuScope.company,
    ),
    IntranetMenuCodes.myIntranet: AppMenuRouteSpec(
      menuCode: IntranetMenuCodes.myIntranet,
      databaseRouteName: IntranetRouteNames.myIntranet,
      goRouteName: IntranetRouteNames.myIntranet,
      path: IntranetRoutePaths.myIntranet,
      scope: AppMenuScope.company,
    ),
    IntranetMenuCodes.reports: AppMenuRouteSpec(
      menuCode: IntranetMenuCodes.reports,
      databaseRouteName: IntranetRouteNames.reports,
      goRouteName: IntranetRouteNames.reports,
      path: IntranetRoutePaths.reports,
      scope: AppMenuScope.company,
    ),    ExpenseMenuCodes.settings: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.settings,
      databaseRouteName: ExpenseRouteNames.settings,
      goRouteName: ExpenseRouteNames.settings,
      path: ExpenseRoutePaths.settings,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.categories: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.categories,
      databaseRouteName: ExpenseRouteNames.categories,
      goRouteName: ExpenseRouteNames.categories,
      path: ExpenseRoutePaths.categories,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.advances: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.advances,
      databaseRouteName: ExpenseRouteNames.advances,
      goRouteName: ExpenseRouteNames.advances,
      path: ExpenseRoutePaths.advances,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.claims: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.claims,
      databaseRouteName: ExpenseRouteNames.claims,
      goRouteName: ExpenseRouteNames.claims,
      path: ExpenseRoutePaths.claims,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.approvalInbox: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.approvalInbox,
      databaseRouteName: ExpenseRouteNames.approvalInbox,
      goRouteName: ExpenseRouteNames.approvalInbox,
      path: ExpenseRoutePaths.approvalInbox,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.settlements: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.settlements,
      databaseRouteName: ExpenseRouteNames.settlements,
      goRouteName: ExpenseRouteNames.settlements,
      path: ExpenseRoutePaths.settlements,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.myExpenses: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.myExpenses,
      databaseRouteName: ExpenseRouteNames.myExpenses,
      goRouteName: ExpenseRouteNames.myExpenses,
      path: ExpenseRoutePaths.myExpenses,
      scope: AppMenuScope.company,
    ),
    ExpenseMenuCodes.reports: AppMenuRouteSpec(
      menuCode: ExpenseMenuCodes.reports,
      databaseRouteName: ExpenseRouteNames.reports,
      goRouteName: ExpenseRouteNames.reports,
      path: ExpenseRoutePaths.reports,
      scope: AppMenuScope.company,
    ),
    ProjectMenuCodes.settings: AppMenuRouteSpec(
      menuCode: ProjectMenuCodes.settings,
      databaseRouteName: ProjectRouteNames.settings,
      goRouteName: ProjectRouteNames.settings,
      path: ProjectRoutePaths.settings,
      scope: AppMenuScope.company,
    ),
    ProjectMenuCodes.budgetCategories: AppMenuRouteSpec(
      menuCode: ProjectMenuCodes.budgetCategories,
      databaseRouteName: ProjectRouteNames.budgetCategories,
      goRouteName: ProjectRouteNames.budgetCategories,
      path: ProjectRoutePaths.budgetCategories,
      scope: AppMenuScope.company,
    ),
    ProjectMenuCodes.projects: AppMenuRouteSpec(
      menuCode: ProjectMenuCodes.projects,
      databaseRouteName: ProjectRouteNames.projects,
      goRouteName: ProjectRouteNames.projects,
      path: ProjectRoutePaths.projects,
      scope: AppMenuScope.company,
    ),
    ProjectMenuCodes.myTasks: AppMenuRouteSpec(
      menuCode: ProjectMenuCodes.myTasks,
      databaseRouteName: ProjectRouteNames.myTasks,
      goRouteName: ProjectRouteNames.myTasks,
      path: ProjectRoutePaths.myTasks,
      scope: AppMenuScope.company,
    ),
    ProjectMenuCodes.reports: AppMenuRouteSpec(
      menuCode: ProjectMenuCodes.reports,
      databaseRouteName: ProjectRouteNames.reports,
      goRouteName: ProjectRouteNames.reports,
      path: ProjectRoutePaths.reports,
      scope: AppMenuScope.company,
    ),
    '29001': AppMenuRouteSpec(
      menuCode: '29001',
      databaseRouteName: 'timeAttendancePeriodSchemes',
      goRouteName: RouteNames.timeAttendancePeriodSchemes,
      path: RoutePaths.timeAttendancePeriodSchemes,
      scope: AppMenuScope.company,
    ),
    '29002': AppMenuRouteSpec(
      menuCode: '29002',
      databaseRouteName: 'timeAttendancePeriodAssignments',
      goRouteName: RouteNames.timeAttendancePeriodAssignments,
      path: RoutePaths.timeAttendancePeriodAssignments,
      scope: AppMenuScope.company,
    ),
    '29003': AppMenuRouteSpec(
      menuCode: '29003',
      databaseRouteName: 'timeAttendancePeriods',
      goRouteName: RouteNames.timeAttendancePeriods,
      path: RoutePaths.timeAttendancePeriods,
      scope: AppMenuScope.company,
    ),
    '29004': AppMenuRouteSpec(
      menuCode: '29004',
      databaseRouteName: 'timeAttendanceSummaryReport',
      goRouteName: RouteNames.timeAttendanceSummaryReport,
      path: RoutePaths.timeAttendanceSummaryReport,
      scope: AppMenuScope.company,
    ),
    '28005': AppMenuRouteSpec(
      menuCode: '28005',
      databaseRouteName: 'timeHolidayCalendars',
      goRouteName: RouteNames.timeHolidayCalendars,
      path: RoutePaths.timeHolidayCalendars,
      scope: AppMenuScope.company,
    ),
    '28006': AppMenuRouteSpec(
      menuCode: '28006',
      databaseRouteName: 'timeHolidayDates',
      goRouteName: RouteNames.timeHolidayDates,
      path: RoutePaths.timeHolidayDates,
      scope: AppMenuScope.company,
    ),
    '28007': AppMenuRouteSpec(
      menuCode: '28007',
      databaseRouteName: 'timeBranchHolidayCalendars',
      goRouteName: RouteNames.timeBranchHolidayCalendars,
      path: RoutePaths.timeBranchHolidayCalendars,
      scope: AppMenuScope.company,
    ),
    '28008': AppMenuRouteSpec(
      menuCode: '28008',
      databaseRouteName: 'timeBranchHolidayExceptions',
      goRouteName: RouteNames.timeBranchHolidayExceptions,
      path: RoutePaths.timeBranchHolidayExceptions,
      scope: AppMenuScope.company,
    ),
    '28009': AppMenuRouteSpec(
      menuCode: '28009',
      databaseRouteName: 'timeLeaveTypes',
      goRouteName: RouteNames.timeLeaveTypes,
      path: RoutePaths.timeLeaveTypes,
      scope: AppMenuScope.company,
    ),
    '28010': AppMenuRouteSpec(
      menuCode: '28010',
      databaseRouteName: 'timeLeaveEntitlementPolicies',
      goRouteName: RouteNames.timeLeaveEntitlementPolicies,
      path: RoutePaths.timeLeaveEntitlementPolicies,
      scope: AppMenuScope.company,
    ),
    '28011': AppMenuRouteSpec(
      menuCode: '28011',
      databaseRouteName: 'timeLeaveBalances',
      goRouteName: RouteNames.timeLeaveBalances,
      path: RoutePaths.timeLeaveBalances,
      scope: AppMenuScope.company,
    ),
    '28013': AppMenuRouteSpec(
      menuCode: '28013',
      databaseRouteName: RouteNames.timePayrollExportProfiles,
      goRouteName: RouteNames.timePayrollExportProfiles,
      path: RoutePaths.timePayrollExportProfiles,
      scope: AppMenuScope.company,
    ),
    '25003': AppMenuRouteSpec(
      menuCode: '25003',
      databaseRouteName: RouteNames.timePayrollExport,
      goRouteName: RouteNames.timePayrollExport,
      path: RoutePaths.timePayrollExport,
      scope: AppMenuScope.company,
    ),
    '25004': AppMenuRouteSpec(
      menuCode: '25004',
      databaseRouteName: RouteNames.timePayrollExportHistory,
      goRouteName: RouteNames.timePayrollExportHistory,
      path: RoutePaths.timePayrollExportHistory,
      scope: AppMenuScope.company,
    ),
    '28012': AppMenuRouteSpec(
      menuCode: '28012',
      databaseRouteName: 'timeLeaveReport',
      goRouteName: 'timeLeaveReport',
      path: '/company/time-leave-report',
      scope: AppMenuScope.company,
    ),
    '26003': AppMenuRouteSpec(
      menuCode: '26003',
      databaseRouteName: 'timeLeaveRequests',
      goRouteName: RouteNames.timeLeaveRequests,
      path: RoutePaths.timeLeaveRequests,
      scope: AppMenuScope.company,
    ),
    '26004': AppMenuRouteSpec(
      menuCode: '26004',
      databaseRouteName: 'timeLeaveApprovalInbox',
      goRouteName: RouteNames.timeLeaveApprovalInbox,
      path: RoutePaths.timeLeaveApprovalInbox,
      scope: AppMenuScope.company,
    ),
    '30002': AppMenuRouteSpec(
      menuCode: '30002',
      databaseRouteName: 'myAttendanceHistory',
      goRouteName: RouteNames.myAttendanceHistory,
      path: RoutePaths.myAttendanceHistory,
      scope: AppMenuScope.company,
    ),
    '30003': AppMenuRouteSpec(
      menuCode: '30003',
      databaseRouteName: 'myLeaveRequests',
      goRouteName: RouteNames.myLeaveRequests,
      path: RoutePaths.myLeaveRequests,
      scope: AppMenuScope.company,
    ),
    '30004': AppMenuRouteSpec(
      menuCode: '30004',
      databaseRouteName: 'myLeaveBalance',
      goRouteName: RouteNames.myLeaveBalance,
      path: RoutePaths.myLeaveBalance,
      scope: AppMenuScope.company,
    ),
    for (final route in ServiceRoutes.all)
      route.menuCode: AppMenuRouteSpec(
        menuCode: route.menuCode,
        databaseRouteName: route.routeName,
        goRouteName: route.effectiveGoRouteName,
        path: route.routePath,
        scope: AppMenuScope.company,
      ),
    for (final route in MeetingRoutes.all)
      route.menuCode: AppMenuRouteSpec(
        menuCode: route.menuCode,
        databaseRouteName: route.name,
        goRouteName: route.name,
        path: route.path,
        scope: AppMenuScope.company,
      ),
    for (final route in VisitorRoutes.implemented)
      route.menuCode: AppMenuRouteSpec(
        menuCode: route.menuCode,
        databaseRouteName: route.routeName,
        goRouteName: route.effectiveGoRouteName,
        path: route.routePath,
        scope: AppMenuScope.company,
      ),
    for (final route in TimeRoutes.implemented)
      route.menuCode: AppMenuRouteSpec(
        menuCode: route.menuCode,
        databaseRouteName: route.routeName,
        goRouteName: route.effectiveGoRouteName,
        path: route.routePath,
        scope: AppMenuScope.company,
      ),
    for (final route in TrainingRoutes.all)
      route.menuCode: AppMenuRouteSpec(
        menuCode: route.menuCode,
        databaseRouteName: route.routeName,
        goRouteName: route.effectiveGoRouteName,
        path: route.routePath,
        scope: AppMenuScope.company,
      ),
  };

  static AppMenuRouteSpec? byMenuCode(String menuCode) =>
      _byMenuCode[menuCode.trim()];

  static Iterable<AppMenuRouteSpec> get all => _byMenuCode.values;

  static Iterable<AppMenuRouteSpec> byPath(String path) =>
      _byMenuCode.values.where((spec) => spec.path == path);

  static bool containsPath(String path) => byPath(path).isNotEmpty;
}
