using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
namespace Laoo.DigitalChecklist.Controllers;
public sealed partial class DigitalChecklistController
{
    [HttpGet("approver-users")]
    public async Task<IActionResult> ApproverUsers(CancellationToken ct) { await using var d = await Open(ct); if (await Guard(d, "58004", "VIEW", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); if (dep is null && !admin) return Forbid(); return Ok(await DigitalChecklistDb.Rows(d, "SELECT U.UserID id,E.FullName name,E.EmployeeCode code FROM dbo.TDADUserEmployee U JOIN dbo.TDADEmployee E ON E.CompanyID=U.CompanyID AND E.EmployeeID=U.EmployeeID JOIN dbo.TDADEmployeeOrganizationAssignment A ON A.CompanyID=E.CompanyID AND A.EmployeeID=E.EmployeeID AND A.IsActive=1 AND A.EffectiveFrom<=CONVERT(date,SYSUTCDATETIME()) AND (A.EffectiveTo IS NULL OR A.EffectiveTo>=CONVERT(date,SYSUTCDATETIME())) WHERE U.CompanyID=@co AND U.IsActive=1 AND E.IsActive=1 AND (@admin=1 OR A.DepartmentOrgUnitID=@dep) ORDER BY E.FullName", ct, ("@co", Company), ("@admin", admin), ("@dep", dep))); }
    [HttpPost("types")]
    public async Task<IActionResult> CreateType(MasterInput x, CancellationToken ct) { if (x.ParentId is null || string.IsNullOrWhiteSpace(x.Code) || string.IsNullOrWhiteSpace(x.Name)) return BadRequest(new { message = "กรุณาเลือกลุ่มและกรอกรหัสกับชื่อประเภท" }); await using var d = await Open(ct); if (await Guard(d, "58002", "CREATE", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); var allowed = await DigitalChecklistDb.Id(d, "SELECT COUNT(*) FROM dbo.TDCLGroup WHERE CompanyID=@co AND GroupID=@id AND (@admin=1 OR DepartmentOrgUnitID=@dep)", ct, ("@co", Company), ("@id", x.ParentId), ("@admin", admin), ("@dep", dep)); if (allowed == 0) return Forbid(); var id = await DigitalChecklistDb.Id(d, "INSERT dbo.TDCLType(CompanyID,GroupID,TypeCode,TypeName) OUTPUT INSERTED.TypeID VALUES(@co,@g,@code,@name)", ct, ("@co", Company), ("@g", x.ParentId), ("@code", x.Code.Trim()), ("@name", x.Name.Trim())); return Ok(new { id }); }
    [HttpGet("types")]
    public async Task<IActionResult> Types(CancellationToken ct) { await using var d = await Open(ct); if (await Guard(d, "58002", "VIEW", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); return Ok(await DigitalChecklistDb.Rows(d, "SELECT T.TypeID id,T.GroupID groupId,T.TypeCode code,T.TypeName name,G.DepartmentOrgUnitID departmentId FROM dbo.TDCLType T JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE T.CompanyID=@co AND (@admin=1 OR G.DepartmentOrgUnitID=@dep) ORDER BY T.TypeName", ct, ("@co", Company), ("@admin", admin), ("@dep", dep))); }
    [HttpGet("types/{typeId:long}/template-items")]
    public async Task<IActionResult> TemplateItems(long typeId, [FromQuery] long? scheduleId, CancellationToken ct)
    {
        await using var db = await Open(ct);
        if (await Guard(db, "58006", "VIEW", ct) is { } denied) return denied;
        var department = await Department(db, ct);
        var admin = await Admin(db, ct);
        const string sql = """
            SELECT I.ItemID id,I.ItemText text,T.TemplateID templateId
            FROM dbo.TDCLType Y
            JOIN dbo.TDCLGroup G ON G.CompanyID=Y.CompanyID AND G.GroupID=Y.GroupID
            JOIN dbo.TDCLTemplate T ON T.CompanyID=Y.CompanyID AND T.TypeID=Y.TypeID AND T.IsActive=1
            JOIN dbo.TDCLTemplateItem I ON I.CompanyID=T.CompanyID AND I.TemplateID=T.TemplateID
            WHERE Y.CompanyID=@co AND Y.TypeID=@type AND Y.IsActive=1 AND G.IsActive=1
              AND (@admin=1 OR G.DepartmentOrgUnitID=@dep)
              AND ((@schedule IS NULL AND T.TemplateID=
                    (SELECT TOP(1) V.TemplateID FROM dbo.TDCLTemplate V
                     WHERE V.CompanyID=@co AND V.TypeID=@type AND V.IsActive=1 ORDER BY V.TemplateID DESC))
                OR (@schedule IS NOT NULL AND EXISTS
                    (SELECT 1 FROM dbo.TDCLSchedule S WHERE S.CompanyID=@co
                     AND S.ScheduleID=@schedule AND S.TypeID=@type AND S.TemplateID=T.TemplateID)))
            ORDER BY I.SequenceNo
            """;
        return Ok(await DigitalChecklistDb.Rows(db, sql, ct,
            ("@co", Company), ("@type", typeId), ("@schedule", scheduleId),
            ("@admin", admin), ("@dep", department)));
    }
    [HttpPost("workflows")]
    public async Task<IActionResult> CreateWorkflow(MasterInput x, CancellationToken ct) { if (x.ParentId is null || string.IsNullOrWhiteSpace(x.Name)) return BadRequest(new { message = "กรุณาเลือกประเภทและชื่อสายอนุมัติ" }); List<long> users; try { users = JsonSerializer.Deserialize<List<long>>(x.Details ?? "[]") ?? []; } catch { return BadRequest(new { message = "รายชื่อผู้อนุมัติไม่ถูกต้อง" }); } if (users.Count == 0 || users.Distinct().Count() != users.Count) return BadRequest(new { message = "ต้องมีผู้อนุมัติไม่ซ้ำกันอย่างน้อยหนึ่งคน" }); await using var d = await Open(ct); if (await Guard(d, "58004", "CREATE", ct) is { } denied) return denied; var dep = await Department(d, ct); var all = await Admin(d, ct); if (await DigitalChecklistDb.Id(d, "SELECT COUNT(*) FROM dbo.TDCLType T JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE T.CompanyID=@co AND T.TypeID=@id AND (@admin=1 OR G.DepartmentOrgUnitID=@dep)", ct, ("@co", Company), ("@id", x.ParentId), ("@admin", all), ("@dep", dep)) == 0) return Forbid(); var json = JsonSerializer.Serialize(users); var id = await DigitalChecklistDb.Id(d, "BEGIN TRY BEGIN TRAN; IF EXISTS(SELECT 1 FROM dbo.TDCLWorkflow WHERE CompanyID=@co AND TypeID=@type AND IsActive=1) THROW 58012,'Active workflow already exists',1; IF EXISTS(SELECT 1 FROM OPENJSON(@users) WITH(UserID bigint '$') J LEFT JOIN dbo.TDADUser U ON U.CompanyID=@co AND U.UserID=J.UserID AND U.IsActive=1 WHERE U.UserID IS NULL) THROW 58013,'Approver unavailable',1; INSERT dbo.TDCLWorkflow(CompanyID,TypeID,WorkflowName) VALUES(@co,@type,@name); DECLARE @id bigint=SCOPE_IDENTITY(); INSERT dbo.TDCLWorkflowStep(CompanyID,WorkflowID,SequenceNo,ApproverUserID) SELECT @co,@id,CONVERT(int,[key])+1,CONVERT(bigint,value) FROM OPENJSON(@users); COMMIT; SELECT @id; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH", ct, ("@co", Company), ("@type", x.ParentId), ("@name", x.Name.Trim()), ("@users", json)); return Ok(new { id }); }
    [NonAction]
    public async Task<IActionResult> CreateSchedule(MasterInput x, CancellationToken ct) { if (x.ParentId is null || string.IsNullOrWhiteSpace(x.Frequency) || x.Frequency is not ("DAILY" or "WEEKLY" or "MONTHLY" or "YEARLY")) return BadRequest(new { message = "เลือกประเภทและความถี่รายวัน/สัปดาห์/เดือน/ปี" }); try { var times = JsonSerializer.Deserialize<List<string>>(x.TimesJson ?? "[]"); if (times is null || times.Count == 0 || times.Count > 12 || times.Any(t => !TimeOnly.TryParse(t, out _))) return BadRequest(new { message = "กำหนดเวลาอย่างน้อยหนึ่งช่วงและไม่เกิน 12 ช่วงต่อวัน" }); } catch { return BadRequest(new { message = "รูปแบบเวลาตรวจไม่ถูกต้อง" }); } await using var d = await Open(ct); if (await Guard(d, "58005", "CREATE", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); var id = await DigitalChecklistDb.Id(d, "BEGIN TRY BEGIN TRAN; DECLARE @group bigint=(SELECT G.GroupID FROM dbo.TDCLType T JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE T.CompanyID=@co AND T.TypeID=@type AND (@admin=1 OR G.DepartmentOrgUnitID=@dep)); DECLARE @template bigint=(SELECT TOP(1) TemplateID FROM dbo.TDCLTemplate WHERE CompanyID=@co AND TypeID=@type AND IsActive=1 ORDER BY TemplateID DESC); DECLARE @workflow bigint=(SELECT TOP(1) WorkflowID FROM dbo.TDCLWorkflow WHERE CompanyID=@co AND TypeID=@type AND IsActive=1 ORDER BY WorkflowID DESC); DECLARE @employee bigint=(SELECT TOP(1) EmployeeID FROM dbo.TDADUserEmployee WHERE CompanyID=@co AND UserID=@user AND IsActive=1); IF @group IS NULL OR @template IS NULL OR @workflow IS NULL OR @employee IS NULL THROW 58014,'Type, template, workflow or employee assignment missing',1; INSERT dbo.TDCLSchedule(CompanyID,TypeID,TemplateID,WorkflowID,ScheduleName,FrequencyCode,TimesJson,ResponsibleEmployeeID,StartsOn) VALUES(@co,@type,@template,@workflow,@name,@freq,@times,@employee,CONVERT(date,SYSUTCDATETIME())); COMMIT; SELECT SCOPE_IDENTITY(); END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH", ct, ("@co", Company), ("@type", x.ParentId), ("@admin", admin), ("@dep", dep), ("@user", Actor), ("@name", x.Name.Trim()), ("@freq", x.Frequency), ("@times", x.TimesJson)); return Ok(new { id }); }
    [HttpPost("master")]
    public async Task<IActionResult> SaveMaster(MasterInput x, CancellationToken ct)
    {
        if (x.MenuCode is null || !DigitalChecklistAccess.Menus.ContainsKey(x.MenuCode) || string.IsNullOrWhiteSpace(x.Name) || x.Name.Length > 150 || string.IsNullOrWhiteSpace(x.Code) || x.Code.Length > 30) return BadRequest(new { message = "กรุณาตรวจรหัสและชื่อ" }); await using var d = await Open(ct); if (await Guard(d, x.MenuCode, "CREATE", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); if (x.MenuCode == "58002") { var target = x.DepartmentId ?? dep; if (target is null || target <= 0 || (!admin && target != dep)) return Forbid(); if (await DigitalChecklistDb.Id(d, "SELECT COUNT(*) FROM dbo.TDADOrganizationUnit WHERE CompanyID=@co AND OrgUnitID=@id AND UnitType=N'DEP' AND IsActive=1", ct, ("@co", Company), ("@id", target)) == 0) return BadRequest(new { message = "แผนกไม่ถูกต้อง" }); var id = await DigitalChecklistDb.Id(d, "INSERT dbo.TDCLGroup(CompanyID,GroupCode,GroupName,DepartmentOrgUnitID) OUTPUT INSERTED.GroupID VALUES(@co,@code,@name,@dep)", ct, ("@co", Company), ("@code", x.Code.Trim()), ("@name", x.Name.Trim()), ("@dep", target)); return Ok(new { id }); }
        if (x.MenuCode == "58002" && x.ParentId is long groupId) { var allowed = await DigitalChecklistDb.Id(d, "SELECT COUNT(*) FROM dbo.TDCLGroup WHERE CompanyID=@co AND GroupID=@id AND (@admin=1 OR DepartmentOrgUnitID=@dep)", ct, ("@co", Company), ("@id", groupId), ("@admin", admin), ("@dep", dep)); if (allowed == 0) return Forbid(); var id = await DigitalChecklistDb.Id(d, "INSERT dbo.TDCLType(CompanyID,GroupID,TypeCode,TypeName) OUTPUT INSERTED.TypeID VALUES(@co,@group,@code,@name)", ct, ("@co", Company), ("@group", groupId), ("@code", x.Code.Trim()), ("@name", x.Name.Trim())); return Ok(new { id }); }
        if (x.ParentId is null) return BadRequest(new { message = "กรุณาเลือกกลุ่มหรือประเภทแม่" });
        if (x.MenuCode == "58003")
        {
            var type = await DigitalChecklistDb.Rows(d,
                "SELECT T.TypeID FROM dbo.TDCLType T JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE T.CompanyID=@co AND T.TypeID=@id AND T.IsActive=1 AND G.IsActive=1 AND (@admin=1 OR G.DepartmentOrgUnitID=@dep)",
                ct, ("@co", Company), ("@id", x.ParentId), ("@admin", admin), ("@dep", dep));
            if (type.Count == 0) return Forbid();
            var lines = (x.Details ?? "").Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (lines.Length == 0 || lines.Any(line => line.Length > 500))
                return BadRequest(new { message = "แบบตรวจต้องมีรายการอย่างน้อยหนึ่งข้อ และแต่ละข้อไม่เกิน 500 ตัวอักษร" });
            const string sql = """
                BEGIN TRY BEGIN TRAN;
                INSERT dbo.TDCLTemplate(CompanyID,TypeID,TemplateCode,TemplateName)
                VALUES(@co,@type,@code,@name);
                DECLARE @id bigint=SCOPE_IDENTITY();
                INSERT dbo.TDCLTemplateItem(CompanyID,TemplateID,SequenceNo,ItemText)
                SELECT @co,@id,CONVERT(int,[key])+1,CONVERT(nvarchar(500),value) FROM OPENJSON(@items);
                INSERT dbo.TDCLAudit(CompanyID,ActorUserID,ActionCode,EntityCode,EntityID,Detail)
                VALUES(@co,@actor,'CREATE','TEMPLATE',@id,@name);
                COMMIT; SELECT @id;
                END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH
                """;
            var id = await DigitalChecklistDb.Id(d, sql, ct,
                ("@co", Company), ("@type", x.ParentId), ("@code", x.Code.Trim()),
                ("@name", x.Name.Trim()), ("@items", JsonSerializer.Serialize(lines)), ("@actor", Actor));
            return Ok(new { id });
        }
        return BadRequest(new { message = "หน้าจอนี้ต้องใช้แบบฟอร์มเฉพาะ กรุณาเลือกประเภทข้อมูลให้ถูกต้อง" });
    }
    [NonAction]
    public async Task<IActionResult> SubmitInspection(InspectionInput x, CancellationToken ct) { if (x.Items.Count == 0 || x.Items.Any(i => i.ResultCode is not ("PASS" or "FAIL"))) return BadRequest(new { message = "กรุณาบันทึกผลตรวจทุกรายการ" }); await using var d = await Open(ct); if (await Guard(d, "58006", "CREATE", ct) is { } denied) return denied; var dep = await Department(d, ct); if (dep is null) return StatusCode(403, new { message = "ไม่พบแผนกปัจจุบัน กรุณาติดต่อผู้ดูแล" }); var type = await DigitalChecklistDb.Rows(d, "SELECT T.TypeID FROM dbo.TDCLType T JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE T.CompanyID=@co AND T.TypeID=@type AND G.DepartmentOrgUnitID=@dep AND T.IsActive=1", ct, ("@co", Company), ("@type", x.TypeId), ("@dep", dep)); if (type.Count == 0) return Forbid(); var items = JsonSerializer.Serialize(x.Items); var code = $"DCL-{DateTime.UtcNow:yyyyMMddHHmmss}-{Guid.NewGuid():N}"[..32]; var sql = "BEGIN TRY BEGIN TRAN; INSERT dbo.TDCLInspection(CompanyID,ScheduleID,TypeID,DepartmentOrgUnitID,InspectionCode,DueAt,StartedAt,SubmittedAt,StatusCode,SnapshotJson,CreatedBy) VALUES(@co,@schedule,@type,@dep,@code,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME(),'IN_APPROVAL',@snapshot,@actor); DECLARE @id bigint=SCOPE_IDENTITY(); INSERT dbo.TDCLInspectionItem(CompanyID,InspectionID,TemplateItemID,ResultCode,Detail) SELECT @co,@id,TemplateItemId,ResultCode,Detail FROM OPENJSON(@items) WITH(TemplateItemId bigint '$.TemplateItemId',ResultCode varchar(12) '$.ResultCode',Detail nvarchar(1000) '$.Detail'); INSERT dbo.TDCLApproval(CompanyID,InspectionID,GroupID,StepNo,ApproverUserID,StatusCode) SELECT @co,@id,G.GroupID,S.SequenceNo,S.ApproverUserID,CASE WHEN S.SequenceNo=1 THEN 'PENDING' ELSE 'WAITING' END FROM dbo.TDCLWorkflow W JOIN dbo.TDCLWorkflowStep S ON S.CompanyID=W.CompanyID AND S.WorkflowID=W.WorkflowID JOIN dbo.TDCLType T ON T.CompanyID=W.CompanyID AND T.TypeID=W.TypeID JOIN dbo.TDCLGroup G ON G.CompanyID=T.CompanyID AND G.GroupID=T.GroupID WHERE W.CompanyID=@co AND W.TypeID=@type AND W.IsActive=1; IF @@ROWCOUNT=0 THROW 58010,'Approval route not configured',1; COMMIT; SELECT @id; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH"; var id = await DigitalChecklistDb.Id(d, sql, ct, ("@co", Company), ("@schedule", x.ScheduleId), ("@type", x.TypeId), ("@dep", dep), ("@code", code), ("@snapshot", x.Note), ("@actor", Actor), ("@items", items)); return Ok(new { id, status = "IN_APPROVAL" }); }
    [NonAction]
    public async Task<IActionResult> ApproveGuarded(long id, DecisionInput x, CancellationToken ct) { await using var db = await Open(ct); if (await Guard(db, "58007", "APPROVE", ct) is { } denied) return denied; if (await DigitalChecklistDb.Id(db, "SELECT COUNT(*) FROM dbo.TDCLApproval A JOIN dbo.TDCLInspection I ON I.CompanyID=A.CompanyID AND I.InspectionID=A.InspectionID WHERE A.CompanyID=@co AND A.ApprovalID=@id AND A.ApproverUserID=@actor AND I.CreatedBy=@actor", ct, ("@co", Company), ("@id", id), ("@actor", Actor)) > 0) return Forbid(); return await Approve(id, x, ct); }
    [NonAction]
    public async Task<IActionResult> Approve(long id, DecisionInput x, CancellationToken ct) { await using var d = await Open(ct); if (await Guard(d, "58007", "APPROVE", ct) is { } denied) return denied; var sql = "BEGIN TRY BEGIN TRAN; UPDATE dbo.TDCLApproval SET StatusCode='APPROVED',DecisionNote=@note,DecidedAt=SYSUTCDATETIME() WHERE CompanyID=@co AND ApprovalID=@id AND ApproverUserID=@actor AND StatusCode='PENDING'; IF @@ROWCOUNT=0 THROW 58011,'Approval unavailable',1; DECLARE @inspection bigint=(SELECT InspectionID FROM dbo.TDCLApproval WHERE CompanyID=@co AND ApprovalID=@id); DECLARE @next int=(SELECT MIN(StepNo) FROM dbo.TDCLApproval WHERE CompanyID=@co AND InspectionID=@inspection AND StatusCode='WAITING'); IF @next IS NOT NULL UPDATE dbo.TDCLApproval SET StatusCode='PENDING' WHERE CompanyID=@co AND InspectionID=@inspection AND StepNo=@next; ELSE BEGIN UPDATE dbo.TDCLInspection SET StatusCode='APPROVED' WHERE CompanyID=@co AND InspectionID=@inspection; INSERT dbo.TDCLCorrectiveTask(CompanyID,InspectionID,InspectionItemID,TaskCode,Subject,Detail,StatusCode) SELECT @co,@inspection,II.InspectionItemID,CONCAT('DCL-',@inspection,'-',II.InspectionItemID),T.TypeName,II.Detail,'OPEN' FROM dbo.TDCLInspectionItem II JOIN dbo.TDCLInspection I ON I.CompanyID=II.CompanyID AND I.InspectionID=II.InspectionID JOIN dbo.TDCLType T ON T.CompanyID=I.CompanyID AND T.TypeID=I.TypeID WHERE II.CompanyID=@co AND II.InspectionID=@inspection AND II.ResultCode='FAIL'; END; COMMIT; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH"; await using var c = new SqlCommand(sql, d); c.Parameters.AddWithValue("@co", Company); c.Parameters.AddWithValue("@id", id); c.Parameters.AddWithValue("@actor", Actor); c.Parameters.AddWithValue("@note", x.Note ?? (object)DBNull.Value); await c.ExecuteNonQueryAsync(ct); return Ok(new { approved = true }); }
    [NonAction]
    public async Task<IActionResult> Return(long id, DecisionInput x, CancellationToken ct) { if (string.IsNullOrWhiteSpace(x.Note)) return BadRequest(new { message = "กรุณาระบุเหตุผลที่ส่งกลับ" }); await using var d = await Open(ct); if (await Guard(d, "58007", "RETURN", ct) is { } denied) return denied; await using var c = new SqlCommand("BEGIN TRY BEGIN TRAN; DECLARE @inspection bigint=(SELECT InspectionID FROM dbo.TDCLApproval WHERE CompanyID=@co AND ApprovalID=@id AND ApproverUserID=@actor AND StatusCode='PENDING'); IF @inspection IS NULL THROW 58015,'Approval unavailable',1; UPDATE dbo.TDCLApproval SET StatusCode='RETURNED',DecisionNote=@note,DecidedAt=SYSUTCDATETIME() WHERE CompanyID=@co AND InspectionID=@inspection AND StatusCode IN('PENDING','WAITING'); UPDATE dbo.TDCLInspection SET StatusCode='RETURNED' WHERE CompanyID=@co AND InspectionID=@inspection; COMMIT; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH", d); c.Parameters.AddWithValue("@co", Company); c.Parameters.AddWithValue("@id", id); c.Parameters.AddWithValue("@actor", Actor); c.Parameters.AddWithValue("@note", x.Note.Trim()); await c.ExecuteNonQueryAsync(ct); return Ok(new { returned = true }); }
    [HttpPost("corrective/{id:long}/status")]
    public async Task<IActionResult> UpdateTask(long id, TaskInput x, CancellationToken ct) { if (x.StatusCode is not ("OPEN" or "IN_PROGRESS" or "RESOLVED")) return BadRequest(new { message = "สถานะงานไม่ถูกต้อง" }); await using var d = await Open(ct); if (await Guard(d, "58008", "EDIT", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); var changed = await DigitalChecklistDb.Id(d, "UPDATE C SET StatusCode=@status,Detail=COALESCE(@detail,Detail),ClosedAt=CASE WHEN @status='RESOLVED' THEN SYSUTCDATETIME() ELSE NULL END OUTPUT INSERTED.TaskID FROM dbo.TDCLCorrectiveTask C JOIN dbo.TDCLInspection I ON I.CompanyID=C.CompanyID AND I.InspectionID=C.InspectionID WHERE C.CompanyID=@co AND C.TaskID=@id AND (@admin=1 OR I.DepartmentOrgUnitID=@dep)", ct, ("@status", x.StatusCode), ("@detail", x.Detail), ("@co", Company), ("@id", id), ("@admin", admin), ("@dep", dep)); return changed == 0 ? NotFound() : Ok(new { updated = true }); }
    [NonAction]
    public async Task<IActionResult> Handoff(long id, CancellationToken ct) { await using var d = await Open(ct); if (await Guard(d, "58008", "HANDOFF", ct) is { } denied) return denied; var dep = await Department(d, ct); var admin = await Admin(d, ct); var service = await DigitalChecklistDb.Id(d, "SELECT COUNT(*) FROM dbo.TDADCompanyProjectSubscription S JOIN dbo.TDADProject P ON P.ProjectID=S.ProjectID AND P.ProjectCode=N'LAOO_SERVICE' AND P.IsActive=1 WHERE S.CompanyID=@co AND S.IsCurrent=1 AND S.StatusCode IN(N'ACTIVE',N'TRIAL') AND (S.ExpireDate IS NULL OR S.ExpireDate>=CONVERT(date,SYSUTCDATETIME()))", ct, ("@co", Company)); if (service == 0) return Conflict(new { message = "บริษัทไม่ได้เปิดใช้ระบบแจ้งซ่อม งานยังคงอยู่ในคิวส่งต่อ" }); var request = await DigitalChecklistDb.Id(d, "BEGIN TRY BEGIN TRAN; DECLARE @task bigint,@subject nvarchar(200),@detail nvarchar(1000),@employee bigint,@employeeName nvarchar(200); SELECT @task=C.TaskID,@subject=C.Subject,@detail=C.Detail,@employee=U.EmployeeID,@employeeName=E.FullName FROM dbo.TDCLCorrectiveTask C JOIN dbo.TDCLInspection I ON I.CompanyID=C.CompanyID AND I.InspectionID=C.InspectionID JOIN dbo.TDADUserEmployee U ON U.CompanyID=C.CompanyID AND U.UserID=@actor AND U.IsActive=1 JOIN dbo.TDADEmployee E ON E.CompanyID=U.CompanyID AND E.EmployeeID=U.EmployeeID WHERE C.CompanyID=@co AND C.TaskID=@id AND (@admin=1 OR I.DepartmentOrgUnitID=@dep) AND C.ServiceHandoffStatus IN('PENDING','FAILED'); IF @task IS NULL THROW 58016,'Task unavailable',1; INSERT dbo.TDADServiceRequest(CompanyID,RequestNo,RequesterType,RequesterID,RequesterNameSnapshot,Subject,Detail,StatusCode,RequestDate,IsActive,CreateDate,CreateBy) VALUES(@co,CONCAT('DCL-',@task),'EMPLOYEE',@employee,@employeeName,@subject,COALESCE(@detail,N'ส่งต่อจาก Digital Checklist'),'NEW',SYSUTCDATETIME(),1,SYSUTCDATETIME(),@actor); DECLARE @request bigint=SCOPE_IDENTITY(); UPDATE dbo.TDCLCorrectiveTask SET ServiceHandoffStatus='SENT',ServiceTicketID=@request WHERE CompanyID=@co AND TaskID=@task; INSERT dbo.TDCLAudit(CompanyID,ActorUserID,ActionCode,EntityCode,EntityID,Detail) VALUES(@co,@actor,'HANDOFF','CORRECTIVE_TASK',@task,CONCAT('TDADServiceRequest:',@request)); COMMIT; SELECT @request; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH", ct, ("@co", Company), ("@id", id), ("@actor", Actor), ("@admin", admin), ("@dep", dep)); return Ok(new { serviceRequestId = request, status = "SENT" }); }
}
