using System.Data;
using System.Security.Claims;
using Laoo.Shared.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace LaooVoteModule.Controllers;

[ApiController, Authorize]
[Route("api/company/votes")]
public sealed class VoteController(IConfiguration configuration) : ControllerBase
{
    const string Settings = "44001", Topics = "44002", Approvals = "44003", Mine = "44004", Results = "44005";

    [HttpGet("settings")]
    public async Task<IActionResult> GetSettings(CancellationToken t) {
        if (!Scope(out var co, out _)) return Forbid(); await using var db=await Open(t); if(!await Can(db,Settings,"VIEW",t))return Forbid();
        await using var c=new SqlCommand("SELECT IsEnabled,DefaultOpenHours,DefaultApproverUserID FROM dbo.TDVTSetting WHERE CompanyID=@co",db); Add(c,"@co",SqlDbType.BigInt,co); await using var r=await c.ExecuteReaderAsync(t);
        return Ok(await r.ReadAsync(t)?new { isEnabled=r.GetBoolean(0),defaultOpenHours=r.GetInt32(1),defaultApproverUserId=r.IsDBNull(2)?(long?)null:r.GetInt64(2)}:new{isEnabled=true,defaultOpenHours=72,defaultApproverUserId=(long?)null});
    }

    [HttpPut("settings")]
    public async Task<IActionResult> SaveSettings(VoteSettingsRequest x,CancellationToken t) {
        if(!Scope(out var co,out var user))return Forbid(); if(x.DefaultOpenHours is <1 or >8760)return BadRequest(new{message="ข้อมูลไม่ถูกต้อง",description="ระยะเวลาเปิดโหวตต้องอยู่ระหว่าง 1 ถึง 8,760 ชั่วโมง"});
        await using var db=await Open(t);if(!await Can(db,Settings,"EDIT",t))return Forbid();
        if(x.DefaultApproverUserId is not null&&!await CompanyUser(db,co,x.DefaultApproverUserId.Value,t))return BadRequest(new{message="ผู้อนุมัติไม่ถูกต้อง",description="ผู้อนุมัติต้องเป็นผู้ใช้ที่ active ในบริษัทเดียวกัน"});
        await using var c=new SqlCommand("MERGE dbo.TDVTSetting AS T USING(SELECT @co CompanyID) S ON T.CompanyID=S.CompanyID WHEN MATCHED THEN UPDATE SET IsEnabled=@on,DefaultOpenHours=@hours,DefaultApproverUserID=@approver,UpdateDate=SYSUTCDATETIME(),UpdateBy=@user WHEN NOT MATCHED THEN INSERT(CompanyID,IsEnabled,DefaultOpenHours,DefaultApproverUserID,UpdateBy) VALUES(@co,@on,@hours,@approver,@user);",db);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@on",SqlDbType.Bit,x.IsEnabled);Add(c,"@hours",SqlDbType.Int,x.DefaultOpenHours);Add(c,"@approver",SqlDbType.BigInt,x.DefaultApproverUserId);Add(c,"@user",SqlDbType.BigInt,user);await c.ExecuteNonQueryAsync(t);return NoContent();
    }

    [HttpGet("actions")]
    public async Task<IActionResult> TopicActions(CancellationToken t) { if(!Scope(out _,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Topics,"VIEW",t))return Forbid();return Ok(new { screenType=4,view=true,create=await Can(db,Topics,"CREATE",t),edit=await Can(db,Topics,"EDIT",t),delete=await Can(db,Topics,"DELETE",t),submit=await Can(db,Topics,"SUBMIT",t),publish=await Can(db,Topics,"PUBLISH",t),close=await Can(db,Topics,"CLOSE",t)}); }

    [HttpGet("target-options")]
    public async Task<IActionResult> TargetOptions([FromQuery]string? search, CancellationToken t) {
        if(!Scope(out var co,out _)) return Forbid(); await using var db=await Open(t); if(!await Can(db,Topics,"VIEW",t)) return Forbid();
        var like=$"%{search?.Trim()??string.Empty}%";
        await using var c=new SqlCommand("""SELECT TOP 100 OrgUnitID,OrgUnitName FROM dbo.TDADOrganizationUnit WHERE CompanyID=@co AND UnitType=N'DEP' AND IsActive=1 AND (@q=N'' OR OrgUnitName LIKE @like) ORDER BY OrgUnitName; SELECT TOP 100 E.EmployeeID,E.EmployeeCode,E.EmployeeName FROM dbo.TDADEmployee E WHERE E.CompanyID=@co AND E.IsActive=1 AND (@q=N'' OR E.EmployeeCode LIKE @like OR E.EmployeeName LIKE @like) ORDER BY E.EmployeeName;""",db);
        Add(c,"@co",SqlDbType.BigInt,co); Add(c,"@q",SqlDbType.NVarChar,search?.Trim()??string.Empty,300); Add(c,"@like",SqlDbType.NVarChar,like,310);
        var departments=new List<object>(); var employees=new List<object>(); await using var r=await c.ExecuteReaderAsync(t);
        while(await r.ReadAsync(t)) departments.Add(new{id=r.GetInt64(0),name=r.GetString(1)});
        await r.NextResultAsync(t); while(await r.ReadAsync(t)) employees.Add(new{id=r.GetInt64(0),code=r.GetString(1),name=r.GetString(2)});
        return Ok(new { departments, employees });
    }

    [HttpGet]
    public async Task<IActionResult> List([FromQuery]string? search,[FromQuery]string? status,[FromQuery]int page=1,[FromQuery]int pageSize=20,CancellationToken t=default) {
        if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Topics,"VIEW",t))return Forbid();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);
        const string where="T.CompanyID=@co AND (@status IS NULL OR T.StatusCode=@status) AND (@search=N'' OR T.VoteNo LIKE @like OR T.TopicName LIKE @like)";
        await using var c=new SqlCommand($"""SELECT T.VoteTopicID,T.VoteNo,T.TopicName,T.StatusCode,T.OpenDateTime,T.CloseDateTime,T.TargetMode,T.IdentityMode,COUNT(V.VoteTopicVoterID),SUM(CASE WHEN V.VotedAt IS NULL THEN 0 ELSE 1 END) FROM dbo.TDVTTopic T LEFT JOIN dbo.TDVTTopicVoter V ON V.VoteTopicID=T.VoteTopicID WHERE {where} GROUP BY T.VoteTopicID,T.VoteNo,T.TopicName,T.StatusCode,T.OpenDateTime,T.CloseDateTime,T.TargetMode,T.IdentityMode ORDER BY CASE WHEN T.StatusCode=N'PUBLISHED' THEN 0 ELSE 1 END,T.OpenDateTime DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY; SELECT COUNT_BIG(*) FROM dbo.TDVTTopic T WHERE {where};""",db);BindList(c,co,search,status,page,pageSize);var rows=new List<object>();await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))rows.Add(new{id=r.GetInt64(0),voteNo=r.GetString(1),name=r.GetString(2),status=EffectiveStatus(r.GetString(3),r.GetDateTime(5)),openAt=r.GetDateTime(4),closeAt=r.GetDateTime(5),targetMode=r.GetString(6),identityMode=r.GetString(7),eligible=r.GetInt32(8),voted=r.IsDBNull(9)?0:r.GetInt32(9)});await r.NextResultAsync(t);var total=await r.ReadAsync(t)?r.GetInt64(0):0;return Ok(new{items=rows,total,page,pageSize});
    }

    [HttpGet("{id:long}")]
    public async Task<IActionResult> Get(long id,CancellationToken t) { if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Topics,"VIEW",t))return Forbid();return await Topic(db,co,id,t) is { } x?Ok(x):NotFound(); }
    [HttpPost] public Task<IActionResult> Create(VoteTopicRequest x,CancellationToken t)=>Save(null,x,t);
    [HttpPut("{id:long}")] public Task<IActionResult> Update(long id,VoteTopicRequest x,CancellationToken t)=>Save(id,x,t);

    [HttpDelete("{id:long}")]
    public async Task<IActionResult> Delete(long id,CancellationToken t) {if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Topics,"DELETE",t))return Forbid();await using var c=new SqlCommand("DELETE dbo.TDVTTopic WHERE VoteTopicID=@id AND CompanyID=@co AND StatusCode=N'DRAFT'",db);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@co",SqlDbType.BigInt,co);return await c.ExecuteNonQueryAsync(t)==1?NoContent():Conflict(new{message="ลบไม่ได้",description="ลบได้เฉพาะหัวข้อร่างเท่านั้น"});}

    [HttpPost("{id:long}/submit")]
    public Task<IActionResult> Submit(long id,CancellationToken t)=>Change(id,"SUBMIT",Topics,"PENDING_APPROVAL",null,t);
    [HttpPost("{id:long}/publish")]
    public async Task<IActionResult> Publish(long id,CancellationToken t) {if(!Scope(out var co,out var user))return Forbid();await using var db=await Open(t);if(!await Can(db,Topics,"PUBLISH",t))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);try {await using var state=new SqlCommand("UPDATE dbo.TDVTTopic SET StatusCode=N'PUBLISHED',PublishDate=SYSUTCDATETIME(),PublishBy=@u,UpdateDate=SYSUTCDATETIME(),UpdateBy=@u WHERE VoteTopicID=@id AND CompanyID=@co AND StatusCode=N'APPROVED';",db,tx);Add(state,"@id",SqlDbType.BigInt,id);Add(state,"@co",SqlDbType.BigInt,co);Add(state,"@u",SqlDbType.BigInt,user);if(await state.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return Conflict(new{message="เผยแพร่ไม่ได้",description="หัวข้อต้องผ่านอนุมัติก่อน"});}await FreezeVoters(db,tx,co,id,t);await Audit(db,tx,co,id,"PUBLISH",null,user,t);await tx.CommitAsync(t);return NoContent();}catch{await tx.RollbackAsync(t);throw;} }
    [HttpPost("{id:long}/close")] public Task<IActionResult> Close(long id,CancellationToken t)=>Change(id,"CLOSE",Topics,"CLOSED",null,t);

    [HttpGet("approvals")]
    public async Task<IActionResult> ApprovalList([FromQuery]int page=1,[FromQuery]int pageSize=20,CancellationToken t=default) {if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Approvals,"VIEW",t))return Forbid();return await ApprovalRows(db,co,page,pageSize,t);}
    [HttpPost("{id:long}/approval")]
    public async Task<IActionResult> Approve(long id,ApprovalRequest x,CancellationToken t) {var action=x.Action?.Trim().ToUpperInvariant();if(action is not("APPROVE" or "RETURN"))return BadRequest(new{message="คำสั่งไม่ถูกต้อง"});if(action=="RETURN"&&string.IsNullOrWhiteSpace(x.Remark))return BadRequest(new{message="กรุณาระบุเหตุผลส่งกลับแก้ไข"});return await Change(id,action,Approvals,action=="APPROVE"?"APPROVED":"RETURNED",x.Remark,t);}

    [HttpGet("mine")]
    public async Task<IActionResult> MyVotes(CancellationToken t) {if(!Scope(out var co,out var user))return Forbid();await using var db=await Open(t);if(!await Can(db,Mine,"VIEW",t))return Forbid();await using var c=new SqlCommand("SELECT T.VoteTopicID,T.VoteNo,T.TopicName,T.Description,T.OpenDateTime,T.CloseDateTime,V.VotedAt FROM dbo.TDVTTopicVoter V JOIN dbo.TDVTTopic T ON T.VoteTopicID=V.VoteTopicID WHERE V.CompanyID=@co AND V.UserID=@u AND T.StatusCode=N'PUBLISHED' AND SYSUTCDATETIME() BETWEEN T.OpenDateTime AND T.CloseDateTime ORDER BY T.CloseDateTime",db);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@u",SqlDbType.BigInt,user);return Ok(new{items=await ReadMine(c,t)});}
    [HttpPost("mine/{id:long}/vote")]
    public async Task<IActionResult> Vote(long id,VoteRequest x,CancellationToken t) {if(!Scope(out var co,out var user))return Forbid();await using var db=await Open(t);if(!await Can(db,Mine,"VOTE",t))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);try{const string sql="""INSERT dbo.TDVTVote(CompanyID,VoteTopicID,VoteTopicVoterID,VoteTopicOptionID) SELECT @co,T.VoteTopicID,V.VoteTopicVoterID,@opt FROM dbo.TDVTTopic T JOIN dbo.TDVTTopicVoter V ON V.VoteTopicID=T.VoteTopicID AND V.UserID=@u LEFT JOIN dbo.TDVTTopicOption O ON O.VoteTopicOptionID=@opt AND O.VoteTopicID=T.VoteTopicID WHERE T.VoteTopicID=@id AND T.CompanyID=@co AND T.StatusCode=N'PUBLISHED' AND SYSUTCDATETIME() BETWEEN T.OpenDateTime AND T.CloseDateTime AND V.VotedAt IS NULL AND O.VoteTopicOptionID IS NOT NULL; UPDATE V SET VotedAt=SYSUTCDATETIME() FROM dbo.TDVTTopicVoter V WHERE V.VoteTopicID=@id AND V.CompanyID=@co AND V.UserID=@u AND EXISTS(SELECT 1 FROM dbo.TDVTVote X WHERE X.VoteTopicVoterID=V.VoteTopicVoterID);""";await using var c=new SqlCommand(sql,db,tx);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@u",SqlDbType.BigInt,user);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@opt",SqlDbType.BigInt,x.OptionId);if(await c.ExecuteNonQueryAsync(t)<1){await tx.RollbackAsync(t);return Conflict(new{message="ลงคะแนนไม่ได้",description="หมดเวลา ไม่มีสิทธิ์ หรือเคยลงคะแนนแล้ว"});}await tx.CommitAsync(t);return NoContent();}catch(SqlException e)when(e.Number is 2601 or 2627){await tx.RollbackAsync(t);return Conflict(new{message="ลงคะแนนซ้ำไม่ได้"});}catch{await tx.RollbackAsync(t);throw;}}

    [HttpGet("results/dashboard")]
    public async Task<IActionResult> Dashboard(CancellationToken t) {if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Results,"VIEW",t))return Forbid();await using var c=new SqlCommand("SELECT SUM(CASE WHEN StatusCode=N'PUBLISHED' AND CloseDateTime>SYSUTCDATETIME() THEN 1 ELSE 0 END),SUM(CASE WHEN StatusCode=N'CLOSED' OR CloseDateTime<=SYSUTCDATETIME() THEN 1 ELSE 0 END),SUM(CASE WHEN StatusCode=N'PENDING_APPROVAL' THEN 1 ELSE 0 END),COUNT(DISTINCT V.VoteTopicVoterID),SUM(CASE WHEN V.VotedAt IS NULL THEN 0 ELSE 1 END) FROM dbo.TDVTTopic T LEFT JOIN dbo.TDVTTopicVoter V ON V.VoteTopicID=T.VoteTopicID WHERE T.CompanyID=@co",db);Add(c,"@co",SqlDbType.BigInt,co);await using var r=await c.ExecuteReaderAsync(t);await r.ReadAsync(t);var eligible=r.IsDBNull(3)?0:r.GetInt32(3);var voted=r.IsDBNull(4)?0:r.GetInt32(4);return Ok(new{open=r.IsDBNull(0)?0:r.GetInt32(0),closed=r.IsDBNull(1)?0:r.GetInt32(1),pendingApproval=r.IsDBNull(2)?0:r.GetInt32(2),eligible,voted,turnout=eligible==0?0:Math.Round(100m*voted/eligible,1)});}
    [HttpGet("results/{id:long}")]
    public async Task<IActionResult> Result(long id,CancellationToken t) {if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Results,"VIEW",t))return Forbid();var topic=await Topic(db,co,id,t);if(topic is null)return NotFound();await using var state=new SqlCommand("SELECT StatusCode,CloseDateTime FROM dbo.TDVTTopic WHERE VoteTopicID=@id AND CompanyID=@co",db);Add(state,"@id",SqlDbType.BigInt,id);Add(state,"@co",SqlDbType.BigInt,co);await using var stateReader=await state.ExecuteReaderAsync(t);if(!await stateReader.ReadAsync(t))return NotFound();if(stateReader.GetString(0)!="CLOSED"&&stateReader.GetDateTime(1)>DateTime.UtcNow)return Conflict(new{message="ยังไม่แสดงผล",description="ผลโหวตจะแสดงได้เมื่อปิดรอบหรือครบกำหนดเวลาปิดแล้ว"});await stateReader.DisposeAsync();await using var c=new SqlCommand("SELECT O.VoteTopicOptionID,O.OptionText,COUNT(X.VoteID) Votes FROM dbo.TDVTTopicOption O LEFT JOIN dbo.TDVTVote X ON X.VoteTopicOptionID=O.VoteTopicOptionID WHERE O.VoteTopicID=@id AND O.CompanyID=@co GROUP BY O.VoteTopicOptionID,O.OptionText,O.SortOrder ORDER BY O.SortOrder",db);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@co",SqlDbType.BigInt,co);var options=new List<object>();await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))options.Add(new{id=r.GetInt64(0),text=r.GetString(1),votes=r.GetInt32(2)});return Ok(new{topic,options});}

    async Task<IActionResult> Save(long? id,VoteTopicRequest x,CancellationToken t) {if(!Scope(out var co,out var user))return Forbid();var err=Validate(x);if(err is not null)return BadRequest(new{message="ข้อมูลหัวข้อโหวตไม่ถูกต้อง",description=err});await using var db=await Open(t);if(!await Can(db,Topics,id is null?"CREATE":"EDIT",t))return Forbid();if(!await TargetsValid(db,co,x,t))return BadRequest(new{message="กลุ่มผู้มีสิทธิ์ไม่ถูกต้อง",description="พนักงานหรือแผนกต้อง active และอยู่บริษัทเดียวกัน"});await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);try{long topic=id??0;if(id is null){await using var c=new SqlCommand("INSERT dbo.TDVTTopic(CompanyID,VoteNo,TopicName,Description,TargetMode,IdentityMode,OpenDateTime,CloseDateTime,CreateBy) VALUES(@co,N'VT'+FORMAT(SYSUTCDATETIME(),'yyyyMMddHHmmss')+RIGHT(REPLACE(CONVERT(nvarchar(36),NEWID()),N'-',N''),4),@name,@desc,@target,@identity,@open,@close,@u);SELECT SCOPE_IDENTITY();",db,tx);BindTopic(c,co,user,x);topic=Convert.ToInt64(await c.ExecuteScalarAsync(t));}else{await using var c=new SqlCommand("UPDATE dbo.TDVTTopic SET TopicName=@name,Description=@desc,TargetMode=@target,IdentityMode=@identity,OpenDateTime=@open,CloseDateTime=@close,UpdateDate=SYSUTCDATETIME(),UpdateBy=@u WHERE VoteTopicID=@id AND CompanyID=@co AND StatusCode IN(N'DRAFT',N'RETURNED');SELECT @@ROWCOUNT;",db,tx);BindTopic(c,co,user,x);Add(c,"@id",SqlDbType.BigInt,id);if(Convert.ToInt32(await c.ExecuteScalarAsync(t))!=1){await tx.RollbackAsync(t);return Conflict(new{message="แก้ไขไม่ได้",description="แก้ไขได้เฉพาะร่างหรือรายการที่ส่งกลับ"});}await using var del=new SqlCommand("DELETE dbo.TDVTTopicOption WHERE VoteTopicID=@id;DELETE dbo.TDVTTopicTarget WHERE VoteTopicID=@id;",db,tx);Add(del,"@id",SqlDbType.BigInt,topic);await del.ExecuteNonQueryAsync(t);}foreach(var o in x.Options!.Select((v,i)=>(v,i))){await using var c=new SqlCommand("INSERT dbo.TDVTTopicOption(CompanyID,VoteTopicID,OptionText,SortOrder) VALUES(@co,@id,@text,@sort)",db,tx);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@id",SqlDbType.BigInt,topic);Add(c,"@text",SqlDbType.NVarChar,o.v.Trim(),500);Add(c,"@sort",SqlDbType.Int,o.i+1);await c.ExecuteNonQueryAsync(t);}foreach(var target in x.Targets??[]){await using var c=new SqlCommand("INSERT dbo.TDVTTopicTarget(CompanyID,VoteTopicID,TargetType,TargetID) VALUES(@co,@id,@type,@target)",db,tx);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@id",SqlDbType.BigInt,topic);Add(c,"@type",SqlDbType.NVarChar,target.Type.Trim().ToUpperInvariant(),20);Add(c,"@target",SqlDbType.BigInt,target.Id);await c.ExecuteNonQueryAsync(t);}await Audit(db,tx,co,topic,id is null?"CREATE":"EDIT",null,user,t);await tx.CommitAsync(t);return Ok(new{id=topic});}catch{await tx.RollbackAsync(t);throw;}}
    async Task<IActionResult> Change(long id,string action,string menu,string status,string? remark,CancellationToken t){if(!Scope(out var co,out var user))return Forbid();await using var db=await Open(t);if(!await Can(db,menu,action,t))return Forbid();var required=action=="SUBMIT"?"DRAFT_OR_RETURNED":action=="APPROVE"?"PENDING_APPROVAL":action=="RETURN"?"PENDING_APPROVAL":action=="CLOSE"?"PUBLISHED":"";var stateFilter=required=="DRAFT_OR_RETURNED"?"StatusCode IN(N'DRAFT',N'RETURNED')":"StatusCode=@required";await using var tx=(SqlTransaction)await db.BeginTransactionAsync(t);try{await using var c=new SqlCommand($"UPDATE dbo.TDVTTopic SET StatusCode=@status,SubmitDate=CASE WHEN @action=N'SUBMIT' THEN SYSUTCDATETIME() ELSE SubmitDate END,SubmitBy=CASE WHEN @action=N'SUBMIT' THEN @u ELSE SubmitBy END,ApproveDate=CASE WHEN @action=N'APPROVE' THEN SYSUTCDATETIME() ELSE ApproveDate END,ApproveBy=CASE WHEN @action=N'APPROVE' THEN @u ELSE ApproveBy END,UpdateDate=SYSUTCDATETIME(),UpdateBy=@u WHERE VoteTopicID=@id AND CompanyID=@co AND {stateFilter};",db,tx);Add(c,"@status",SqlDbType.NVarChar,status,30);Add(c,"@action",SqlDbType.NVarChar,action,30);Add(c,"@u",SqlDbType.BigInt,user);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@co",SqlDbType.BigInt,co);if(required!="DRAFT_OR_RETURNED")Add(c,"@required",SqlDbType.NVarChar,required,30);if(await c.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return Conflict(new{message="เปลี่ยนสถานะไม่ได้",description="สถานะปัจจุบันไม่รองรับรายการนี้"});}await Audit(db,tx,co,id,action,remark,user,t);await tx.CommitAsync(t);return NoContent();}catch{await tx.RollbackAsync(t);throw;}}
    async Task FreezeVoters(SqlConnection db,SqlTransaction tx,long co,long topic,CancellationToken t){await using var c=new SqlCommand("""DECLARE @mode nvarchar(20)=(SELECT TargetMode FROM dbo.TDVTTopic WHERE VoteTopicID=@id AND CompanyID=@co); INSERT dbo.TDVTTopicVoter(CompanyID,VoteTopicID,UserID,EmployeeID) SELECT DISTINCT @co,@id,U.UserID,UE.EmployeeID FROM dbo.TDADUser U JOIN dbo.TDADUserEmployee UE ON UE.CompanyID=U.CompanyID AND UE.UserID=U.UserID AND UE.IsActive=1 JOIN dbo.TDADEmployee E ON E.CompanyID=UE.CompanyID AND E.EmployeeID=UE.EmployeeID AND E.IsActive=1 WHERE U.CompanyID=@co AND U.IsActive=1 AND (@mode=N'ALL' OR EXISTS(SELECT 1 FROM dbo.TDVTTopicTarget TT WHERE TT.VoteTopicID=@id AND ((TT.TargetType=N'EMPLOYEE' AND TT.TargetID=E.EmployeeID) OR (TT.TargetType=N'DEPARTMENT' AND TT.TargetID=E.DepartmentOrgUnitID))));""",db,tx);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@id",SqlDbType.BigInt,topic);await c.ExecuteNonQueryAsync(t);}
    async Task<object?> Topic(SqlConnection db,long co,long id,CancellationToken t){await using var c=new SqlCommand("SELECT VoteTopicID,VoteNo,TopicName,Description,TargetMode,IdentityMode,StatusCode,OpenDateTime,CloseDateTime,CreateBy FROM dbo.TDVTTopic WHERE VoteTopicID=@id AND CompanyID=@co;SELECT VoteTopicOptionID,OptionText,SortOrder FROM dbo.TDVTTopicOption WHERE VoteTopicID=@id ORDER BY SortOrder;SELECT TargetType,TargetID FROM dbo.TDVTTopicTarget WHERE VoteTopicID=@id;",db);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@co",SqlDbType.BigInt,co);await using var r=await c.ExecuteReaderAsync(t);if(!await r.ReadAsync(t))return null;var x=new {id=r.GetInt64(0),voteNo=r.GetString(1),name=r.GetString(2),description=r.IsDBNull(3)?null:r.GetString(3),targetMode=r.GetString(4),identityMode=r.GetString(5),status=EffectiveStatus(r.GetString(6),r.GetDateTime(8)),openAt=r.GetDateTime(7),closeAt=r.GetDateTime(8),createBy=r.GetInt64(9)};var options=new List<object>();await r.NextResultAsync(t);while(await r.ReadAsync(t))options.Add(new{id=r.GetInt64(0),text=r.GetString(1),sortOrder=r.GetInt32(2)});var targets=new List<object>();await r.NextResultAsync(t);while(await r.ReadAsync(t))targets.Add(new{type=r.GetString(0),id=r.GetInt64(1)});return new {topic=x,options,targets};}
    async Task<IActionResult> ApprovalRows(SqlConnection db,long co,int page,int pageSize,CancellationToken t){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);await using var c=new SqlCommand("SELECT VoteTopicID,VoteNo,TopicName,OpenDateTime,CloseDateTime FROM dbo.TDVTTopic WHERE CompanyID=@co AND StatusCode=N'PENDING_APPROVAL' ORDER BY SubmitDate OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY;SELECT COUNT_BIG(*) FROM dbo.TDVTTopic WHERE CompanyID=@co AND StatusCode=N'PENDING_APPROVAL'",db);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@skip",SqlDbType.Int,(page-1)*pageSize);Add(c,"@take",SqlDbType.Int,pageSize);var a=new List<object>();await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))a.Add(new{id=r.GetInt64(0),voteNo=r.GetString(1),name=r.GetString(2),openAt=r.GetDateTime(3),closeAt=r.GetDateTime(4)});await r.NextResultAsync(t);var total=await r.ReadAsync(t)?r.GetInt64(0):0;return Ok(new{items=a,total,page,pageSize});}
    static async Task<List<object>> ReadMine(SqlCommand c,CancellationToken t){var x=new List<object>();await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))x.Add(new{id=r.GetInt64(0),voteNo=r.GetString(1),name=r.GetString(2),description=r.IsDBNull(3)?null:r.GetString(3),openAt=r.GetDateTime(4),closeAt=r.GetDateTime(5),votedAt=r.IsDBNull(6)?(DateTime?)null:r.GetDateTime(6)});return x;}
    async Task<bool> TargetsValid(SqlConnection db,long co,VoteTopicRequest x,CancellationToken t){if(x.TargetMode.Trim().ToUpperInvariant()=="ALL")return true;if(x.Targets is null||x.Targets.Count==0)return false;foreach(var y in x.Targets){var type=y.Type.Trim().ToUpperInvariant();var sql=type=="EMPLOYEE"?"SELECT COUNT(1) FROM dbo.TDADEmployee WHERE EmployeeID=@id AND CompanyID=@co AND IsActive=1":type=="DEPARTMENT"?"SELECT COUNT(1) FROM dbo.TDADOrganizationUnit WHERE OrgUnitID=@id AND CompanyID=@co AND UnitType=N'DEP' AND IsActive=1":null;if(sql is null)return false;await using var c=new SqlCommand(sql,db);Add(c,"@id",SqlDbType.BigInt,y.Id);Add(c,"@co",SqlDbType.BigInt,co);if(Convert.ToInt32(await c.ExecuteScalarAsync(t))!=1)return false;}return true;}
    async Task<bool> CompanyUser(SqlConnection db,long co,long u,CancellationToken t){await using var c=new SqlCommand("SELECT COUNT(1) FROM dbo.TDADUser WHERE UserID=@u AND CompanyID=@co AND IsActive=1",db);Add(c,"@u",SqlDbType.BigInt,u);Add(c,"@co",SqlDbType.BigInt,co);return Convert.ToInt32(await c.ExecuteScalarAsync(t))==1;}
    async Task Audit(SqlConnection db,SqlTransaction tx,long co,long id,string action,string? detail,long user,CancellationToken t){await using var c=new SqlCommand("INSERT dbo.TDVTAuditHistory(CompanyID,VoteTopicID,ActionCode,Detail,ActionBy) VALUES(@co,@id,@a,@d,@u);INSERT dbo.TDVTApprovalHistory(CompanyID,VoteTopicID,ActionCode,Remark,ActionBy) SELECT @co,@id,@a,@d,@u WHERE @a IN(N'SUBMIT',N'APPROVE',N'RETURN');",db,tx);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@id",SqlDbType.BigInt,id);Add(c,"@a",SqlDbType.NVarChar,action,30);Add(c,"@d",SqlDbType.NVarChar,detail,1000);Add(c,"@u",SqlDbType.BigInt,user);await c.ExecuteNonQueryAsync(t);}
    async Task<bool> Can(SqlConnection db,string screen,string action,CancellationToken t)=>await CompanyMenuAccess.IsAllowedAsync(db,User,screen,action,t);
    async Task<SqlConnection> Open(CancellationToken t){var db=new SqlConnection(configuration.GetConnectionString("LaooDatabase"));await db.OpenAsync(t);return db;}
    bool Scope(out long co,out long user){co=user=0;return User.FindFirstValue("user_type")=="COMPANY_USER"&&long.TryParse(User.FindFirstValue("company_id"),out co)&&long.TryParse(User.FindFirstValue("user_id"),out user)&&co>0&&user>0;}
    static string? Validate(VoteTopicRequest x){if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Trim().Length>300)return "กรุณาระบุชื่อหัวข้อไม่เกิน 300 ตัวอักษร";if(x.OpenAt>=x.CloseAt)return "วันเวลาเปิดต้องน้อยกว่าวันเวลาปิด";if(x.Options is null||x.Options.Count<2||x.Options.Any(v=>string.IsNullOrWhiteSpace(v))||x.Options.Select(v=>v.Trim()).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=x.Options.Count)return "ต้องมีตัวเลือกอย่างน้อย 2 ตัวเลือกและห้ามซ้ำ";if(x.TargetMode.Trim().ToUpperInvariant() is not("ALL" or "CUSTOM"))return "รูปแบบกลุ่มผู้มีสิทธิ์ไม่ถูกต้อง";if(x.IdentityMode.Trim().ToUpperInvariant() is not("ANONYMOUS" or "OPEN"))return "รูปแบบการเปิดเผยชื่อไม่ถูกต้อง";return null;}
    static string EffectiveStatus(string status,DateTime close)=>status=="PUBLISHED"&&close<=DateTime.UtcNow?"CLOSED":status;
    static void BindList(SqlCommand c,long co,string? search,string? status,int page,int take){Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@status",SqlDbType.NVarChar,string.IsNullOrWhiteSpace(status)?null:status.Trim().ToUpperInvariant(),30);Add(c,"@search",SqlDbType.NVarChar,search?.Trim()??"",300);Add(c,"@like",SqlDbType.NVarChar,$"%{search?.Trim()??""}%",310);Add(c,"@skip",SqlDbType.Int,(page-1)*take);Add(c,"@take",SqlDbType.Int,take);}
    static void BindTopic(SqlCommand c,long co,long user,VoteTopicRequest x){Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@u",SqlDbType.BigInt,user);Add(c,"@name",SqlDbType.NVarChar,x.Name.Trim(),300);Add(c,"@desc",SqlDbType.NVarChar,string.IsNullOrWhiteSpace(x.Description)?null:x.Description.Trim(),2000);Add(c,"@target",SqlDbType.NVarChar,x.TargetMode.Trim().ToUpperInvariant(),20);Add(c,"@identity",SqlDbType.NVarChar,x.IdentityMode.Trim().ToUpperInvariant(),20);Add(c,"@open",SqlDbType.DateTime2,x.OpenAt);Add(c,"@close",SqlDbType.DateTime2,x.CloseAt);}
    static void Add(SqlCommand c,string n,SqlDbType type,object? v,int size=0){var p=size==0?c.Parameters.Add(n,type):c.Parameters.Add(n,type,size);p.Value=v??DBNull.Value;}
    [HttpGet("mine/{id:long}")]
    public async Task<IActionResult> MyVoteDetail(long id,CancellationToken t) {
        if(!Scope(out var co,out var user))return Forbid();await using var db=await Open(t);if(!await Can(db,Mine,"VIEW",t))return Forbid();
        await using var check=new SqlCommand("SELECT COUNT(1) FROM dbo.TDVTTopic T JOIN dbo.TDVTTopicVoter V ON V.VoteTopicID=T.VoteTopicID AND V.UserID=@u WHERE T.VoteTopicID=@id AND T.CompanyID=@co AND T.StatusCode=N'PUBLISHED' AND SYSUTCDATETIME() BETWEEN T.OpenDateTime AND T.CloseDateTime",db);Add(check,"@id",SqlDbType.BigInt,id);Add(check,"@co",SqlDbType.BigInt,co);Add(check,"@u",SqlDbType.BigInt,user);if(Convert.ToInt32(await check.ExecuteScalarAsync(t))!=1)return NotFound();
        return await Topic(db,co,id,t) is { } topic?Ok(topic):NotFound();
    }
    [HttpGet("results")]
    public async Task<IActionResult> ResultsList([FromQuery]string? search,[FromQuery]string? status,[FromQuery]int page=1,[FromQuery]int pageSize=20,CancellationToken t=default) {
        if(!Scope(out var co,out _))return Forbid();await using var db=await Open(t);if(!await Can(db,Results,"VIEW",t))return Forbid();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);
        await using var c=new SqlCommand("SELECT T.VoteTopicID,T.VoteNo,T.TopicName,T.StatusCode,T.IdentityMode,T.OpenDateTime,T.CloseDateTime,COUNT(V.VoteTopicVoterID),SUM(CASE WHEN V.VotedAt IS NULL THEN 0 ELSE 1 END) FROM dbo.TDVTTopic T LEFT JOIN dbo.TDVTTopicVoter V ON V.VoteTopicID=T.VoteTopicID WHERE T.CompanyID=@co AND (@status IS NULL OR T.StatusCode=@status) AND (@search=N'' OR T.VoteNo LIKE @like OR T.TopicName LIKE @like) GROUP BY T.VoteTopicID,T.VoteNo,T.TopicName,T.StatusCode,T.IdentityMode,T.OpenDateTime,T.CloseDateTime ORDER BY T.CloseDateTime DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY;SELECT COUNT_BIG(*) FROM dbo.TDVTTopic T WHERE T.CompanyID=@co AND (@status IS NULL OR T.StatusCode=@status) AND (@search=N'' OR T.VoteNo LIKE @like OR T.TopicName LIKE @like)",db);Add(c,"@co",SqlDbType.BigInt,co);Add(c,"@status",SqlDbType.NVarChar,string.IsNullOrWhiteSpace(status)?null:status.Trim().ToUpperInvariant(),30);Add(c,"@search",SqlDbType.NVarChar,search?.Trim()??"",300);Add(c,"@like",SqlDbType.NVarChar,$"%{search?.Trim()??""}%",310);Add(c,"@skip",SqlDbType.Int,(page-1)*pageSize);Add(c,"@take",SqlDbType.Int,pageSize);var rows=new List<object>();await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))rows.Add(new{id=r.GetInt64(0),voteNo=r.GetString(1),name=r.GetString(2),status=EffectiveStatus(r.GetString(3),r.GetDateTime(6)),identityMode=r.GetString(4),openAt=r.GetDateTime(5),closeAt=r.GetDateTime(6),eligible=r.GetInt32(7),voted=r.IsDBNull(8)?0:r.GetInt32(8)});await r.NextResultAsync(t);var total=await r.ReadAsync(t)?r.GetInt64(0):0;return Ok(new{items=rows,total,page,pageSize});
    }

}

public sealed record VoteSettingsRequest(bool IsEnabled,int DefaultOpenHours,long? DefaultApproverUserId);
public sealed record VoteTargetRequest(string Type,long Id);
public sealed record VoteTopicRequest(string Name,string? Description,string TargetMode,string IdentityMode,DateTime OpenAt,DateTime CloseAt,List<string>? Options,List<VoteTargetRequest>? Targets);
public sealed record ApprovalRequest(string? Action,string? Remark);
public sealed record VoteRequest(long OptionId);
