/* LAOO Service PM phase 1.  Idempotent; uses existing Item/ItemInstance as source of equipment. */
IF OBJECT_ID(N'dbo.TDADServicePmPlan',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmPlan(
 PmPlanID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmPlan PRIMARY KEY, CompanyID bigint NOT NULL,
 PlanName nvarchar(200) NOT NULL, ItemTypeCode nvarchar(50) NOT NULL, IntervalUnit nvarchar(10) NOT NULL,
 IntervalValue int NOT NULL, StartDate date NOT NULL, IsActive bit NOT NULL CONSTRAINT DF_TDADServicePmPlan_Active DEFAULT 1,
 CreateDate datetime2(3) NOT NULL CONSTRAINT DF_TDADServicePmPlan_CreateDate DEFAULT SYSUTCDATETIME(), CreateBy bigint NULL, UpdateDate datetime2(3) NULL, UpdateBy bigint NULL,
 CONSTRAINT CK_TDADServicePmPlan_Unit CHECK(IntervalUnit IN(N'DAY',N'MONTH')), CONSTRAINT CK_TDADServicePmPlan_Value CHECK(IntervalValue>0));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_TDADServicePmPlan_Company_Type') CREATE INDEX IX_TDADServicePmPlan_Company_Type ON dbo.TDADServicePmPlan(CompanyID,ItemTypeCode,IsActive);
IF OBJECT_ID(N'dbo.TDADServicePmPlanAssignment',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmPlanAssignment(
 PmPlanAssignmentID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmPlanAssignment PRIMARY KEY, CompanyID bigint NOT NULL, PmPlanID bigint NOT NULL, ItemInstanceID bigint NOT NULL,
 StartDate date NOT NULL, NextDueDate date NOT NULL, IsActive bit NOT NULL CONSTRAINT DF_TDADServicePmPlanAssignment_Active DEFAULT 1,
 CreateDate datetime2(3) NOT NULL CONSTRAINT DF_TDADServicePmPlanAssignment_CreateDate DEFAULT SYSUTCDATETIME(), CreateBy bigint NULL, UpdateDate datetime2(3) NULL, UpdateBy bigint NULL,
 CONSTRAINT UQ_TDADServicePmPlanAssignment UNIQUE(CompanyID,PmPlanID,ItemInstanceID), CONSTRAINT FK_TDADServicePmPlanAssignment_Plan FOREIGN KEY(PmPlanID) REFERENCES dbo.TDADServicePmPlan(PmPlanID), CONSTRAINT FK_TDADServicePmPlanAssignment_Instance FOREIGN KEY(ItemInstanceID) REFERENCES dbo.TDIVItemInstance(ItemInstanceID));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_TDADServicePmPlanAssignment_Due') CREATE INDEX IX_TDADServicePmPlanAssignment_Due ON dbo.TDADServicePmPlanAssignment(CompanyID,NextDueDate,IsActive);
IF OBJECT_ID(N'dbo.TDADServicePmChecklist',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmChecklist(PmChecklistID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmChecklist PRIMARY KEY,CompanyID bigint NOT NULL,ChecklistName nvarchar(200) NOT NULL,IsActive bit NOT NULL CONSTRAINT DF_TDADServicePmChecklist_Active DEFAULT 1,CreateDate datetime2(3) NOT NULL CONSTRAINT DF_TDADServicePmChecklist_CreateDate DEFAULT SYSUTCDATETIME(),CreateBy bigint NULL,UpdateDate datetime2(3) NULL,UpdateBy bigint NULL);
IF OBJECT_ID(N'dbo.TDADServicePmChecklistItem',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmChecklistItem(PmChecklistItemID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmChecklistItem PRIMARY KEY,CompanyID bigint NOT NULL,PmChecklistID bigint NOT NULL,SequenceNo int NOT NULL,CheckItem nvarchar(500) NOT NULL,IsRequired bit NOT NULL CONSTRAINT DF_TDADServicePmChecklistItem_Required DEFAULT 1,IsActive bit NOT NULL CONSTRAINT DF_TDADServicePmChecklistItem_Active DEFAULT 1,CONSTRAINT FK_TDADServicePmChecklistItem_Header FOREIGN KEY(PmChecklistID) REFERENCES dbo.TDADServicePmChecklist(PmChecklistID));
IF OBJECT_ID(N'dbo.TDADServicePmPlanChecklist',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmPlanChecklist(CompanyID bigint NOT NULL,PmPlanID bigint NOT NULL,PmChecklistID bigint NOT NULL,CONSTRAINT PK_TDADServicePmPlanChecklist PRIMARY KEY(CompanyID,PmPlanID,PmChecklistID),CONSTRAINT FK_TDADServicePmPlanChecklist_Plan FOREIGN KEY(PmPlanID) REFERENCES dbo.TDADServicePmPlan(PmPlanID),CONSTRAINT FK_TDADServicePmPlanChecklist_Checklist FOREIGN KEY(PmChecklistID) REFERENCES dbo.TDADServicePmChecklist(PmChecklistID));
IF OBJECT_ID(N'dbo.TDADServicePmWorkOrder',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmWorkOrder(PmWorkOrderID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmWorkOrder PRIMARY KEY,CompanyID bigint NOT NULL,PmPlanAssignmentID bigint NOT NULL,ItemInstanceID bigint NOT NULL,DueDate date NOT NULL,StatusCode nvarchar(20) NOT NULL CONSTRAINT DF_TDADServicePmWorkOrder_Status DEFAULT N'PENDING',PlanNameSnapshot nvarchar(200) NOT NULL,ItemSnapshot nvarchar(500) NULL,LocationSnapshot nvarchar(500) NULL,StartedDate datetime2(3) NULL,StartedBy bigint NULL,CompletedDate datetime2(3) NULL,CompletedBy bigint NULL,ResultDetail nvarchar(2000) NULL,SkipReason nvarchar(1000) NULL,CreateDate datetime2(3) NOT NULL CONSTRAINT DF_TDADServicePmWorkOrder_CreateDate DEFAULT SYSUTCDATETIME(),CreateBy bigint NULL,UpdateDate datetime2(3) NULL,UpdateBy bigint NULL,CONSTRAINT UQ_TDADServicePmWorkOrder_Due UNIQUE(CompanyID,PmPlanAssignmentID,DueDate),CONSTRAINT CK_TDADServicePmWorkOrder_Status CHECK(StatusCode IN(N'PENDING',N'IN_PROGRESS',N'COMPLETED',N'SKIPPED')),CONSTRAINT FK_TDADServicePmWorkOrder_Assignment FOREIGN KEY(PmPlanAssignmentID) REFERENCES dbo.TDADServicePmPlanAssignment(PmPlanAssignmentID),CONSTRAINT FK_TDADServicePmWorkOrder_Instance FOREIGN KEY(ItemInstanceID) REFERENCES dbo.TDIVItemInstance(ItemInstanceID));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_TDADServicePmWorkOrder_Calendar') CREATE INDEX IX_TDADServicePmWorkOrder_Calendar ON dbo.TDADServicePmWorkOrder(CompanyID,DueDate,StatusCode);
IF OBJECT_ID(N'dbo.TDADServicePmWorkOrderCheck',N'U') IS NULL
CREATE TABLE dbo.TDADServicePmWorkOrderCheck(PmWorkOrderCheckID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TDADServicePmWorkOrderCheck PRIMARY KEY,CompanyID bigint NOT NULL,PmWorkOrderID bigint NOT NULL,PmChecklistItemID bigint NULL,SequenceNo int NOT NULL,CheckItemSnapshot nvarchar(500) NOT NULL,IsRequired bit NOT NULL,IsChecked bit NOT NULL CONSTRAINT DF_TDADServicePmWorkOrderCheck_Checked DEFAULT 0,ResultNote nvarchar(1000) NULL,CONSTRAINT FK_TDADServicePmWorkOrderCheck_WorkOrder FOREIGN KEY(PmWorkOrderID) REFERENCES dbo.TDADServicePmWorkOrder(PmWorkOrderID));
