import '../../features/meeting/meeting_route_contract.dart';

abstract final class RoutePaths {
  static const String landing = '/';
  static const String login = '/login';
  static const String resetPassword = '/reset-password';
  static const String authenticatedHome = '/home';
  static const String partnerCompanies = '/partner/companies';
  static const String partnerBranches = '/partner/branches';
  static const String companyBranches = '/company/branches';
  static const String partnerUsers = '/partner/users';
  static const String supportHome = '/support';
  static const String partner = '/support/partner';
  static const String laooUser = '/support/laoo-user';
  static const String partnerUser = '/support/partner-user';
  static const String companyUser = '/support/company-user';
  static const String module = '/support/module';
  static const String customerModule = '/support/customer-module';
  static const String permission = '/support/permission';
  static const String audit = '/support/audit';
  static const String loginLog = '/support/login-log';
  static const String companySetup = '/support/company-setup';
  static const String technicalInfo = '/support/technical-info';
  static const String masterData = '/master-data';
  static const String organizationStructure = '/organization-structure';
  static const String companyEmployees = '/company/employees';
  static const String companySupervisors = '/company/supervisors';
  static const String companyUsers = '/company/users';
  static const String companyRoleGroups = '/company/role-groups';
  static const String companyMenuPermissions = '/company/menu-permissions';
  static const String partnerEmployees = '/partner/employees';
  static const String customerEmployees = '/partner/customer-employees';
  static const String partnerRoleGroups = '/partner/role-groups';
  static const String partnerMenuPermissions = '/partner/menu-permissions';
  static const String laooEmployees = '/support/employees';
  static const String laooUsers = '/support/users';
  static const String meetingRoomBookings = MeetingRoutePaths.bookings;
  static const String meetingRoomApprovals = MeetingRoutePaths.approvals;
  static const String meetingRoomCalendar = MeetingRoutePaths.calendar;
  static const String meetingInvitationRsvp = MeetingRoutePaths.invitations;
  static const String meetingFoodPlans = MeetingRoutePaths.foodPlans;
  static const String roomCheckIn = MeetingRoutePaths.roomCheckIn;
  static const String roomSupportTasks = MeetingRoutePaths.roomSupportTasks;
  static const String roomIssues = MeetingRoutePaths.roomIssues;
  static const String meetingBuildings = MeetingRoutePaths.buildings;
  static const String meetingRooms = MeetingRoutePaths.rooms;
  static const String meetingFacilities = MeetingRoutePaths.facilities;
  static const String meetingFoods = MeetingRoutePaths.foods;
  static const String meetingRoomUtilizationReport =
      MeetingRoutePaths.utilizationReport;
  static const String meetingNoShowReport = MeetingRoutePaths.noShowReport;
  static const String meetingFeedbackReport = MeetingRoutePaths.feedbackReport;
}
