using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

using Microsoft.Extensions.Configuration;

namespace LaooMemoModule.Controllers;

[ApiController,Authorize,Route("api/company/memo")]
public sealed class MemoMasterController(IConfiguration config):MemoControllerBase(config)
{
 [HttpGet("types")] public Task<IActionResult> Types(CancellationToken ct)=>List("50002","SELECT MemoTypeID id,TypeCode code,TypeName name,NumberPrefix prefix,DefaultRouteID routeId,DefaultTemplateID templateId,DefaultConfidentiality confidentiality,IsActive active FROM dbo.TDMEType WHERE CompanyID=@company ORDER BY TypeName",ct);
 [HttpPost("types")] public Task<IActionResult> Type(TypeRequest x,CancellationToken ct)=>SaveType(null,x,ct);
 [HttpPut("types/{id:long}")] public Task<IActionResult> Type(long id,TypeRequest x,CancellationToken ct)=>SaveType(id,x,ct);
 async Task<IActionResult> SaveType(long? id,TypeRequest x,CancellationToken ct){if(Clean(x.Code) is null||Clean(x.Name) is null||Clean(x.Prefix) is null||x.Confidentiality is not("NORMAL" or "INTERNAL" or "SECRET"))return Invalid("ข้อมูลประเภทไม่ครบ","ระบุรหัส ชื่อ รูปแบบเลข และชั้นความลับ");if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50002",id is null?"CREATE":"EDIT",ct))return Forbid();try{var sql=id is null?"INSERT dbo.TDMEType(CompanyID,TypeCode,TypeName,NumberPrefix,DefaultRouteID,DefaultTemplateID,DefaultConfidentiality,IsActive,CreateBy) OUTPUT INSERTED.MemoTypeID VALUES(@company,@code,@name,@prefix,@route,@template,@secret,@active,@user)":"UPDATE dbo.TDMEType SET TypeCode=@code,TypeName=@name,NumberPrefix=@prefix,DefaultRouteID=@route,DefaultTemplateID=@template,DefaultConfidentiality=@secret,IsActive=@active,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() OUTPUT INSERTED.MemoTypeID WHERE CompanyID=@company AND MemoTypeID=@id";var saved=await Scalar<long>(db,sql,ct,("@company",company),("@id",id),("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@prefix",x.Prefix.Trim().ToUpperInvariant()),("@route",x.RouteId),("@template",x.TemplateId),("@secret",x.Confidentiality),("@active",x.Active),("@user",user));return saved>0?Ok(new{id=saved}):NotFound();}catch(SqlException e)when(e.Number is 2601 or 2627){return Conflict(new{message="รหัสประเภทซ้ำ",description="ใช้รหัสอื่นภายในบริษัทเดียวกัน"});}}
 [HttpDelete("types/{id:long}")] public Task<IActionResult> DeleteType(long id,CancellationToken ct)=>DeleteUnused("50002","TDMEType","MemoTypeID","TDMEMemo","MemoTypeID",id,ct);

 [HttpGet("templates")] public Task<IActionResult> Templates(CancellationToken ct)=>List("50004","SELECT TemplateID id,TemplateCode code,TemplateName name,SubjectDefault subject,BodyDeltaJson delta,BodyPlainText body,IsActive active FROM dbo.TDMETemplate WHERE CompanyID=@company ORDER BY TemplateName",ct);
 [HttpPost("templates")] public Task<IActionResult> Template(TemplateRequest x,CancellationToken ct)=>SaveTemplate(null,x,ct);
 [HttpPut("templates/{id:long}")] public Task<IActionResult> Template(long id,TemplateRequest x,CancellationToken ct)=>SaveTemplate(id,x,ct);
 async Task<IActionResult> SaveTemplate(long? id,TemplateRequest x,CancellationToken ct){if(Clean(x.Code) is null||Clean(x.Name) is null)return Invalid("ข้อมูล Template ไม่ครบ","ระบุรหัสและชื่อ Template");if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50004",id is null?"CREATE":"EDIT",ct))return Forbid();try{var sql=id is null?"INSERT dbo.TDMETemplate(CompanyID,TemplateCode,TemplateName,SubjectDefault,BodyDeltaJson,BodyPlainText,IsActive,CreateBy) OUTPUT INSERTED.TemplateID VALUES(@company,@code,@name,@subject,@delta,@body,@active,@user)":"UPDATE dbo.TDMETemplate SET TemplateCode=@code,TemplateName=@name,SubjectDefault=@subject,BodyDeltaJson=@delta,BodyPlainText=@body,IsActive=@active,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() OUTPUT INSERTED.TemplateID WHERE CompanyID=@company AND TemplateID=@id";var saved=await Scalar<long>(db,sql,ct,("@company",company),("@id",id),("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@subject",Clean(x.Subject)),("@delta",Clean(x.Delta)??"[{\"insert\":\"\\n\"}]"),("@body",Clean(x.Body)??""),("@active",x.Active),("@user",user));return saved>0?Ok(new{id=saved}):NotFound();}catch(SqlException e)when(e.Number is 2601 or 2627){return Conflict(new{message="รหัส Template ซ้ำ",description="ใช้รหัสอื่นภายในบริษัทเดียวกัน"});}}
 [HttpDelete("templates/{id:long}")] public Task<IActionResult> DeleteTemplate(long id,CancellationToken ct)=>DeleteUnused("50004","TDMETemplate","TemplateID","TDMEType","DefaultTemplateID",id,ct);

 [HttpGet("routes")] public async Task<IActionResult> Routes(CancellationToken ct){if(!Scope(out var company,out _))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50003","VIEW",ct))return Forbid();var items=await Query(db,"SELECT RouteID id,RouteCode code,RouteName name,IsActive active FROM dbo.TDMEApprovalRoute WHERE CompanyID=@company ORDER BY RouteName",ct,("@company",company));foreach(var item in items)item["steps"]=await Query(db,"SELECT RouteStepID id,StepOrder stepOrder,AssigneeUserID userId,StepName name FROM dbo.TDMEApprovalRouteStep WHERE CompanyID=@company AND RouteID=@id ORDER BY StepOrder",ct,("@company",company),("@id",item["id"]));return Ok(items);}
 [HttpPost("routes")] public Task<IActionResult> Route(RouteRequest x,CancellationToken ct)=>SaveRoute(null,x,ct);
 [HttpPut("routes/{id:long}")] public Task<IActionResult> Route(long id,RouteRequest x,CancellationToken ct)=>SaveRoute(id,x,ct);
 async Task<IActionResult> SaveRoute(long? id,RouteRequest x,CancellationToken ct){if(Clean(x.Code) is null||Clean(x.Name) is null||x.Steps is null||x.Steps.Count==0||x.Steps.Any(v=>v.UserId<=0))return Invalid("สายอนุมัติไม่ครบ","ระบุรหัส ชื่อ และผู้อนุมัติอย่างน้อยหนึ่งขั้น");if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50003",id is null?"CREATE":"EDIT",ct))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(ct);try{long route;if(id is null)route=await Scalar<long>(db,tx,"INSERT dbo.TDMEApprovalRoute(CompanyID,RouteCode,RouteName,IsActive,CreateBy) OUTPUT INSERTED.RouteID VALUES(@company,@code,@name,@active,@user)",ct,("@company",company),("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@active",x.Active),("@user",user));else{route=id.Value;if(await Execute(db,tx,"UPDATE dbo.TDMEApprovalRoute SET RouteCode=@code,RouteName=@name,IsActive=@active,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@company AND RouteID=@id",ct,("@company",company),("@id",route),("@code",x.Code.Trim().ToUpperInvariant()),("@name",x.Name.Trim()),("@active",x.Active),("@user",user))==0){await tx.RollbackAsync(ct);return NotFound();}await Execute(db,tx,"DELETE dbo.TDMEApprovalRouteStep WHERE CompanyID=@company AND RouteID=@id",ct,("@company",company),("@id",route));}var order=0;foreach(var step in x.Steps){order++;await Execute(db,tx,"INSERT dbo.TDMEApprovalRouteStep(CompanyID,RouteID,StepOrder,AssigneeUserID,StepName,CreateBy) VALUES(@company,@route,@order,@assignee,@name,@user)",ct,("@company",company),("@route",route),("@order",order),("@assignee",step.UserId),("@name",Clean(step.Name)),("@user",user));}await tx.CommitAsync(ct);return Ok(new{id=route});}catch(SqlException e)when(e.Number is 2601 or 2627){await tx.RollbackAsync(ct);return Conflict(new{message="รหัสสายอนุมัติซ้ำ",description="ใช้รหัสอื่นภายในบริษัทเดียวกัน"});}}
 [HttpDelete("routes/{id:long}")] public Task<IActionResult> DeleteRoute(long id,CancellationToken ct)=>DeleteUnused("50003","TDMEApprovalRoute","RouteID","TDMEType","DefaultRouteID",id,ct);

 async Task<IActionResult> List(string menu,string sql,CancellationToken ct){if(!Scope(out var company,out _))return Forbid();await using var db=await Open(ct);if(!await Can(db,menu,"VIEW",ct))return Forbid();return Ok(await Query(db,sql,ct,("@company",company)));}
 async Task<IActionResult> DeleteUnused(string menu,string table,string key,string reference,string referenceKey,long id,CancellationToken ct){if(!Scope(out var company,out _))return Forbid();await using var db=await Open(ct);if(!await Can(db,menu,"DELETE",ct))return Forbid();if(await Scalar<int>(db,$"SELECT COUNT(*) FROM dbo.{reference} WHERE CompanyID=@company AND {referenceKey}=@id",ct,("@company",company),("@id",id))>0)return Conflict(new{message="ลบรายการไม่ได้",description="รายการถูกใช้งานแล้ว"});return await Execute(db,$"DELETE dbo.{table} WHERE CompanyID=@company AND {key}=@id",ct,("@company",company),("@id",id))>0?NoContent():NotFound();}
}
