using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.Configuration;

namespace LaooMemoModule.Controllers;

[ApiController,Authorize,Route("api/company/memo")]
public sealed class MemoAccessController(IConfiguration config):MemoControllerBase(config)
{
 static readonly string[] ActionNames=["VIEW","CREATE","EDIT","DELETE","SUBMIT","WITHDRAW","APPROVE","RETURN","CANCEL","PREVIEW","DOWNLOAD","PRINT","EXPORT","UPLOAD"];
 [HttpGet("actions/{menu}")] public async Task<IActionResult> Actions(string menu,CancellationToken ct){if(!Menus.Contains(menu)||!Scope(out _,out _))return Forbid();await using var db=await Open(ct);if(!await Can(db,menu,"VIEW",ct))return Forbid();var result=new Dictionary<string,bool>();foreach(var action in ActionNames)result[action.ToLowerInvariant()]=await Can(db,menu,action,ct);return Ok(result);}
 [HttpGet("options")] public async Task<IActionResult> Options(CancellationToken ct){if(!Scope(out var company,out _))return Forbid();await using var db=await Open(ct);if(!await AnyView(db,ct))return Forbid();return Ok(new{types=await Query(db,"SELECT MemoTypeID id,TypeCode code,TypeName name,DefaultRouteID routeId,DefaultTemplateID templateId,DefaultConfidentiality confidentiality FROM dbo.TDMEType WHERE CompanyID=@company AND IsActive=1 ORDER BY TypeName",ct,("@company",company)),routes=await Query(db,"SELECT RouteID id,RouteCode code,RouteName name FROM dbo.TDMEApprovalRoute WHERE CompanyID=@company AND IsActive=1 ORDER BY RouteName",ct,("@company",company)),templates=await Query(db,"SELECT TemplateID id,TemplateCode code,TemplateName name,SubjectDefault subject,BodyDeltaJson delta,BodyPlainText body FROM dbo.TDMETemplate WHERE CompanyID=@company AND IsActive=1 ORDER BY TemplateName",ct,("@company",company)),users=await Query(db,"SELECT u.UserID id,u.Username code,COALESCE(e.FullName,u.Username) name FROM dbo.TDADUser u LEFT JOIN dbo.TDADUserEmployee ue ON ue.CompanyID=u.CompanyID AND ue.UserID=u.UserID AND ue.IsActive=1 LEFT JOIN dbo.TDADEmployee e ON e.CompanyID=ue.CompanyID AND e.EmployeeID=ue.EmployeeID WHERE u.CompanyID=@company AND u.IsActive=1 ORDER BY COALESCE(e.FullName,u.Username)",ct,("@company",company)),departments=await Query(db,"SELECT OrgUnitID id,UnitCode code,NameTH name FROM dbo.TDADOrganizationUnit WHERE CompanyID=@company AND UnitType IN(N'DEPARTMENT',N'DEP') AND IsActive=1 ORDER BY NameTH",ct,("@company",company)),roles=await Query(db,"SELECT RoleGroupID id,RoleCode code,RoleNameTH name FROM dbo.TDADRoleGroup WHERE CompanyID=@company AND ScopeType=N'C' AND IsActive=1 ORDER BY RoleNameTH",ct,("@company",company))});}
 [HttpGet("settings")] public async Task<IActionResult> Settings(CancellationToken ct){if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50001","VIEW",ct))return Forbid();await EnsureSettings(db,company,user,ct);return Ok((await Query(db,"SELECT MaxAttachmentMB maxAttachmentMb,AllowedExtensions allowedExtensions,AutoDistribute autoDistribute FROM dbo.TDMESystemSetting WHERE CompanyID=@company",ct,("@company",company))).Single());}
 [HttpPut("settings")] public async Task<IActionResult> Settings(SettingRequest request,CancellationToken ct){if(request.MaxAttachmentMb is <1 or >200||Clean(request.AllowedExtensions) is null)return Invalid("ข้อมูลตั้งค่าไม่ถูกต้อง","ขนาดไฟล์ต้องอยู่ระหว่าง 1-200 MB และต้องระบุนามสกุลไฟล์");if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50001","EDIT",ct))return Forbid();await EnsureSettings(db,company,user,ct);await Execute(db,"UPDATE dbo.TDMESystemSetting SET MaxAttachmentMB=@max,AllowedExtensions=@extensions,AutoDistribute=@auto,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@company",ct,("@max",request.MaxAttachmentMb),("@extensions",request.AllowedExtensions.Trim().ToLowerInvariant()),("@auto",request.AutoDistribute),("@user",user),("@company",company));return NoContent();}
}
