using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.Configuration;

namespace LaooMemoModule.Controllers;

[ApiController,Authorize,Route("api/company/memo")]
public sealed class MemoReadController(IConfiguration config):MemoControllerBase(config)
{
 [HttpGet("inbox")] public async Task<IActionResult> Inbox(CancellationToken ct){if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50007","VIEW",ct))return Forbid();return Ok(await Query(db,"SELECT DISTINCT m.MemoID id,m.MemoNo memoNo,m.SubjectText subject,m.ToText recipient,m.MemoDate memoDate,m.ConfidentialityCode confidentiality,r.ReadAt readAt,m.DistributedAt distributedAt FROM dbo.TDMEMemoRecipient r JOIN dbo.TDMEMemo m ON m.CompanyID=r.CompanyID AND m.MemoID=r.MemoID WHERE r.CompanyID=@company AND m.StatusCode=N'DISTRIBUTED' AND (r.SubjectType=N'USER' AND r.SubjectID=@user OR r.SubjectType=N'DEPARTMENT' AND r.SubjectID IN(SELECT e.DepartmentOrgUnitID FROM dbo.TDADUserEmployee ue JOIN dbo.TDADEmployee e ON e.CompanyID=ue.CompanyID AND e.EmployeeID=ue.EmployeeID WHERE ue.CompanyID=@company AND ue.UserID=@user AND ue.IsActive=1) OR r.SubjectType=N'ROLE' AND r.SubjectID IN(SELECT erg.RoleGroupID FROM dbo.TDADUserEmployee ue JOIN dbo.TDADEmployeeRoleGroup erg ON erg.EmployeeID=ue.EmployeeID AND erg.IsActive=1 AND erg.EffectiveFrom<=CONVERT(date,SYSUTCDATETIME()) AND (erg.EffectiveTo IS NULL OR erg.EffectiveTo>=CONVERT(date,SYSUTCDATETIME())) WHERE ue.CompanyID=@company AND ue.UserID=@user AND ue.IsActive=1)) ORDER BY m.DistributedAt DESC",ct,("@company",company),("@user",user)));}
 [HttpPost("inbox/{id:long}/read")] public async Task<IActionResult> Read(long id,CancellationToken ct){if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50007","VIEW",ct))return Forbid();await Execute(db,"UPDATE r SET ReadAt=COALESCE(ReadAt,SYSUTCDATETIME()) FROM dbo.TDMEMemoRecipient r WHERE r.CompanyID=@company AND r.MemoID=@id AND (r.SubjectType=N'USER' AND r.SubjectID=@user OR r.SubjectType=N'DEPARTMENT' AND r.SubjectID IN(SELECT e.DepartmentOrgUnitID FROM dbo.TDADUserEmployee ue JOIN dbo.TDADEmployee e ON e.CompanyID=ue.CompanyID AND e.EmployeeID=ue.EmployeeID WHERE ue.CompanyID=@company AND ue.UserID=@user AND ue.IsActive=1) OR r.SubjectType=N'ROLE' AND r.SubjectID IN(SELECT erg.RoleGroupID FROM dbo.TDADUserEmployee ue JOIN dbo.TDADEmployeeRoleGroup erg ON erg.EmployeeID=ue.EmployeeID AND erg.IsActive=1 AND erg.EffectiveFrom<=CONVERT(date,SYSUTCDATETIME()) AND (erg.EffectiveTo IS NULL OR erg.EffectiveTo>=CONVERT(date,SYSUTCDATETIME())) WHERE ue.CompanyID=@company AND ue.UserID=@user AND ue.IsActive=1))",ct,("@company",company),("@id",id),("@user",user));return NoContent();}
 [HttpGet("history")] public async Task<IActionResult> History(CancellationToken ct){if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50008","VIEW",ct))return Forbid();return Ok(await Query(db,"SELECT m.MemoID id,COALESCE(m.MemoNo,m.TemporaryNo) memoNo,m.SubjectText subject,m.StatusCode status,m.ConfidentialityCode confidentiality,m.CreateDate createDate,m.ApprovedAt approvedAt,m.DistributedAt distributedAt FROM dbo.TDMEMemo m WHERE m.CompanyID=@company AND (m.OwnerUserID=@user OR EXISTS(SELECT 1 FROM dbo.TDMEMemoApproval a WHERE a.CompanyID=m.CompanyID AND a.MemoID=m.MemoID AND a.AssigneeUserID=@user)) ORDER BY m.CreateDate DESC",ct,("@company",company),("@user",user)));}
 [HttpGet("reports")] public async Task<IActionResult> Reports(CancellationToken ct){if(!Scope(out var company,out _))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50009","VIEW",ct))return Forbid();return Ok(new{totals=(await Query(db,"SELECT COUNT(*) total,SUM(CASE WHEN StatusCode=N'DRAFT' THEN 1 ELSE 0 END) draft,SUM(CASE WHEN StatusCode=N'IN_APPROVAL' THEN 1 ELSE 0 END) inApproval,SUM(CASE WHEN StatusCode=N'DISTRIBUTED' THEN 1 ELSE 0 END) [distributed] FROM dbo.TDMEMemo WHERE CompanyID=@company",ct,("@company",company))).Single(),byType=await Query(db,"SELECT t.TypeName name,COUNT(m.MemoID) value FROM dbo.TDMEType t LEFT JOIN dbo.TDMEMemo m ON m.CompanyID=t.CompanyID AND m.MemoTypeID=t.MemoTypeID WHERE t.CompanyID=@company GROUP BY t.MemoTypeID,t.TypeName ORDER BY value DESC",ct,("@company",company)),byMonth=await Query(db,"SELECT CONVERT(char(7),MemoDate,120) name,COUNT(*) value FROM dbo.TDMEMemo WHERE CompanyID=@company GROUP BY CONVERT(char(7),MemoDate,120) ORDER BY name DESC",ct,("@company",company))});}
}
