using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace LaooMemoModule.Controllers;

[ApiController,Authorize,Route("api/company/memo")]
public sealed class MemoAttachmentController(IConfiguration config,IWebHostEnvironment environment):MemoControllerBase(config)
{
 [HttpPost("documents/{id:long}/attachments"),RequestSizeLimit(220_000_000)] public async Task<IActionResult> Upload(long id,[FromForm]IFormFile file,[FromForm]string kind="ATTACHMENT",CancellationToken ct=default){kind=kind.ToUpperInvariant();if(file.Length<=0||kind is not("INLINE" or "ATTACHMENT"))return Invalid("ไฟล์ไม่ถูกต้อง","เลือกไฟล์และประเภทที่รองรับ");if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);if(!await Can(db,"50005","UPLOAD",ct))return Forbid();await EnsureSettings(db,company,user,ct);var setting=(await Query(db,"SELECT MaxAttachmentMB maxMb,AllowedExtensions extensions FROM dbo.TDMESystemSetting WHERE CompanyID=@company",ct,("@company",company))).Single();var extension=Path.GetExtension(file.FileName).TrimStart('.').ToLowerInvariant();var allowed=Convert.ToString(setting["extensions"])!.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);if(!allowed.Contains(extension,StringComparer.OrdinalIgnoreCase)||file.Length>Convert.ToInt64(setting["maxMb"])*1024*1024)return Invalid("ไฟล์ไม่ผ่านเงื่อนไข",$"อนุญาต {string.Join(", ",allowed)} และขนาดไม่เกิน {setting["maxMb"]} MB");var memo=await Query(db,"SELECT CurrentVersionID versionId FROM dbo.TDMEMemo WHERE CompanyID=@company AND MemoID=@id AND OwnerUserID=@user AND StatusCode IN(N'DRAFT',N'RETURNED',N'WITHDRAWN')",ct,("@company",company),("@id",id),("@user",user));if(memo.Count==0)return Conflict(new{message="แนบไฟล์ไม่ได้",description="แนบได้เฉพาะ Memo ของตนที่ยังแก้ไขได้"});var version=Convert.ToInt64(memo[0]["versionId"]);var root=environment.WebRootPath??Path.Combine(environment.ContentRootPath,"wwwroot");var relative=Path.Combine("uploads","memo",company.ToString(),id.ToString(),version.ToString());var folder=Path.Combine(root,relative);Directory.CreateDirectory(folder);var stored=$"{Guid.NewGuid():N}.{extension}";var full=Path.Combine(folder,stored);await using(var output=System.IO.File.Create(full))await file.CopyToAsync(output,ct);await using var input=System.IO.File.OpenRead(full);var hash=Convert.ToHexString(await SHA256.HashDataAsync(input,ct));var attachment=await Scalar<long>(db,"INSERT dbo.TDMEAttachment(CompanyID,MemoID,VersionID,FileKind,OriginalFileName,StoredFileName,RelativePath,ContentType,FileSizeBytes,Sha256,CreateBy) OUTPUT INSERTED.AttachmentID VALUES(@company,@memo,@version,@kind,@original,@stored,@path,@content,@size,@hash,@user)",ct,("@company",company),("@memo",id),("@version",version),("@kind",kind),("@original",Path.GetFileName(file.FileName)),("@stored",stored),("@path",relative.Replace('\\','/')),("@content",file.ContentType),("@size",file.Length),("@hash",hash),("@user",user));return Ok(new{id=attachment,fileName=file.FileName,sizeBytes=file.Length,sha256=hash});}
 [HttpGet("attachments/{id:long}")] public async Task<IActionResult> File(long id,bool download=false,CancellationToken ct=default){if(!Scope(out var company,out var user))return Forbid();await using var db=await Open(ct);var action=download?"DOWNLOAD":"PREVIEW";if(!await Can(db,"50005",action,ct)&&!await Can(db,"50007",action,ct)&&!await Can(db,"50008",action,ct))return Forbid();var rows=await Query(db,"SELECT MemoID memoId,RelativePath relativePath,StoredFileName storedFileName,OriginalFileName originalFileName,ContentType contentType FROM dbo.TDMEAttachment WHERE CompanyID=@company AND AttachmentID=@id",ct,("@company",company),("@id",id));if(rows.Count==0||!await CanRead(db,company,Convert.ToInt64(rows[0]["memoId"]),user,ct))return Forbid();var root=environment.WebRootPath??Path.Combine(environment.ContentRootPath,"wwwroot");var full=Path.GetFullPath(Path.Combine(root,Convert.ToString(rows[0]["relativePath"])!,Convert.ToString(rows[0]["storedFileName"])!));var allowed=Path.GetFullPath(Path.Combine(root,"uploads","memo",company.ToString()));if(!full.StartsWith(allowed,StringComparison.OrdinalIgnoreCase)||!System.IO.File.Exists(full))return NotFound();return PhysicalFile(full,Convert.ToString(rows[0]["contentType"])??"application/octet-stream",download?Convert.ToString(rows[0]["originalFileName"]):null,true);}
}
