using System.Data;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace LaooProviderModule.Controllers;

[ApiController,Authorize,Route("api/company/provider")]
public sealed class ProviderWorkflowController(IConfiguration configuration):ProviderControllerBase(configuration)
{
    [HttpGet("approvals")]
    public async Task<IActionResult> Approvals(CancellationToken token){if(!SupportScope())return Forbid();await using var db=await Open(token);if(!await Can(db,"51005","VIEW",token))return Forbid();return Ok(await ProviderDb.Query(db,"SELECT p.ProviderID id,p.CompanyID companyId,c.CustomerNameTH companyName,p.Slug slug,p.StatusCode status,p.SubmittedAt submittedAt,r.DisplayName displayName,r.SummaryText summary FROM dbo.TDPRProviderProfile p JOIN dbo.TDPRProviderRevision r ON r.RevisionID=p.CurrentRevisionID JOIN dbo.TDSTCompanySetUp c ON c.CompanyID=p.CompanyID WHERE p.StatusCode IN(N'SUBMITTED',N'APPROVED',N'SUSPENDED') ORDER BY CASE p.StatusCode WHEN N'SUBMITTED' THEN 0 ELSE 1 END,p.SubmittedAt DESC",token));}

    [HttpPost("approvals/{id:long}/{action}")]
    public async Task<IActionResult> Approval(long id,string action,DecisionRequest request,CancellationToken token)
    {
        action=action.ToUpperInvariant();if(!SupportScope())return Forbid();if(action is not ("APPROVE" or "RETURN" or "SUSPEND"))return BadRequest(new{message="Action ไม่ถูกต้อง"});if(action!="APPROVE"&&Clean(request.Reason) is null)return BadRequest(new{message="ระบุเหตุผล"});await using var db=await Open(token);if(!await Can(db,"51005",action,token))return Forbid();var actor=ActorId();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(IsolationLevel.Serializable,token);var rows=await ProviderDb.Query(db,tx,"SELECT CompanyID companyId,CurrentRevisionID revisionId,StatusCode status FROM dbo.TDPRProviderProfile WITH(UPDLOCK,HOLDLOCK) WHERE ProviderID=@id",token,("@id",id));if(rows.Count==0){await tx.RollbackAsync(token);return NotFound();}var status=Convert.ToString(rows[0]["status"]);if(action is "APPROVE" or "RETURN"&&status!="SUBMITTED"){await tx.RollbackAsync(token);return Conflict(new{message="สถานะไม่พร้อมดำเนินการ"});}var next=action=="APPROVE"?"APPROVED":action=="RETURN"?"RETURNED":"SUSPENDED";var revision=Convert.ToInt64(rows[0]["revisionId"]);await ProviderDb.Execute(db,tx,"UPDATE dbo.TDPRProviderRevision SET StatusCode=@next,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE RevisionID=@revision;UPDATE dbo.TDPRProviderProfile SET StatusCode=@next,PublishedRevisionID=CASE WHEN @next=N'APPROVED' THEN @revision ELSE PublishedRevisionID END,ApprovedBy=CASE WHEN @next=N'APPROVED' THEN @user ELSE ApprovedBy END,ApprovedAt=CASE WHEN @next=N'APPROVED' THEN SYSUTCDATETIME() ELSE ApprovedAt END,ReturnReason=CASE WHEN @next=N'RETURNED' THEN @reason ELSE NULL END,SuspendedReason=CASE WHEN @next=N'SUSPENDED' THEN @reason ELSE NULL END,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ProviderID=@id",token,("@next",next),("@user",actor),("@revision",revision),("@reason",Clean(request.Reason)),("@id",id));await Audit(db,tx,Convert.ToInt64(rows[0]["companyId"]),"PROFILE",id,action,Clean(request.Reason),actor,token);await tx.CommitAsync(token);return NoContent();
    }

    [HttpGet("review-links")]
    public async Task<IActionResult> ReviewLinks(CancellationToken token){if(!CompanyScope(out var company,out _))return Forbid();await using var db=await Open(token);if(!await Can(db,"51006","VIEW",token))return Forbid();return Ok(await ProviderDb.Query(db,"SELECT i.ReviewInviteID id,i.ServiceDate serviceDate,i.ReferenceNo referenceNo,i.ExpiresAt expiresAt,i.StatusCode status,s.ServiceName serviceName,b.BranchName branchName,i.CreateDate createDate FROM dbo.TDPRReviewInvite i JOIN dbo.TDPRServiceType s ON s.ServiceTypeID=i.ServiceTypeID LEFT JOIN dbo.TDPRProviderBranch b ON b.ProviderBranchID=i.ProviderBranchID WHERE i.CompanyID=@company ORDER BY i.CreateDate DESC",token,("@company",company)));}

    [HttpPost("review-links"), EnableRateLimiting("provider-review")]
    public async Task<IActionResult> CreateReviewLink(ReviewLinkRequest request,CancellationToken token)
    {
        if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51006","CREATE",token))return Forbid();await EnsureSettings(db,company,user,token);var expiry=await ProviderDb.Scalar<int>(db,"SELECT ReviewExpiryDays FROM dbo.TDPRSystemSetting WHERE CompanyID=@company",token,("@company",company));var profile=await ProviderDb.Query(db,"SELECT ProviderID id,PublishedRevisionID revision FROM dbo.TDPRProviderProfile WHERE CompanyID=@company AND PublishedRevisionID IS NOT NULL AND StatusCode<>N'SUSPENDED'",token,("@company",company));if(profile.Count==0)return Conflict(new{message="ต้องมีโปรไฟล์ที่อนุมัติแล้ว"});var provider=Convert.ToInt64(profile[0]["id"]);var revision=Convert.ToInt64(profile[0]["revision"]);if(await ProviderDb.Scalar<int>(db,"SELECT COUNT(*) FROM dbo.TDPRProviderService WHERE RevisionID=@revision AND ServiceTypeID=@service",token,("@revision",revision),("@service",request.ServiceTypeId))==0)return BadRequest(new{message="ประเภทบริการไม่อยู่ในโปรไฟล์"});if(request.BranchId.HasValue&&await ProviderDb.Scalar<int>(db,"SELECT COUNT(*) FROM dbo.TDPRProviderBranch WHERE ProviderBranchID=@branch AND RevisionID=@revision",token,("@branch",request.BranchId),("@revision",revision))==0)return BadRequest(new{message="สาขาไม่ถูกต้อง"});var raw=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var hash=Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(raw)));var id=await ProviderDb.Scalar<long>(db,"INSERT dbo.TDPRReviewInvite(CompanyID,ProviderID,ProviderBranchID,ServiceTypeID,TokenHash,ServiceDate,ReferenceNo,ExpiresAt,CreateBy) OUTPUT INSERTED.ReviewInviteID VALUES(@company,@provider,@branch,@service,@hash,@date,@reference,DATEADD(day,@expiry,SYSUTCDATETIME()),@user)",token,("@company",company),("@provider",provider),("@branch",request.BranchId),("@service",request.ServiceTypeId),("@hash",hash),("@date",request.ServiceDate.Date),("@reference",Clean(request.ReferenceNo)),("@expiry",expiry),("@user",user));return Ok(new{id,token=raw,url=$"/providers/review/{raw}"});
    }

    [HttpDelete("review-links/{id:long}")]
    public async Task<IActionResult> CancelReviewLink(long id,CancellationToken token){if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51006","CANCEL",token)&&!await Can(db,"51006","DELETE",token))return Forbid();var changed=await ProviderDb.Execute(db,"UPDATE dbo.TDPRReviewInvite SET StatusCode=N'CANCELLED',UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ReviewInviteID=@id AND CompanyID=@company AND StatusCode=N'ACTIVE'",token,("@id",id),("@company",company),("@user",user));return changed>0?NoContent():Conflict(new{message="ยกเลิกไม่ได้"});}

    [HttpGet("reviews")]
    public async Task<IActionResult> Reviews(CancellationToken token){var support=SupportScope();long? company=null;if(!support){if(!CompanyScope(out var scopedCompany,out _))return Forbid();company=scopedCompany;}await using var db=await Open(token);if(!await Can(db,"51007","VIEW",token))return Forbid();return Ok(await ProviderDb.Query(db,"SELECT r.ReviewID id,r.CompanyID companyId,c.CustomerNameTH companyName,s.ServiceName serviceName,r.QualityScore quality,r.PunctualityScore punctuality,r.ServiceScore service,r.ValueScore value,r.CommentText comment,r.IsHidden hidden,r.HiddenReason hiddenReason,r.CreatedAt createdAt FROM dbo.TDPRReview r JOIN dbo.TDPRServiceType s ON s.ServiceTypeID=r.ServiceTypeID JOIN dbo.TDSTCompanySetUp c ON c.CompanyID=r.CompanyID WHERE (@company IS NULL OR r.CompanyID=@company) ORDER BY r.CreatedAt DESC",token,("@company",company)));}

    [HttpPost("reviews/{id:long}/moderate")]
    public async Task<IActionResult> Moderate(long id,ModerateRequest request,CancellationToken token){if(!SupportScope())return Forbid();if(Clean(request.Reason) is null)return BadRequest(new{message="ระบุเหตุผล"});await using var db=await Open(token);if(!await Can(db,"51007","MODERATE",token))return Forbid();return await ProviderDb.Execute(db,"UPDATE dbo.TDPRReview SET IsHidden=@hidden,HiddenReason=@reason,HiddenBy=@user,HiddenAt=SYSUTCDATETIME() WHERE ReviewID=@id",token,("@hidden",request.Hidden),("@reason",Clean(request.Reason)),("@user",ActorId()),("@id",id))>0?NoContent():NotFound();}

    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard(CancellationToken token){var support=SupportScope();long? company=null;if(!support){if(!CompanyScope(out var scopedCompany,out _))return Forbid();company=scopedCompany;}await using var db=await Open(token);if(!await Can(db,"51008","VIEW",token))return Forbid();var summary=(await ProviderDb.Query(db,"SELECT COUNT(*) totalReviews,CAST(ISNULL(AVG(CAST((QualityScore+PunctualityScore+ServiceScore+ValueScore)/4.0 AS decimal(6,3))),0) AS decimal(4,2)) averageRating,SUM(CASE WHEN IsHidden=1 THEN 1 ELSE 0 END) hiddenReviews FROM dbo.TDPRReview WHERE (@company IS NULL OR CompanyID=@company)",token,("@company",company))).Single();var byService=await ProviderDb.Query(db,"SELECT s.ServiceName name,COUNT(*) reviewCount,CAST(AVG(CAST((r.QualityScore+r.PunctualityScore+r.ServiceScore+r.ValueScore)/4.0 AS decimal(6,3))) AS decimal(4,2)) averageRating FROM dbo.TDPRReview r JOIN dbo.TDPRServiceType s ON s.ServiceTypeID=r.ServiceTypeID WHERE (@company IS NULL OR r.CompanyID=@company) AND r.IsHidden=0 GROUP BY s.ServiceName ORDER BY reviewCount DESC",token,("@company",company));return Ok(new{summary,byService});}
}
