using System.Data;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace LaooProviderModule.Controllers;

[ApiController,Authorize,Route("api/company/provider")]
public sealed class ProviderProfileController(IConfiguration configuration):ProviderControllerBase(configuration)
{
    [HttpGet("profile")]
    public async Task<IActionResult> Profile(CancellationToken token)
    {
        if(!CompanyScope(out var company,out _))return Forbid();await using var db=await Open(token);if(!await Can(db,"51004","VIEW",token))return Forbid();
        var rows=await ProviderDb.Query(db,"SELECT p.ProviderID id,p.Slug slug,p.StatusCode status,p.ReturnReason returnReason,p.SuspendedReason suspendedReason,r.RevisionID revisionId,r.RevisionNo revisionNo,r.DisplayName displayName,r.SummaryText summary,r.PublicAddress address,r.PublicTelephone telephone,r.PublicEmail email,r.LineID lineId,r.LineUrl lineUrl,r.WebsiteUrl websiteUrl FROM dbo.TDPRProviderProfile p JOIN dbo.TDPRProviderRevision r ON r.RevisionID=p.CurrentRevisionID WHERE p.CompanyID=@company",token,("@company",company));if(rows.Count==0)return Ok(new{status="NEW"});
        var revision=Convert.ToInt64(rows[0]["revisionId"]);rows[0]["serviceTypeIds"]=(await ProviderDb.Query(db,"SELECT ServiceTypeID id FROM dbo.TDPRProviderService WHERE RevisionID=@revision",token,("@revision",revision))).Select(x=>x["id"]);rows[0]["areaIds"]=(await ProviderDb.Query(db,"SELECT LocationID id FROM dbo.TDPRProviderArea WHERE RevisionID=@revision",token,("@revision",revision))).Select(x=>x["id"]);rows[0]["branches"]=await ProviderDb.Query(db,"SELECT ProviderBranchID id,BranchID branchId,BranchName name,AddressText address,Telephone telephone,Latitude latitude,Longitude longitude,IsPrimary isPrimary FROM dbo.TDPRProviderBranch WHERE RevisionID=@revision ORDER BY IsPrimary DESC,BranchName",token,("@revision",revision));return Ok(rows[0]);
    }

    [HttpPut("profile")]
    public async Task<IActionResult> SaveProfile(ProfileRequest request,CancellationToken token)
    {
        var name=Clean(request.DisplayName);var slug=Clean(request.Slug)?.ToLowerInvariant();var services=(request.ServiceTypeIds??[]).Distinct().Where(x=>x>0).ToList();var areas=(request.AreaIds??[]).Distinct().Where(x=>x>0).ToList();if(name is null||slug is null||!Regex.IsMatch(slug,"^[a-z0-9][a-z0-9-]{2,159}$")||services.Count==0||areas.Count==0)return BadRequest(new{message="ระบุชื่อ Slug ประเภทบริการ และพื้นที่ให้บริการ"});if(!ValidUrl(request.WebsiteUrl)||!ValidUrl(request.LineUrl))return BadRequest(new{message="URL ไม่ถูกต้อง"});if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51004","EDIT",token))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(token);
        try{
            foreach(var service in services)if(await ProviderDb.Scalar<int>(db,tx,"SELECT COUNT(*) FROM dbo.TDPRServiceType WHERE ServiceTypeID=@id AND IsActive=1",token,("@id",service))==0)throw new InvalidOperationException("มีประเภทบริการที่ไม่ถูกต้อง");
            foreach(var area in areas)if(await ProviderDb.Scalar<int>(db,tx,"SELECT COUNT(*) FROM dbo.TDPRLocation WHERE LocationID=@id AND IsActive=1",token,("@id",area))==0)throw new InvalidOperationException("มีพื้นที่ให้บริการที่ไม่ถูกต้อง");
            var existing=await ProviderDb.Query(db,tx,"SELECT ProviderID id,StatusCode status FROM dbo.TDPRProviderProfile WITH(UPDLOCK,HOLDLOCK) WHERE CompanyID=@company",token,("@company",company));long provider;int revNo;
            if(existing.Count==0){provider=await ProviderDb.Scalar<long>(db,tx,"INSERT dbo.TDPRProviderProfile(CompanyID,Slug,StatusCode,CreateBy) OUTPUT INSERTED.ProviderID VALUES(@company,@slug,N'DRAFT',@user)",token,("@company",company),("@slug",slug),("@user",user));revNo=1;}
            else{provider=Convert.ToInt64(existing[0]["id"]);if(Convert.ToString(existing[0]["status"])=="SUBMITTED"){await tx.RollbackAsync(token);return Conflict(new{message="โปรไฟล์อยู่ระหว่างอนุมัติ"});}revNo=await ProviderDb.Scalar<int>(db,tx,"SELECT ISNULL(MAX(RevisionNo),0)+1 FROM dbo.TDPRProviderRevision WHERE ProviderID=@provider",token,("@provider",provider));await ProviderDb.Execute(db,tx,"UPDATE dbo.TDPRProviderProfile SET Slug=@slug,StatusCode=N'DRAFT',ReturnReason=NULL,SuspendedReason=NULL,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ProviderID=@provider",token,("@slug",slug),("@user",user),("@provider",provider));}
            var revision=await ProviderDb.Scalar<long>(db,tx,"INSERT dbo.TDPRProviderRevision(ProviderID,CompanyID,RevisionNo,DisplayName,SummaryText,PublicAddress,PublicTelephone,PublicEmail,LineID,LineUrl,WebsiteUrl,StatusCode,CreateBy) OUTPUT INSERTED.RevisionID VALUES(@provider,@company,@rev,@name,@summary,@address,@phone,@email,@lineId,@lineUrl,@website,N'DRAFT',@user)",token,("@provider",provider),("@company",company),("@rev",revNo),("@name",name),("@summary",Clean(request.Summary)),("@address",Clean(request.Address)),("@phone",Clean(request.Telephone)),("@email",Clean(request.Email)),("@lineId",Clean(request.LineId)),("@lineUrl",Clean(request.LineUrl)),("@website",Clean(request.WebsiteUrl)),("@user",user));
            foreach(var service in services)await ProviderDb.Execute(db,tx,"INSERT dbo.TDPRProviderService(CompanyID,RevisionID,ServiceTypeID,CreateBy) VALUES(@company,@revision,@service,@user)",token,("@company",company),("@revision",revision),("@service",service),("@user",user));
            foreach(var area in areas)await ProviderDb.Execute(db,tx,"INSERT dbo.TDPRProviderArea(CompanyID,RevisionID,LocationID,CreateBy) VALUES(@company,@revision,@area,@user)",token,("@company",company),("@revision",revision),("@area",area),("@user",user));
            var branches=request.Branches??[];if(branches.Count==0)throw new InvalidOperationException("ระบุสาขาที่ให้บริการอย่างน้อย 1 แห่ง");
            foreach(var branch in branches){if(branch.BranchId.HasValue&&await ProviderDb.Scalar<int>(db,tx,"SELECT COUNT(*) FROM dbo.TDADBranch WHERE CompanyID=@company AND BranchID=@branch AND IsActive=1",token,("@company",company),("@branch",branch.BranchId))==0)throw new InvalidOperationException("สาขาไม่อยู่ในบริษัท");await ProviderDb.Execute(db,tx,"INSERT dbo.TDPRProviderBranch(CompanyID,RevisionID,BranchID,BranchName,AddressText,Telephone,Latitude,Longitude,IsPrimary,CreateBy) VALUES(@company,@revision,@branch,@name,@address,@phone,@lat,@lng,@primary,@user)",token,("@company",company),("@revision",revision),("@branch",branch.BranchId),("@name",Clean(branch.Name)??"สำนักงานใหญ่"),("@address",Clean(branch.Address)),("@phone",Clean(branch.Telephone)),("@lat",branch.Latitude),("@lng",branch.Longitude),("@primary",branch.IsPrimary),("@user",user));}
            await ProviderDb.Execute(db,tx,"UPDATE dbo.TDPRProviderProfile SET CurrentRevisionID=@revision WHERE ProviderID=@provider",token,("@revision",revision),("@provider",provider));await Audit(db,tx,company,"PROFILE",provider,"EDIT",null,user,token);await tx.CommitAsync(token);return Ok(new{id=provider,revisionId=revision});
        }catch(InvalidOperationException e){await tx.RollbackAsync(token);return BadRequest(new{message=e.Message});}catch(SqlException e) when(e.Number is 2601 or 2627){await tx.RollbackAsync(token);return Conflict(new{message="Slug นี้ถูกใช้แล้ว"});}
    }

    [HttpPost("profile/submit")]
    public async Task<IActionResult> Submit(CancellationToken token){if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51004","SUBMIT",token))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(token);var rows=await ProviderDb.Query(db,tx,"SELECT ProviderID id,CurrentRevisionID revision FROM dbo.TDPRProviderProfile WITH(UPDLOCK,HOLDLOCK) WHERE CompanyID=@company AND StatusCode IN(N'DRAFT',N'RETURNED',N'WITHDRAWN')",token,("@company",company));if(rows.Count==0){await tx.RollbackAsync(token);return Conflict(new{message="สถานะไม่พร้อมส่งอนุมัติ"});}await ProviderDb.Execute(db,tx,"UPDATE dbo.TDPRProviderProfile SET StatusCode=N'SUBMITTED',SubmittedAt=SYSUTCDATETIME(),UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ProviderID=@id;UPDATE dbo.TDPRProviderRevision SET StatusCode=N'SUBMITTED',UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE RevisionID=@revision",token,("@user",user),("@id",rows[0]["id"]),("@revision",rows[0]["revision"]));await tx.CommitAsync(token);return NoContent();}

    [HttpPost("profile/withdraw")]
    public async Task<IActionResult> Withdraw(CancellationToken token){if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51004","WITHDRAW",token))return Forbid();await using var tx=(SqlTransaction)await db.BeginTransactionAsync(token);var rows=await ProviderDb.Query(db,tx,"SELECT ProviderID id,CurrentRevisionID revision FROM dbo.TDPRProviderProfile WITH(UPDLOCK,HOLDLOCK) WHERE CompanyID=@company AND StatusCode=N'SUBMITTED'",token,("@company",company));if(rows.Count==0){await tx.RollbackAsync(token);return Conflict(new{message="ถอนได้เฉพาะรายการที่รออนุมัติ"});}await ProviderDb.Execute(db,tx,"UPDATE dbo.TDPRProviderProfile SET StatusCode=N'WITHDRAWN',UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ProviderID=@id;UPDATE dbo.TDPRProviderRevision SET StatusCode=N'WITHDRAWN',UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE RevisionID=@revision",token,("@user",user),("@id",rows[0]["id"]),("@revision",rows[0]["revision"]));await tx.CommitAsync(token);return NoContent();}
}
