using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace LaooProviderModule.Controllers;

[ApiController,Authorize,Route("api/company/provider")]
public sealed class ProviderMasterController(IConfiguration configuration,IWebHostEnvironment environment):ProviderControllerBase(configuration)
{
    static readonly string[] Menus=["51001","51002","51003","51004","51005","51006","51007","51008","51009"];
    [HttpGet("actions/{menu}")]
    public async Task<IActionResult> Actions(string menu,CancellationToken token){if(!Menus.Contains(menu))return Forbid();await using var db=await Open(token);var names=new[]{"VIEW","CREATE","EDIT","DELETE","SUBMIT","WITHDRAW","APPROVE","RETURN","SUSPEND","CANCEL","MODERATE","EXPORT"};var result=new Dictionary<string,bool>();foreach(var name in names)result[name.ToLowerInvariant()]=await Can(db,menu,name,token);return Ok(result);}

    [HttpGet("settings")]
    public async Task<IActionResult> Settings(CancellationToken token){if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51001","VIEW",token))return Forbid();await EnsureSettings(db,company,user,token);return Ok((await ProviderDb.Query(db,"SELECT ServiceCoverMaxMB serviceCoverMaxMb,ReviewExpiryDays reviewExpiryDays,BayesianMinimumReviews bayesianMinimumReviews,RatingWeightNoGps ratingWeightNoGps,RecencyWeightNoGps recencyWeightNoGps,RatingWeightGps ratingWeightGps,DistanceWeightGps distanceWeightGps,RecencyWeightGps recencyWeightGps,MaxDistanceKm maxDistanceKm FROM dbo.TDPRSystemSetting WHERE CompanyID=@company",token,("@company",company))).Single());}
    [HttpPut("settings")]
    public async Task<IActionResult> Settings(ProviderSettings request,CancellationToken token){if(request.ServiceCoverMaxMb is <1 or >10||request.ReviewExpiryDays is <1 or >90||request.BayesianMinimumReviews is <1 or >100||request.MaxDistanceKm is <1 or >1000)return BadRequest(new{message="ค่าตั้งค่าไม่ถูกต้อง"});if(Math.Abs(request.RatingWeightNoGps+request.RecencyWeightNoGps-100)>0.01||Math.Abs(request.RatingWeightGps+request.DistanceWeightGps+request.RecencyWeightGps-100)>0.01)return BadRequest(new{message="ผลรวมน้ำหนักต้องเท่ากับ 100"});if(!CompanyScope(out var company,out var user))return Forbid();await using var db=await Open(token);if(!await Can(db,"51001","EDIT",token))return Forbid();await EnsureSettings(db,company,user,token);await ProviderDb.Execute(db,"UPDATE dbo.TDPRSystemSetting SET ServiceCoverMaxMB=@cover,ReviewExpiryDays=@expiry,BayesianMinimumReviews=@minimum,RatingWeightNoGps=@rng,RecencyWeightNoGps=@cng,RatingWeightGps=@rg,DistanceWeightGps=@dg,RecencyWeightGps=@cg,MaxDistanceKm=@distance,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE CompanyID=@company",token,("@cover",request.ServiceCoverMaxMb),("@expiry",request.ReviewExpiryDays),("@minimum",request.BayesianMinimumReviews),("@rng",request.RatingWeightNoGps),("@cng",request.RecencyWeightNoGps),("@rg",request.RatingWeightGps),("@dg",request.DistanceWeightGps),("@cg",request.RecencyWeightGps),("@distance",request.MaxDistanceKm),("@user",user),("@company",company));return NoContent();}

    [HttpGet("locations")]
    public async Task<IActionResult> Locations(CancellationToken token){await using var db=await Open(token);if(!await Can(db,"51002","VIEW",token))return Forbid();return Ok(await ProviderDb.Query(db,"SELECT l.LocationID id,l.LocationCode code,l.LocationType type,l.ParentLocationID parentId,p.NameTH parentName,l.NameTH name,l.NameEN nameEn,l.Latitude latitude,l.Longitude longitude,l.SortOrder sortOrder,l.IsActive active FROM dbo.TDPRLocation l LEFT JOIN dbo.TDPRLocation p ON p.LocationID=l.ParentLocationID ORDER BY CASE l.LocationType WHEN N'PROVINCE' THEN 1 WHEN N'DISTRICT' THEN 2 ELSE 3 END,p.NameTH,l.SortOrder,l.NameTH",token));}
    [HttpPost("locations")] public Task<IActionResult> SaveLocation(LocationRequest request,CancellationToken token)=>SaveLocation(null,request,"CREATE",token);
    [HttpPut("locations/{id:long}")] public Task<IActionResult> SaveLocation(long id,LocationRequest request,CancellationToken token)=>SaveLocation(id,request,"EDIT",token);
    async Task<IActionResult> SaveLocation(long? id,LocationRequest request,string action,CancellationToken token){var code=Clean(request.Code)?.ToUpperInvariant();var name=Clean(request.Name);var type=Clean(request.Type)?.ToUpperInvariant();if(code is null||name is null||type is not ("PROVINCE" or "DISTRICT" or "SUBDISTRICT")||(type!="PROVINCE"&&!request.ParentId.HasValue))return BadRequest(new{message="ข้อมูลพื้นที่ไม่ครบ"});if(!SupportScope())return Forbid();await using var db=await Open(token);if(!await Can(db,"51002",action,token))return Forbid();if(request.ParentId.HasValue&&await ProviderDb.Scalar<int>(db,"SELECT COUNT(*) FROM dbo.TDPRLocation WHERE LocationID=@parent AND IsActive=1",token,("@parent",request.ParentId))==0)return BadRequest(new{message="ไม่พบพื้นที่แม่"});try{var sql=id.HasValue?"UPDATE dbo.TDPRLocation SET LocationCode=@code,LocationType=@type,ParentLocationID=@parent,NameTH=@name,NameEN=@nameEn,Latitude=@lat,Longitude=@lng,SortOrder=@sort,IsActive=@active,UpdateDate=SYSUTCDATETIME() OUTPUT INSERTED.LocationID WHERE LocationID=@id":"INSERT dbo.TDPRLocation(LocationCode,LocationType,ParentLocationID,NameTH,NameEN,Latitude,Longitude,SortOrder,IsActive) OUTPUT INSERTED.LocationID VALUES(@code,@type,@parent,@name,@nameEn,@lat,@lng,@sort,@active)";var saved=await ProviderDb.Scalar<long>(db,sql,token,("@id",id),("@code",code),("@type",type),("@parent",request.ParentId),("@name",name),("@nameEn",Clean(request.NameEn)),("@lat",request.Latitude),("@lng",request.Longitude),("@sort",request.SortOrder),("@active",request.Active));return saved>0?Ok(new{id=saved}):NotFound();}catch(SqlException e) when(e.Number is 2601 or 2627){return Conflict(new{message="รหัสพื้นที่ซ้ำ"});}}
    [HttpDelete("locations/{id:long}")]
    public async Task<IActionResult> DeleteLocation(long id,CancellationToken token){if(!SupportScope())return Forbid();await using var db=await Open(token);if(!await Can(db,"51002","DELETE",token))return Forbid();if(await ProviderDb.Scalar<int>(db,"SELECT (SELECT COUNT(*) FROM dbo.TDPRLocation WHERE ParentLocationID=@id)+(SELECT COUNT(*) FROM dbo.TDPRProviderArea WHERE LocationID=@id)",token,("@id",id))>0)return Conflict(new{message="พื้นที่ถูกใช้งานแล้ว ให้ปิดใช้งานแทน"});return await ProviderDb.Execute(db,"DELETE dbo.TDPRLocation WHERE LocationID=@id",token,("@id",id))==1?NoContent():NotFound();}

    [HttpGet("service-types")]
    public async Task<IActionResult> ServiceTypes(CancellationToken token){await using var db=await Open(token);if(!await Can(db,"51003","VIEW",token))return Forbid();return Ok(await ProviderDb.Query(db,"SELECT s.ServiceTypeID id,s.ServiceCode code,s.ServiceName name,s.DescriptionText description,s.IconName iconName,s.CoverImagePath coverImagePath,s.CoverMimeType coverMimeType,s.CoverSizeBytes coverSizeBytes,s.SortOrder sortOrder,s.IsActive active,COUNT(DISTINCT CASE WHEN p.PublishedRevisionID=ps.RevisionID AND p.IsActive=1 AND p.StatusCode<>N'SUSPENDED' THEN p.CompanyID END) providerCount FROM dbo.TDPRServiceType s LEFT JOIN dbo.TDPRProviderService ps ON ps.ServiceTypeID=s.ServiceTypeID LEFT JOIN dbo.TDPRProviderProfile p ON p.PublishedRevisionID=ps.RevisionID GROUP BY s.ServiceTypeID,s.ServiceCode,s.ServiceName,s.DescriptionText,s.IconName,s.CoverImagePath,s.CoverMimeType,s.CoverSizeBytes,s.SortOrder,s.IsActive ORDER BY s.SortOrder,s.ServiceName",token));}
    [HttpPost("service-types")] public Task<IActionResult> SaveService(ServiceTypeRequest request,CancellationToken token)=>SaveService(null,request,"CREATE",token);
    [HttpPut("service-types/{id:long}")] public Task<IActionResult> SaveService(long id,ServiceTypeRequest request,CancellationToken token)=>SaveService(id,request,"EDIT",token);
    async Task<IActionResult> SaveService(long? id,ServiceTypeRequest request,string action,CancellationToken token){var code=Clean(request.Code)?.ToUpperInvariant();var name=Clean(request.Name);if(code is null||name is null)return BadRequest(new{message="ระบุรหัสและชื่อประเภทบริการ"});if(!SupportScope())return Forbid();var user=ActorId();await using var db=await Open(token);if(!await Can(db,"51003",action,token))return Forbid();try{var sql=id.HasValue?"UPDATE dbo.TDPRServiceType SET ServiceCode=@code,ServiceName=@name,DescriptionText=@description,IconName=@icon,SortOrder=@sort,IsActive=@active,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() OUTPUT INSERTED.ServiceTypeID WHERE ServiceTypeID=@id":"INSERT dbo.TDPRServiceType(ServiceCode,ServiceName,DescriptionText,IconName,SortOrder,IsActive,CreateBy) OUTPUT INSERTED.ServiceTypeID VALUES(@code,@name,@description,@icon,@sort,@active,@user)";var saved=await ProviderDb.Scalar<long>(db,sql,token,("@id",id),("@code",code),("@name",name),("@description",Clean(request.Description)),("@icon",Clean(request.IconName)),("@sort",request.SortOrder),("@active",request.Active),("@user",user));return saved>0?Ok(new{id=saved}):NotFound();}catch(SqlException e) when(e.Number is 2601 or 2627){return Conflict(new{message="รหัสประเภทบริการซ้ำ"});}}
    [HttpPost("service-types/{id:long}/cover"),RequestSizeLimit(10*1024*1024)]
    public async Task<IActionResult> UploadCover(long id,IFormFile file,CancellationToken token){if(!SupportScope())return Forbid();var user=ActorId();await using var db=await Open(token);if(!await Can(db,"51003","EDIT",token))return Forbid();const int max=2;var ext=Path.GetExtension(file.FileName).TrimStart('.').ToLowerInvariant();if(file.Length<=0||file.Length>(long)max*1024*1024||!new[]{"jpg","jpeg","png","webp"}.Contains(ext))return BadRequest(new{message=$"รูปปกต้องเป็น JPG, PNG หรือ WEBP และไม่เกิน {max} MB"});if(await ProviderDb.Scalar<int>(db,"SELECT COUNT(*) FROM dbo.TDPRServiceType WHERE ServiceTypeID=@id",token,("@id",id))==0)return NotFound();var relative=Path.Combine("uploads","provider","service-types",id.ToString());var root=environment.WebRootPath??Path.Combine(environment.ContentRootPath,"wwwroot");var folder=Path.Combine(root,relative);Directory.CreateDirectory(folder);var stored=$"{Guid.NewGuid():N}.{ext}";await using(var output=System.IO.File.Create(Path.Combine(folder,stored)))await file.CopyToAsync(output,token);var path=(relative+"/"+stored).Replace((char)92,'/');await ProviderDb.Execute(db,"UPDATE dbo.TDPRServiceType SET CoverImagePath=@path,CoverMimeType=@mime,CoverSizeBytes=@size,UpdateBy=@user,UpdateDate=SYSUTCDATETIME() WHERE ServiceTypeID=@id",token,("@path",path),("@mime",file.ContentType),("@size",file.Length),("@user",user),("@id",id));return Ok(new{coverImagePath=path,sizeBytes=file.Length});}
    [HttpDelete("service-types/{id:long}")]
    public async Task<IActionResult> DeleteService(long id,CancellationToken token){if(!SupportScope())return Forbid();await using var db=await Open(token);if(!await Can(db,"51003","DELETE",token))return Forbid();if(await ProviderDb.Scalar<int>(db,"SELECT (SELECT COUNT(*) FROM dbo.TDPRProviderService WHERE ServiceTypeID=@id)+(SELECT COUNT(*) FROM dbo.TDPRReviewInvite WHERE ServiceTypeID=@id)",token,("@id",id))>0)return Conflict(new{message="ประเภทบริการถูกใช้งานแล้ว ให้ปิดใช้งานแทน"});return await ProviderDb.Execute(db,"DELETE dbo.TDPRServiceType WHERE ServiceTypeID=@id",token,("@id",id))==1?NoContent():NotFound();}
}
